package thaumcraft.common.research;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import thaumcraft.common.research.TCResearchRequirementResolver.ItemRequirementResolution;
import thaumcraft.common.research.TCResearchRequirementResolver.KnowledgeRequirementResolution;

final class TCResearchRequirementAudit {
    private TCResearchRequirementAudit() {
    }

    static Report buildReport(int detailLimit) {
        int itemTotal = 0;
        int itemUnresolved = 0;
        int craftTotal = 0;
        int craftUnresolved = 0;
        int knowledgeTotal = 0;
        int knowledgeUnresolved = 0;
        ArrayList<String> details = new ArrayList<>();
        LinkedHashMap<String, Integer> summary = new LinkedHashMap<>();
        ArrayList<String> bridgeDetails = new ArrayList<>();
        LinkedHashMap<String, Integer> bridgeSummary = new LinkedHashMap<>();

        for (TCResearchEntryDefinition entry : TCResearchManager.entries()) {
            for (int stageIndex = 0; stageIndex < entry.stages().size(); stageIndex++) {
                TCResearchStageDefinition stage = entry.stages().get(stageIndex);
                String stageLabel = entry.key() + " stage " + (stageIndex + 1);

                for (String required : stage.requiredItem()) {
                    itemTotal++;
                    ItemRequirementResolution resolution = TCResearchRequirementResolver.resolveItemRequirement(required);
                    if (!resolution.resolved()) {
                        itemUnresolved++;
                        recordUnresolved(details, summary, detailLimit, stageLabel, "required_item", required, resolution.reason(), resolution.summaryKey());
                    } else {
                        recordBridgeIfNeeded(bridgeDetails, bridgeSummary, detailLimit, stageLabel, "required_item", required, resolution);
                    }
                }

                for (String required : stage.requiredCraft()) {
                    craftTotal++;
                    ItemRequirementResolution resolution = TCResearchRequirementResolver.resolveItemRequirement(required);
                    if (!resolution.resolved()) {
                        craftUnresolved++;
                        recordUnresolved(details, summary, detailLimit, stageLabel, "required_craft", required, resolution.reason(), resolution.summaryKey());
                    } else {
                        recordBridgeIfNeeded(bridgeDetails, bridgeSummary, detailLimit, stageLabel, "required_craft", required, resolution);
                    }
                }

                for (String required : stage.requiredKnowledge()) {
                    knowledgeTotal++;
                    KnowledgeRequirementResolution resolution = TCResearchRequirementResolver.resolveKnowledgeRequirement(required);
                    if (!resolution.resolved()) {
                        knowledgeUnresolved++;
                        recordUnresolved(details, summary, detailLimit, stageLabel, "required_knowledge", required, resolution.reason(), resolution.summaryKey());
                    }
                }
            }
        }

        return new Report(
                itemTotal,
                itemUnresolved,
                craftTotal,
                craftUnresolved,
                knowledgeTotal,
                knowledgeUnresolved,
                details,
                summary,
                bridgeDetails,
                bridgeSummary
        );
    }

    static Report writeMarkdown(Path output, int detailLimit) throws IOException {
        Report report = buildReport(detailLimit);
        Path parent = output.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        try (BufferedWriter writer = Files.newBufferedWriter(output, StandardCharsets.UTF_8)) {
            writer.write("# Research requirement runtime audit");
            writer.newLine();
            writer.newLine();
            writer.write("Generated by the NeoForge runtime audit exporter after server data reload.");
            writer.newLine();
            writer.write("Equivalent command: `/tc research requirements " + detailLimit + "`");
            writer.newLine();
            writer.newLine();
            writer.write("| Requirement class | Result |");
            writer.newLine();
            writer.write("|---|---:|");
            writer.newLine();
            writer.write("| `required_item` | `" + report.itemResolved() + "/" + report.itemTotal() + "` resolved |");
            writer.newLine();
            writer.write("| `required_craft` | `" + report.craftResolved() + "/" + report.craftTotal() + "` modern-matchable |");
            writer.newLine();
            writer.write("| `required_knowledge` | `" + report.knowledgeResolved() + "/" + report.knowledgeTotal() + "` resolved |");
            writer.newLine();
            writer.write("| Total unresolved item/craft/knowledge requirements | `" + report.unresolvedTotal() + "` |");
            writer.newLine();
            writer.write("| Identity bridge / placeholder warnings | `" + report.bridgeWarningTotal() + "` |");
            writer.newLine();
            writer.newLine();
            writer.write("`required_craft` modern-matchable means the current `ItemCraftedEvent` marker path can identify the crafted stack. Exact legacy `ItemStack.toString().hashCode()` parity is still a separate exporter/mapping task.");
            writer.newLine();
            writer.write("Bridge warnings are not parser failures. They mark requirements whose registry identity is resolvable, but whose final gameplay source, item semantics, recipe flow, or legacy container/component behavior is still a migration boundary.");
            writer.newLine();
            writer.write("Aspect stack, stored-enchantment and legacy item component requirements are no longer counted as bridge warnings when their legacy NBT/metadata semantics are carried by modern DataComponent or vanilla enchantment-component payloads. Safe 1.12-to-1.21 identity remaps and implemented research-table/scribing-tools requirements are also not counted as bridge warnings.");
            writer.newLine();
            writer.newLine();
            writer.write("## Unresolved Summary");
            writer.newLine();
            writer.newLine();
            if (report.unresolvedSummary().isEmpty()) {
                writer.write("No unresolved stage requirements.");
                writer.newLine();
            } else {
                writer.write("| Count | Bucket |");
                writer.newLine();
                writer.write("|---:|---|");
                writer.newLine();
                for (Map.Entry<String, Integer> entry : report.sortedUnresolvedSummary()) {
                    writer.write("| " + entry.getValue() + " | `" + escapeTableCell(entry.getKey()) + "` |");
                    writer.newLine();
                }
            }
            writer.newLine();
            writer.write("## Bridge / Placeholder Warning Summary");
            writer.newLine();
            writer.newLine();
            if (report.bridgeWarningSummary().isEmpty()) {
                writer.write("No bridge or placeholder warnings.");
                writer.newLine();
            } else {
                writer.write("| Count | Bucket |");
                writer.newLine();
                writer.write("|---:|---|");
                writer.newLine();
                for (Map.Entry<String, Integer> entry : report.sortedBridgeWarningSummary()) {
                    writer.write("| " + entry.getValue() + " | `" + escapeTableCell(entry.getKey()) + "` |");
                    writer.newLine();
                }
            }
            writer.newLine();
            writer.write("## Bridge / Placeholder Warning Details");
            writer.newLine();
            writer.newLine();
            writer.write("Detail limit: `" + detailLimit + "`.");
            writer.newLine();
            writer.newLine();
            if (report.bridgeWarningDetails().isEmpty()) {
                writer.write("No bridge or placeholder detail rows.");
                writer.newLine();
            } else {
                for (String detail : report.bridgeWarningDetails()) {
                    writer.write("- `" + detail.replace("`", "\\`") + "`");
                    writer.newLine();
                }
            }
            writer.newLine();
            writer.write("## Unresolved Details");
            writer.newLine();
            writer.newLine();
            writer.write("Detail limit: `" + detailLimit + "`.");
            writer.newLine();
            writer.newLine();
            if (report.unresolvedDetails().isEmpty()) {
                writer.write("No unresolved detail rows.");
                writer.newLine();
            } else {
                for (String detail : report.unresolvedDetails()) {
                    writer.write("- `" + detail.replace("`", "\\`") + "`");
                    writer.newLine();
                }
            }
        }

        return report;
    }

    private static void recordUnresolved(
            List<String> details,
            LinkedHashMap<String, Integer> summary,
            int detailLimit,
            String stageLabel,
            String type,
            String raw,
            String reason,
            String summaryKey
    ) {
        String bucket = type + " " + summaryKey;
        summary.merge(bucket, 1, Integer::sum);

        if (details.size() >= detailLimit) {
            return;
        }
        details.add(stageLabel + " " + type + " raw=" + raw + " reason=" + reason);
    }

    private static void recordBridgeIfNeeded(
            List<String> details,
            LinkedHashMap<String, Integer> summary,
            int detailLimit,
            String stageLabel,
            String type,
            String raw,
            ItemRequirementResolution resolution
    ) {
        String bucket = bridgeBucket(raw, resolution);
        if (bucket.isBlank()) {
            return;
        }

        summary.merge(type + " " + bucket, 1, Integer::sum);
        if (details.size() >= detailLimit) {
            return;
        }
        details.add(stageLabel + " " + type + " raw=" + raw + " warning=" + bucket);
    }

    private static String bridgeBucket(String raw, ItemRequirementResolution resolution) {
        if (raw == null || raw.isBlank()) {
            return "";
        }

        String value = raw.trim().replace('\'', '"');
        if (value.startsWith("oredict:")) {
            return "legacy OreDictionary tag bridge";
        }

        String rawId = value.split(";")[0];
        String damageText = value.split(";").length > 2 ? value.split(";")[2] : "0";
        if (rawId.equals("minecraft:web") || rawId.equals("minecraft:noteblock") || rawId.equals("minecraft:dye")) {
            return "";
        }
        if (rawId.equals("thaumcraft:arcane_stone")) {
            return "";
        }
        if (rawId.equals("thaumcraft:crystal_essence")) {
            return hasAspectStackRequirement(resolution) ? "" : "aspect crystal essence bridge: flattened aspect variant before final component/container semantics";
        }
        if (rawId.equals("thaumcraft:phial")) {
            return hasAspectStackRequirement(resolution) ? "" : "essentia phial bridge: flattened aspect variant before final DataComponent/container semantics";
        }
        if (rawId.endsWith("thaumcraft:enchanted_placeholder")) {
            return hasStoredMagicRequirement(resolution) ? "" : "legacy enchanted placeholder bridge before final enchantment-component policy";
        }
        if (TCLegacyMaterialFamilyMappings.isMaterialFamily(rawId)) {
            return hasLegacyItemRequirement(resolution) ? "" : "legacy metadata material-family bridge";
        }
        String subsystem = subsystemPlaceholder(rawId, damageText);
        return subsystem == null ? "" : subsystem;
    }

    private static boolean hasAspectStackRequirement(ItemRequirementResolution resolution) {
        return resolution != null
                && resolution.resolved()
                && resolution.requirement() != null
                && resolution.requirement().hasAspectStackRequirement();
    }

    private static boolean hasStoredMagicRequirement(ItemRequirementResolution resolution) {
        return resolution != null
                && resolution.resolved()
                && resolution.requirement() != null
                && resolution.requirement().hasStoredMagicRequirement();
    }

    private static boolean hasLegacyItemRequirement(ItemRequirementResolution resolution) {
        return resolution != null
                && resolution.resolved()
                && resolution.requirement() != null
                && resolution.requirement().hasLegacyItemRequirement();
    }

    private static String subsystemPlaceholder(String rawId, String damageText) {
        if (rawId.equals("thaumcraft:nitor") && TCResearchRequirementResolver.parsePositiveInt(damageText, 0) == 4) {
            return "alchemy identity bridge before nitor recipe/subsystem semantics";
        }
        return switch (rawId) {
            case "thaumcraft:arcane_workbench",
                 "thaumcraft:wand_workbench" -> "research/crafting station placeholder before full UI/menu/recipe semantics";
            case "thaumcraft:caster_basic",
                 "thaumcraft:focus_1",
                 "thaumcraft:focus_2",
                 "thaumcraft:focus_3",
                 "thaumcraft:vis_resonator" -> "auromancy placeholder before focus/caster/vis semantics";
            case "thaumcraft:crucible",
                 "thaumcraft:smelter_basic",
                 "thaumcraft:tallow" -> "alchemy placeholder before crucible/smelter/container semantics";
            case "thaumcraft:infusion_matrix" -> "infusion placeholder before multiblock/recipe semantics";
            case "thaumcraft:thaumium_axe",
                 "thaumcraft:thaumium_hoe",
                 "thaumcraft:thaumium_pick",
                 "thaumcraft:thaumium_shovel",
                 "thaumcraft:thaumium_sword" -> "thaumium tool placeholder before tool material/enchant/repair semantics";
            case "thaumcraft:mirrored_glass" -> "artifice mirror placeholder before mirror behavior";
            case "thaumcraft:brain" -> "biological component identity before golem/brain subsystem semantics";
            case "thaumcraft:curio" -> "curio metadata identity bridge";
            default -> null;
        };
    }

    private static String escapeTableCell(String value) {
        return value.replace("|", "\\|");
    }

    record Report(
            int itemTotal,
            int itemUnresolved,
            int craftTotal,
            int craftUnresolved,
            int knowledgeTotal,
            int knowledgeUnresolved,
            List<String> unresolvedDetails,
            Map<String, Integer> unresolvedSummary,
            List<String> bridgeWarningDetails,
            Map<String, Integer> bridgeWarningSummary
    ) {
        Report {
            unresolvedDetails = List.copyOf(unresolvedDetails);
            unresolvedSummary = Map.copyOf(unresolvedSummary);
            bridgeWarningDetails = List.copyOf(bridgeWarningDetails);
            bridgeWarningSummary = Map.copyOf(bridgeWarningSummary);
        }

        int itemResolved() {
            return itemTotal - itemUnresolved;
        }

        int craftResolved() {
            return craftTotal - craftUnresolved;
        }

        int knowledgeResolved() {
            return knowledgeTotal - knowledgeUnresolved;
        }

        int unresolvedTotal() {
            return itemUnresolved + craftUnresolved + knowledgeUnresolved;
        }

        int bridgeWarningTotal() {
            return bridgeWarningSummary.values().stream().mapToInt(Integer::intValue).sum();
        }

        List<Map.Entry<String, Integer>> sortedUnresolvedSummary() {
            return unresolvedSummary.entrySet().stream()
                    .sorted(Map.Entry.<String, Integer>comparingByValue(Comparator.reverseOrder())
                            .thenComparing(Map.Entry.comparingByKey()))
                    .toList();
        }

        List<Map.Entry<String, Integer>> sortedBridgeWarningSummary() {
            return bridgeWarningSummary.entrySet().stream()
                    .sorted(Map.Entry.<String, Integer>comparingByValue(Comparator.reverseOrder())
                            .thenComparing(Map.Entry.comparingByKey()))
                    .toList();
        }
    }
}
