package thaumcraft.common.warp;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.util.FakePlayerFactory;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.research.TCPlayerKnowledge;
import thaumcraft.common.research.TCPlayerKnowledgeStore;

public final class TCWarpBehaviorAudit {
    private TCWarpBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Warp Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This validates the server-authoritative warp mutation/sync layer.");
        lines.add("- It includes the legacy `ThaumcraftApi.addWarpToItem` crafting-warp bridge for the currently registered TC6 item-warp entry.");
        lines.add("- It intentionally does not implement or claim the full legacy random WarpEvents/hallucination system.");
        lines.add("- `TCPlayerWarpStore` remains a persistence primitive; gameplay callers should use `TCWarpManager`.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        ServerPlayer player = FakePlayerFactory.getMinecraft(server.overworld());
        TCPlayerWarpStore.clear(player);
        TCPlayerKnowledgeStore.set(player, new TCPlayerKnowledge(), false);
        TCWarpClientCache.clear();
        TCWarpItemRegistry.bootstrap();

        checks.add(checkStorageRoundTrip());
        checks.add(checkManagerAddClampCounterAndSync(player));
        checks.add(checkManagerReduceClampAndMessage(player));
        checks.add(checkPayloadRoundTrip());
        checks.add(checkWarpResearchUnlock(player));
        checks.add(checkClearSync(player));
        checks.add(checkItemWarpRegistry());
        checks.add(checkCraftedItemWarpAppliesStickyNormalWarp(player));
        checks.add(checkCraftedItemWarpRespectsWussModeAndUnknownItems(player));

        return new Report(List.copyOf(checks));
    }

    private static Check checkStorageRoundTrip() {
        TCPlayerWarp warp = new TCPlayerWarp();
        warp.add(TCWarpType.PERMANENT, 600);
        warp.add(TCWarpType.NORMAL, 5);
        warp.add(TCWarpType.TEMPORARY, 3);
        warp.setCounter(7);
        TCPlayerWarp copy = TCPlayerWarp.load(warp.save());
        boolean passed = copy.get(TCWarpType.PERMANENT) == TCPlayerWarp.MAX_WARP
                && copy.get(TCWarpType.NORMAL) == 5
                && copy.get(TCWarpType.TEMPORARY) == 3
                && copy.getCounter() == 7
                && copy.actualWarp() == 505
                && copy.totalWarp() == 508;
        return check("storage_roundtrip_legacy_array_order_and_clamp", passed,
                "permanent=" + copy.get(TCWarpType.PERMANENT)
                        + ", normal=" + copy.get(TCWarpType.NORMAL)
                        + ", temporary=" + copy.get(TCWarpType.TEMPORARY)
                        + ", counter=" + copy.getCounter());
    }

    private static Check checkManagerAddClampCounterAndSync(ServerPlayer player) {
        TCPlayerWarpStore.clear(player);
        TCWarpClientCache.clear();
        int updated = TCWarpManager.add(player, TCWarpType.NORMAL, 4);
        TCPlayerWarp stored = TCPlayerWarpStore.get(player);
        TCWarpSyncPayload sync = TCWarpSyncPayload.from(stored);
        TCWarpClientCache.accept(sync);
        TCWarpMessagePayload message = TCWarpClientCache.pollMessage();
        boolean passed = updated == 4
                && stored.get(TCWarpType.NORMAL) == 4
                && stored.getCounter() == 4
                && TCWarpClientCache.currentWarp().get(TCWarpType.NORMAL) == 4
                && message == null;
        return check("manager_positive_add_sets_counter_and_sync_snapshot", passed,
                "updated=" + updated + ", counter=" + stored.getCounter());
    }

    private static Check checkManagerReduceClampAndMessage(ServerPlayer player) {
        TCPlayerWarpStore.clear(player);
        TCWarpClientCache.clear();
        TCWarpManager.add(player, TCWarpType.TEMPORARY, 2);
        int updated = TCWarpManager.reduce(player, TCWarpType.TEMPORARY, 5);
        TCPlayerWarp stored = TCPlayerWarpStore.get(player);
        TCWarpClientCache.accept(new TCWarpMessagePayload(TCWarpType.TEMPORARY, -2));
        TCWarpMessagePayload message = TCWarpClientCache.pollMessage();
        boolean passed = updated == 0
                && stored.get(TCWarpType.TEMPORARY) == 0
                && message != null
                && message.warpType() == TCWarpType.TEMPORARY
                && message.change() == -2;
        return check("manager_negative_reduce_clamps_to_zero_and_uses_actual_change", passed,
                "updated=" + updated + ", message=" + (message == null ? "missing" : message.warpType() + "/" + message.change()));
    }

    private static Check checkPayloadRoundTrip() {
        TCPlayerWarp warp = new TCPlayerWarp();
        warp.set(TCWarpType.PERMANENT, 1);
        warp.set(TCWarpType.NORMAL, 2);
        warp.set(TCWarpType.TEMPORARY, 3);
        warp.setCounter(6);
        TCWarpSyncPayload payload = TCWarpSyncPayload.from(warp);
        TCPlayerWarp copy = payload.toWarp();
        boolean passed = copy.get(TCWarpType.PERMANENT) == 1
                && copy.get(TCWarpType.NORMAL) == 2
                && copy.get(TCWarpType.TEMPORARY) == 3
                && copy.getCounter() == 6;
        return check("sync_payload_preserves_all_warp_fields", passed,
                "payload=" + payload.permanent() + "/" + payload.normal() + "/" + payload.temporary() + "/" + payload.counter());
    }

    private static Check checkWarpResearchUnlock(ServerPlayer player) {
        TCPlayerWarpStore.clear(player);
        TCPlayerKnowledge knowledge = new TCPlayerKnowledge();
        knowledge.addResearch("FIRSTSTEPS");
        knowledge.setResearchStage("FIRSTSTEPS", 4);
        TCPlayerKnowledgeStore.set(player, knowledge, false);
        TCWarpManager.add(player, TCWarpType.NORMAL, 1, false);
        TCPlayerKnowledge after = TCPlayerKnowledgeStore.get(player);
        boolean passed = after.hasResearch("WARP");
        return check("non_temporary_warp_unlocks_legacy_warp_research_after_firststeps", passed,
                "warpKnown=" + passed);
    }

    private static Check checkClearSync(ServerPlayer player) {
        TCWarpManager.add(player, TCWarpType.PERMANENT, 2, false);
        TCWarpManager.add(player, TCWarpType.TEMPORARY, 3, false);
        TCWarpManager.clear(player);
        TCPlayerWarp stored = TCPlayerWarpStore.get(player);
        boolean passed = stored.totalWarp() == 0 && stored.getCounter() == 0;
        return check("manager_clear_resets_warp_and_counter", passed,
                "total=" + stored.totalWarp() + ", counter=" + stored.getCounter());
    }

    private static Check checkItemWarpRegistry() {
        int jarBrain = TCWarpItemRegistry.getWarp(new ItemStack(TCItems.JAR_BRAIN.get()));
        int zombieBrain = TCWarpItemRegistry.getWarp(new ItemStack(TCItems.BRAIN.get()));
        boolean passed = TCWarpItemRegistry.entries().size() == 1
                && jarBrain == 1
                && zombieBrain == 0;
        return check("item_warp_registry_preserves_legacy_jar_brain_entry", passed,
                "entries=" + TCWarpItemRegistry.entries().size() + ", jarBrain=" + jarBrain + ", zombieBrain=" + zombieBrain);
    }

    private static Check checkCraftedItemWarpAppliesStickyNormalWarp(ServerPlayer player) {
        TCPlayerWarpStore.clear(player);
        int awarded = TCWarpManager.applyCraftingWarp(player, new ItemStack(TCItems.JAR_BRAIN.get()), false);
        TCPlayerWarp stored = TCPlayerWarpStore.get(player);
        boolean passed = awarded == 1
                && stored.get(TCWarpType.NORMAL) == 1
                && stored.getCounter() == 1
                && stored.get(TCWarpType.PERMANENT) == 0
                && stored.get(TCWarpType.TEMPORARY) == 0;
        return check("crafted_item_warp_applies_legacy_sticky_normal_warp", passed,
                "awarded=" + awarded + ", normal=" + stored.get(TCWarpType.NORMAL) + ", counter=" + stored.getCounter());
    }

    private static Check checkCraftedItemWarpRespectsWussModeAndUnknownItems(ServerPlayer player) {
        TCPlayerWarpStore.clear(player);
        int wussAward = TCWarpManager.applyCraftingWarp(player, new ItemStack(TCItems.JAR_BRAIN.get()), true);
        int unknownAward = TCWarpManager.applyCraftingWarp(player, new ItemStack(Items.DIRT), false);
        TCPlayerWarp stored = TCPlayerWarpStore.get(player);
        boolean passed = wussAward == 0
                && unknownAward == 0
                && stored.totalWarp() == 0
                && stored.getCounter() == 0;
        return check("crafted_item_warp_respects_wuss_mode_and_unknown_items", passed,
                "wussAward=" + wussAward + ", unknownAward=" + unknownAward + ", total=" + stored.totalWarp());
    }

    private static Check check(String name, boolean passed, String notes) {
        return new Check(name, passed, notes);
    }

    public record Report(List<Check> checks) {
        public long passed() {
            return checks.stream().filter(Check::passed).count();
        }

        public long failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
