param(
    [Parameter(Mandatory = $true)]
    [string]$RepoRoot
)

$script = Join-Path $RepoRoot 'tools/audits/audit-smelter-variant-endpoint-boundary.ps1'
Write-Host '[tc-port] This audit was generated by audit_smelter_variant_endpoint_boundary.ps1.'
Write-Host '[tc-port] Re-run the checked-in top-level generator script from chat if this placeholder wrapper needs regeneration.'
