package thaumcraft.common.crafting.infusion;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import net.minecraft.core.BlockPos;
import thaumcraft.common.essentia.transport.TCEssentiaTubeMode;
import thaumcraft.common.essentia.transport.TCLegacyEssentiaTransportNode;
import thaumcraft.common.essentia.transport.blockentity.TCLegacyTubeBlockEntity;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.item.crafting.RecipeManager;
import net.minecraft.world.level.block.Blocks;
import thaumcraft.Thaumcraft;
import thaumcraft.common.blocks.crafting.TCInfusionMatrixBlock;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.registry.TCRecipes;
import thaumcraft.common.tiles.crafting.TCInfusionMatrixBlockEntity;
import thaumcraft.common.tiles.crafting.TCInfusionPedestalBlockEntity;
import thaumcraft.common.tiles.essentia.TCWardedJarBlockEntity;

public final class TCInfusionBehaviorAudit {
    private static final ResourceLocation CLOUD_RING = ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "cloudring");

    private TCInfusionBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Infusion Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter after server recipe reload.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("| Infusion recipes loaded | " + report.infusionRecipeCount() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This validates the current server-owned infusion input snapshot, recipe matcher and active-plan readiness boundary.");
        lines.add("- The audit also places a matrix and pedestals in a runtime server world to validate legacy-aligned pedestal discovery.");
        lines.add("- Legacy parity point: component matching uses Forge/NeoForge RecipeMatcher 1:1 semantics, so extra pedestal inputs must fail.");
        lines.add("- The audit-only mutation executor consumes validated inputs, while normal player interaction remains disabled.");
        lines.add("- Legacy-shaped source discovery scans aspect containers in the range-12 volume and drains nearest containers first; transient tube buffers are excluded.");
        lines.add("- The persisted cycle audit drains one essentia point per cycle, waits six cycles per component and completes only on the following cycle.");
        lines.add("- This does not yet implement instability events, source-beam payloads, particles, sounds or matrix animation.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        RecipeManager recipeManager = server.getRecipeManager();
        List<RecipeHolder<TCInfusionRecipe>> infusionRecipes = recipeManager.getAllRecipesFor(TCRecipes.INFUSION_TYPE.get());
        checks.add(new Check(
                "infusion_recipes_loaded",
                infusionRecipes.size() >= 30,
                "loaded=" + infusionRecipes.size()
        ));

        Optional<RecipeHolder<TCInfusionRecipe>> cloudRingHolder = infusionRecipes.stream()
                .filter(holder -> holder.id().equals(CLOUD_RING))
                .findFirst();
        Optional<TCInfusionRecipe> cloudRing = cloudRingHolder.map(RecipeHolder::value);
        checks.add(new Check(
                "cloudring_recipe_loaded",
                cloudRing.isPresent(),
                "recipe=" + CLOUD_RING
        ));

        if (cloudRing.isPresent()) {
            TCInfusionRecipe recipe = cloudRing.get();
            checks.add(new Check(
                    "cloudring_legacy_recipe_shape",
                    "CLOUDRING".equals(recipe.getResearch())
                            && recipe.instability() == 1
                            && recipe.components().size() == 2
                            && recipe.aspectCosts().size() == 1
                            && recipe.aspectCosts().getFirst().resolvedAspect() == Aspect.AIR
                            && recipe.aspectCosts().getFirst().amount() == 50
                            && recipe.result().is(TCItems.CLOUD_RING.get()),
                    "research=" + recipe.getResearch()
                            + ", instability=" + recipe.instability()
                            + ", components=" + recipe.components().size()
                            + ", aspects=" + recipe.aspectCosts().size()
            ));

            TCInfusionAssembly exactAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult exactResult = exactAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_happy_path_direct_validation",
                    exactResult.valid()
                            && exactResult.remainingAspects().visSize() == 0
                            && exactResult.requiredComponentCount() == 2
                            && exactResult.suppliedComponentCount() == 2,
                    "reason=" + exactResult.reason() + ", remaining=" + exactResult.remainingAspects().visSize()
            ));

            TCInfusionAssembly reversedAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(Items.FEATHER),
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get())
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            checks.add(new Check(
                    "cloudring_unordered_components_match",
                    reversedAssembly.validateAgainst(recipe).valid(),
                    "legacy RecipeMatcher accepts component order changes"
            ));

            TCInfusionAssembly extraComponentAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(Items.FEATHER),
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.STICK)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult extraResult = extraComponentAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_extra_component_fails_legacy_one_to_one_match",
                    !extraResult.valid() && "component_mismatch".equals(extraResult.reason()),
                    "reason=" + extraResult.reason()
            ));

            TCInfusionAssembly missingAspectAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 49)
            );
            TCInfusionValidationResult missingAspectResult = missingAspectAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_missing_aspect_fails_before_components",
                    !missingAspectResult.valid() && "missing_aspects".equals(missingAspectResult.reason()),
                    "reason=" + missingAspectResult.reason()
            ));

            TCInfusionAssembly wrongCatalystAssembly = TCInfusionAssembly.of(
                    new ItemStack(Items.IRON_INGOT),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult wrongCatalystResult = wrongCatalystAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_wrong_catalyst_fails",
                    !wrongCatalystResult.valid() && "catalyst_mismatch".equals(wrongCatalystResult.reason()),
                    "reason=" + wrongCatalystResult.reason()
            ));

            TCInfusionAssembly noPlayerAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            checks.add(new Check(
                    "researched_recipe_lookup_requires_player_context",
                    noPlayerAssembly.findMatchingRecipe(recipeManager, null).isEmpty(),
                    "legacy InfusionRecipe.matches checks player knowledge before recipe match"
            ));

            checks.add(new Check(
                    "player_facing_infusion_completion_disabled",
                    !TCInfusionMatrixBlock.isPlayerFacingCompletionEnabled(),
                    "matrix click remains validation/status only"
            ));
            cloudRingHolder.ifPresent(holder -> {
                addRuntimeMatrixChecks(server, holder, checks);
                addRuntimeMutationExecutorChecks(server, holder, checks);
                addContainerRemainderPolicyChecks(checks);
                addAspectSourceBoundaryChecks(checks);
                addAspectSourceMutationExecutorChecks(server, holder, checks);
                addAspectSourceResolverChecks(checks);
                addTransportAspectSourceChecks(checks);
                addRuntimeContainerAspectSourceChecks(server, holder, checks);
                addRuntimeLegacyCycleChecks(server, holder, checks);
            });
        }

        return new Report(List.copyOf(checks), infusionRecipes.size());
    }

    private static void addRuntimeMatrixChecks(MinecraftServer server, RecipeHolder<TCInfusionRecipe> cloudRing, ArrayList<Check> checks) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(0, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);
        BlockPos extraPos = matrixPos.offset(0, -2, 2);
        BlockPos outOfColumnPos = matrixPos.offset(0, -2, 3);

        clearTestArea(level, matrixPos);
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(outOfColumnPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);

        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity emptySameColumn = blockEntity(level, outOfColumnPos, TCInfusionPedestalBlockEntity.class);

        checks.add(new Check(
                "runtime_matrix_and_pedestal_block_entities_created",
                matrix != null && center != null && feather != null && crystal != null && emptySameColumn != null,
                "matrix=" + (matrix != null)
                        + ", center=" + (center != null)
                        + ", feather=" + (feather != null)
                        + ", crystal=" + (crystal != null)
        ));
        if (matrix == null || center == null || feather == null || crystal == null) {
            return;
        }

        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));

        TCInfusionMatrixBlockEntity.Snapshot snapshot = matrix.createSnapshot(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_detects_legacy_center_and_surrounding_pedestals",
                snapshot.hasCentralPedestal()
                        && snapshot.surroundingPedestalCount() == 3
                        && snapshot.componentCount() == 2,
                "surrounding=" + snapshot.surroundingPedestalCount() + ", components=" + snapshot.componentCount()
        ));

        TCInfusionValidationResult runtimeResult = matrix.validateAgainst(cloudRing, new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_snapshot_matches_cloudring_recipe",
                runtimeResult.valid()
                        && runtimeResult.requiredComponentCount() == 2
                        && runtimeResult.suppliedComponentCount() == 2,
                "reason=" + runtimeResult.reason() + ", recipe=" + runtimeResult.recipeId()
        ));

        TCInfusionStartResult startResult = matrix.startCraftingForValidation(
                cloudRing,
                new AspectList().add(Aspect.AIR, 50),
                "AuditPlayer"
        );
        Optional<TCInfusionCraftingPlan> activePlan = matrix.activePlan();
        checks.add(new Check(
                "runtime_matrix_start_plan_cloudring",
                startResult.started()
                        && matrix.isCrafting()
                        && activePlan.isPresent()
                        && CLOUD_RING.equals(activePlan.get().recipeId()),
                "started=" + startResult.started() + ", reason=" + startResult.reason()
        ));
        checks.add(new Check(
                "runtime_matrix_start_plan_records_legacy_fields",
                activePlan.isPresent()
                        && "CLOUDRING".equals(activePlan.get().research())
                        && activePlan.get().instability() == 1
                        && activePlan.get().catalyst().is(TCItems.BAUBLE_RING.get())
                        && activePlan.get().components().size() == 2
                        && activePlan.get().requiredAspects().getAmount(Aspect.AIR) == 50
                        && activePlan.get().result().is(TCItems.CLOUD_RING.get())
                        && "AuditPlayer".equals(activePlan.get().playerName()),
                activePlan.map(plan -> "research=" + plan.research()
                                + ", instability=" + plan.instability()
                                + ", components=" + plan.components().size()
                                + ", aspects=" + plan.requiredAspectAmount())
                        .orElse("no active plan")
        ));
        checks.add(new Check(
                "runtime_matrix_start_plan_records_component_pedestal_positions",
                activePlan.isPresent()
                        && activePlan.get().componentPedestalPositions().size() == 2
                        && activePlan.get().componentPedestalPositions().contains(featherPos)
                        && activePlan.get().componentPedestalPositions().contains(crystalPos),
                activePlan.map(plan -> "positions=" + plan.componentPedestalPositions()).orElse("no active plan")
        ));
        checks.add(new Check(
                "runtime_matrix_active_plan_persists_through_nbt",
                activePlan.map(plan -> TCInfusionCraftingPlan.load(plan.save(server.registryAccess()), server.registryAccess()))
                        .map(loaded -> CLOUD_RING.equals(loaded.recipeId())
                                && loaded.components().size() == 2
                                && loaded.requiredAspects().getAmount(Aspect.AIR) == 50
                                && loaded.result().is(TCItems.CLOUD_RING.get()))
                        .orElse(false),
                activePlan.map(plan -> "recipe=" + plan.recipeId()).orElse("no active plan")
        ));
        TCInfusionCompletionPlan completionPlan = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_cloudring",
                completionPlan.valid()
                        && "valid".equals(completionPlan.reason())
                        && completionPlan.componentCount() == 2
                        && completionPlan.requiredAspectAmount() == 50
                        && completionPlan.remainingAspects().visSize() == 0,
                "reason=" + completionPlan.reason()
                        + ", components=" + completionPlan.componentCount()
                        + ", missing=" + completionPlan.missingAspectAmount()
        ));
        TCInfusionCompletionPlan missingAspectCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 49));
        checks.add(new Check(
                "runtime_matrix_completion_plan_requires_all_aspects",
                !missingAspectCompletion.valid()
                        && "missing_aspects".equals(missingAspectCompletion.reason())
                        && missingAspectCompletion.missingAspects().getAmount(Aspect.AIR) == 1,
                "reason=" + missingAspectCompletion.reason()
                        + ", missingAer=" + missingAspectCompletion.missingAspects().getAmount(Aspect.AIR)
        ));

        center.setStoredForValidation(new ItemStack(Items.IRON_INGOT));
        TCInfusionCompletionPlan changedCatalystCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_rechecks_catalyst",
                !changedCatalystCompletion.valid() && "catalyst_changed".equals(changedCatalystCompletion.reason()),
                "reason=" + changedCatalystCompletion.reason()
        ));
        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));

        feather.setStoredForValidation(new ItemStack(Items.STICK));
        TCInfusionCompletionPlan changedComponentCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_rechecks_component_stack",
                !changedComponentCompletion.valid() && "component_changed".equals(changedComponentCompletion.reason()),
                "reason=" + changedComponentCompletion.reason()
        ));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));

        level.setBlock(featherPos, Blocks.AIR.defaultBlockState(), 3);
        TCInfusionCompletionPlan missingComponentPedestalCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_rechecks_component_pedestal",
                !missingComponentPedestalCompletion.valid()
                        && "missing_component_pedestal".equals(missingComponentPedestalCompletion.reason()),
                "reason=" + missingComponentPedestalCompletion.reason()
        ));
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        if (feather != null) {
            feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        }

        TCInfusionStartResult secondStart = matrix.startCraftingForValidation(
                cloudRing,
                new AspectList().add(Aspect.AIR, 50),
                "AuditPlayer"
        );
        checks.add(new Check(
                "runtime_matrix_rejects_second_start_while_active",
                !secondStart.started() && "already_crafting".equals(secondStart.reason()),
                "reason=" + secondStart.reason()
        ));
        matrix.abortCrafting();
        checks.add(new Check(
                "runtime_matrix_abort_clears_start_plan",
                !matrix.isCrafting() && matrix.activePlan().isEmpty(),
                "active=" + matrix.isCrafting()
        ));

        level.setBlock(extraPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionPedestalBlockEntity extra = blockEntity(level, extraPos, TCInfusionPedestalBlockEntity.class);
        if (extra != null) {
            extra.setStoredForValidation(new ItemStack(Items.STICK));
        }
        TCInfusionValidationResult extraResult = matrix.validateAgainst(cloudRing, new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_extra_filled_pedestal_fails_one_to_one_match",
                !extraResult.valid() && "component_mismatch".equals(extraResult.reason()),
                "reason=" + extraResult.reason() + ", components=" + matrix.createSnapshot(new AspectList()).componentCount()
        ));

        level.setBlock(centerPos, Blocks.AIR.defaultBlockState(), 3);
        TCInfusionValidationResult missingCenterResult = matrix.validateAgainst(cloudRing, new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_requires_central_pedestal_two_blocks_below",
                !missingCenterResult.valid() && "missing_central_pedestal".equals(missingCenterResult.reason()),
                "reason=" + missingCenterResult.reason()
        ));
    }

    private static void addAspectSourceResolverChecks(ArrayList<Check> checks) {
        checks.add(new Check(
                "aspect_source_resolver_null_inputs_fail_closed",
                TCInfusionAspectSourceResolver.findSource(null, null).isEmpty()
                        && TCInfusionAspectSourceResolver.NO_SUPPORTED_SOURCE_FOUND.equals(TCInfusionAspectSourceResolver.unavailableReason()),
                "reason=" + TCInfusionAspectSourceResolver.unavailableReason()
        ));
    }

    private static void addTransportAspectSourceChecks(ArrayList<Check> checks) {
        TCLegacyEssentiaTransportNode transport = new TCLegacyEssentiaTransportNode(TCEssentiaTubeMode.NORMAL, 128);
        transport.addEssentia(Aspect.AIR.getTag(), 64, Direction.NORTH, false);
        TCTransportInfusionAspectSource source = new TCTransportInfusionAspectSource(transport, Direction.NORTH);

        TCInfusionAspectSource.DrainResult exactDrain = source.drain(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "transport_aspect_source_drains_single_aspect_exactly",
                exactDrain.success()
                        && exactDrain.drainedAspects().getAmount(Aspect.AIR) == 50
                        && source.availableAspects().getAmount(Aspect.AIR) == 14
                        && transport.storage().amount(Aspect.AIR.getTag()) == 14,
                "reason=" + exactDrain.reason() + ", remainingAer=" + transport.storage().amount(Aspect.AIR.getTag())
        ));

        TCInfusionAspectSource.DrainResult insufficientDrain = source.drain(new AspectList().add(Aspect.AIR, 20));
        checks.add(new Check(
                "transport_aspect_source_rejects_insufficient_single_aspect_without_drain",
                !insufficientDrain.success()
                        && TCTransportInfusionAspectSource.MISSING_ASPECTS.equals(insufficientDrain.reason())
                        && transport.storage().amount(Aspect.AIR.getTag()) == 14,
                "reason=" + insufficientDrain.reason() + ", remainingAer=" + transport.storage().amount(Aspect.AIR.getTag())
        ));

        transport.addEssentia(Aspect.FIRE.getTag(), 10, Direction.NORTH, false);
        TCInfusionAspectSource.DrainResult multiDrain = source.drain(new AspectList().add(Aspect.AIR, 1).add(Aspect.FIRE, 1));
        checks.add(new Check(
                "transport_aspect_source_rejects_multi_aspect_plan_without_drain",
                !multiDrain.success()
                        && TCTransportInfusionAspectSource.SINGLE_ASPECT_ONLY.equals(multiDrain.reason())
                        && transport.storage().amount(Aspect.AIR.getTag()) == 14
                        && transport.storage().amount(Aspect.FIRE.getTag()) == 10,
                "reason=" + multiDrain.reason()
                        + ", aer=" + transport.storage().amount(Aspect.AIR.getTag())
                        + ", ignis=" + transport.storage().amount(Aspect.FIRE.getTag())
        ));
    }

    private static void addRuntimeContainerAspectSourceChecks(
            MinecraftServer server,
            RecipeHolder<TCInfusionRecipe> cloudRing,
            ArrayList<Check> checks
    ) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(72, level.getMinBuildHeight() + 12, 0);
        BlockPos tubePos = matrixPos.offset(1, 0, 0);
        BlockPos nearJarPos = matrixPos.offset(3, 0, 0);
        BlockPos farJarPos = matrixPos.offset(6, 0, 0);
        BlockPos outOfRangeJarPos = matrixPos.offset(TCInfusionAspectSourceResolver.LEGACY_SOURCE_RANGE + 1, 0, 0);

        level.setBlock(matrixPos, Blocks.AIR.defaultBlockState(), 3);
        level.setBlock(tubePos, Blocks.AIR.defaultBlockState(), 3);
        level.setBlock(nearJarPos, Blocks.AIR.defaultBlockState(), 3);
        level.setBlock(farJarPos, Blocks.AIR.defaultBlockState(), 3);
        level.setBlock(outOfRangeJarPos, Blocks.AIR.defaultBlockState(), 3);
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(tubePos, TCBlocks.TUBE.get().defaultBlockState(), 3);

        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCLegacyTubeBlockEntity tube = blockEntity(level, tubePos, TCLegacyTubeBlockEntity.class);
        if (tube != null) {
            tube.addEssentia(Aspect.AIR.getTag(), 1, Direction.WEST, false);
        }
        TCInfusionCraftingPlan plan = new TCInfusionCraftingPlan(
                cloudRing.id(),
                cloudRing.value().getResearch(),
                cloudRing.value().instability(),
                new ItemStack(TCItems.BAUBLE_RING.get()),
                List.of(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()), new ItemStack(Items.FEATHER)),
                List.of(matrixPos.offset(-2, -2, 0), matrixPos.offset(2, -2, 0)),
                new AspectList().add(Aspect.AIR, 50),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );
        checks.add(new Check(
                "runtime_source_resolver_excludes_adjacent_transport_buffer",
                matrix != null && TCInfusionAspectSourceResolver.findSource(matrix, plan).isEmpty(),
                "matrix=" + (matrix != null) + ", tube=" + (tube != null)
        ));
        if (matrix == null) {
            return;
        }

        level.setBlock(nearJarPos, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        level.setBlock(farJarPos, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        level.setBlock(outOfRangeJarPos, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        TCWardedJarBlockEntity nearJar = blockEntity(level, nearJarPos, TCWardedJarBlockEntity.class);
        TCWardedJarBlockEntity farJar = blockEntity(level, farJarPos, TCWardedJarBlockEntity.class);
        TCWardedJarBlockEntity outOfRangeJar = blockEntity(level, outOfRangeJarPos, TCWardedJarBlockEntity.class);
        checks.add(new Check(
                "runtime_warded_jar_source_block_entities_created",
                nearJar != null && farJar != null && outOfRangeJar != null,
                "near=" + (nearJar != null) + ", far=" + (farJar != null) + ", outside=" + (outOfRangeJar != null)
        ));
        if (nearJar == null || farJar == null || outOfRangeJar == null) {
            return;
        }

        nearJar.setStoredForValidation(Aspect.AIR, 30);
        farJar.setStoredForValidation(Aspect.AIR, 40);
        outOfRangeJar.setStoredForValidation(Aspect.AIR, TCWardedJarBlockEntity.CAPACITY);
        Optional<TCInfusionAspectSource> resolved = TCInfusionAspectSourceResolver.findSource(matrix, plan);
        TCInfusionAspectSource.DrainResult nearestFirst = resolved
                .map(source -> source.drain(new AspectList().add(Aspect.AIR, 50)))
                .orElseGet(() -> TCInfusionAspectSource.DrainResult.failed("not_resolved", new AspectList(), new AspectList()));
        checks.add(new Check(
                "runtime_warded_jar_source_drains_nearest_first_with_legacy_range",
                resolved.isPresent()
                        && nearestFirst.success()
                        && nearJar.storedAmount() == 0
                        && farJar.storedAmount() == 20
                        && outOfRangeJar.storedAmount() == TCWardedJarBlockEntity.CAPACITY,
                "reason=" + nearestFirst.reason()
                        + ", near=" + nearJar.storedAmount()
                        + ", far=" + farJar.storedAmount()
                        + ", outside=" + outOfRangeJar.storedAmount()
        ));

        nearJar.setStoredForValidation(Aspect.AIR, 30);
        nearJar.setBlockedForValidation(true);
        farJar.setStoredForValidation(Aspect.AIR, 60);
        TCInfusionAspectSource.DrainResult blockedNearest = resolved
                .map(source -> source.drain(new AspectList().add(Aspect.AIR, 50)))
                .orElseGet(() -> TCInfusionAspectSource.DrainResult.failed("not_resolved", new AspectList(), new AspectList()));
        checks.add(new Check(
                "runtime_warded_jar_source_skips_blocked_nearest_container",
                blockedNearest.success() && nearJar.storedAmount() == 30 && farJar.storedAmount() == 10,
                "reason=" + blockedNearest.reason() + ", near=" + nearJar.storedAmount() + ", far=" + farJar.storedAmount()
        ));

        nearJar.setBlockedForValidation(false);
        nearJar.setStoredForValidation(Aspect.AIR, 20);
        farJar.setStoredForValidation(Aspect.AIR, 20);
        TCInfusionAspectSource.DrainResult insufficient = resolved
                .map(source -> source.drain(new AspectList().add(Aspect.AIR, 50)))
                .orElseGet(() -> TCInfusionAspectSource.DrainResult.failed("not_resolved", new AspectList(), new AspectList()));
        checks.add(new Check(
                "runtime_warded_jar_source_insufficient_plan_is_atomic",
                !insufficient.success()
                        && TCContainerInfusionAspectSource.MISSING_ASPECTS.equals(insufficient.reason())
                        && insufficient.missingAspects().getAmount(Aspect.AIR) == 10
                        && nearJar.storedAmount() == 20
                        && farJar.storedAmount() == 20,
                "reason=" + insufficient.reason() + ", missing=" + insufficient.missingAspects().getAmount(Aspect.AIR)
        ));

        BlockPos pullBufferPos = outOfRangeJarPos.above();
        level.setBlock(pullBufferPos, TCBlocks.TUBE_BUFFER.get().defaultBlockState(), 3);
        TCLegacyTubeBlockEntity pullBuffer = blockEntity(level, pullBufferPos, TCLegacyTubeBlockEntity.class);
        outOfRangeJar.setStoredForValidation(null, 0);
        if (pullBuffer != null) {
            pullBuffer.addEssentia(Aspect.AIR.getTag(), 2, Direction.DOWN, false);
        }
        for (int tick = 0; tick < 4; tick++) {
            TCWardedJarBlockEntity.serverTick(level, outOfRangeJarPos, outOfRangeJar.getBlockState(), outOfRangeJar);
        }
        boolean unchangedBeforeFifthTick = outOfRangeJar.storedAmount() == 0;
        TCWardedJarBlockEntity.serverTick(level, outOfRangeJarPos, outOfRangeJar.getBlockState(), outOfRangeJar);
        checks.add(new Check(
                "runtime_warded_jar_pulls_one_essentia_every_five_server_ticks",
                pullBuffer != null
                        && unchangedBeforeFifthTick
                        && outOfRangeJar.storedAspect() == Aspect.AIR
                        && outOfRangeJar.storedAmount() == 1
                        && pullBuffer.transportNode().storage().amount(Aspect.AIR.getTag()) == 1,
                "buffer=" + (pullBuffer == null ? -1 : pullBuffer.transportNode().storage().amount(Aspect.AIR.getTag()))
                        + ", jar=" + outOfRangeJar.storedAmount()
        ));
    }

    private static void addRuntimeLegacyCycleChecks(
            MinecraftServer server,
            RecipeHolder<TCInfusionRecipe> cloudRing,
            ArrayList<Check> checks
    ) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(112, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);
        BlockPos jarPos = matrixPos.offset(4, 0, 0);

        for (BlockPos pos : List.of(matrixPos, centerPos, featherPos, crystalPos, jarPos)) {
            level.setBlock(pos, Blocks.AIR.defaultBlockState(), 3);
        }
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(jarPos, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);

        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        TCWardedJarBlockEntity jar = blockEntity(level, jarPos, TCWardedJarBlockEntity.class);
        checks.add(new Check(
                "runtime_legacy_cycle_setup_created",
                matrix != null && center != null && feather != null && crystal != null && jar != null,
                "matrix=" + (matrix != null) + ", jar=" + (jar != null)
        ));
        if (matrix == null || center == null || feather == null || crystal == null || jar == null) {
            return;
        }

        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        jar.setStoredForValidation(Aspect.AIR, 50);
        TCInfusionStartResult start = matrix.startCraftingForValidation(
                cloudRing,
                new AspectList().add(Aspect.AIR, 50),
                "AuditPlayer"
        );
        TCInfusionCycleState initialState = matrix.activeCycleState().orElse(null);
        checks.add(new Check(
                "runtime_legacy_cycle_initial_state_matches_plan",
                start.started()
                        && initialState != null
                        && initialState.remainingAspectAmount() == 50
                        && initialState.pendingComponentCount() == 2
                        && initialState.itemCountdown() == 0
                        && initialState.cycleDelay() == TCInfusionCycleState.BASE_CYCLE_DELAY,
                "started=" + start.started() + ", aspects=" + (initialState == null ? -1 : initialState.remainingAspectAmount())
        ));
        if (initialState == null) {
            return;
        }

        CompoundTag savedCycle = initialState.save(server.registryAccess());
        TCInfusionCycleState loadedCycle = TCInfusionCycleState.load(savedCycle, server.registryAccess());
        checks.add(new Check(
                "runtime_legacy_cycle_state_nbt_round_trip",
                loadedCycle != null
                        && loadedCycle.remainingAspectAmount() == 50
                        && loadedCycle.pendingComponentCount() == 2
                        && loadedCycle.cycleDelay() == TCInfusionCycleState.BASE_CYCLE_DELAY,
                "loaded=" + (loadedCycle != null)
        ));

        for (int tick = 0; tick < TCInfusionCycleState.BASE_CYCLE_DELAY - 1; tick++) {
            TCInfusionMatrixBlockEntity.serverTick(level, matrixPos, matrix.getBlockState(), matrix);
        }
        boolean noEarlyDrain = jar.storedAmount() == 50 && initialState.remainingAspectAmount() == 50;
        TCInfusionMatrixBlockEntity.serverTick(level, matrixPos, matrix.getBlockState(), matrix);
        checks.add(new Check(
                "runtime_legacy_cycle_uses_five_tick_default_cadence",
                noEarlyDrain
                        && jar.storedAmount() == 49
                        && initialState.remainingAspectAmount() == 49
                        && TCInfusionCycleResult.Status.ASPECT_DRAINED.name().equals(matrix.lastCycleStatus()),
                "jar=" + jar.storedAmount() + ", remaining=" + initialState.remainingAspectAmount()
        ));
        checks.add(new Check(
                "runtime_legacy_cycle_caches_nearest_source_positions",
                matrix.cachedInfusionSourcePositions().equals(List.of(jarPos))
                        && jarPos.equals(matrix.lastCycleSourcePos()),
                "cached=" + matrix.cachedInfusionSourcePositions()
        ));

        for (int cycle = 0; cycle < 49; cycle++) {
            matrix.advanceCycleForValidation();
        }
        checks.add(new Check(
                "runtime_legacy_cycle_drains_exactly_one_aspect_per_cycle",
                jar.storedAmount() == 0
                        && initialState.remainingAspectAmount() == 0
                        && initialState.completedCycles() == 50
                        && !feather.getStoredStack().isEmpty()
                        && !crystal.getStoredStack().isEmpty(),
                "jar=" + jar.storedAmount() + ", cycles=" + initialState.completedCycles()
        ));

        TCInfusionCycleResult firstTarget = matrix.advanceCycleForValidation();
        for (int cycle = 0; cycle < 4; cycle++) {
            matrix.advanceCycleForValidation();
        }
        boolean firstComponentHeldForFiveCountdownSteps =
                !feather.getStoredStack().isEmpty()
                        && !crystal.getStoredStack().isEmpty()
                        && initialState.itemCountdown() == 1;
        TCInfusionCycleResult firstConsumed = matrix.advanceCycleForValidation();
        checks.add(new Check(
                "runtime_legacy_cycle_waits_six_cycles_before_first_component_consumption",
                firstTarget.status() == TCInfusionCycleResult.Status.COMPONENT_TARGETED
                        && firstComponentHeldForFiveCountdownSteps
                        && firstConsumed.status() == TCInfusionCycleResult.Status.COMPONENT_CONSUMED
                        && initialState.pendingComponentCount() == 1,
                "target=" + firstTarget.status() + ", consumed=" + firstConsumed.status()
        ));

        TCInfusionCycleResult secondTarget = matrix.advanceCycleForValidation();
        for (int cycle = 0; cycle < 4; cycle++) {
            matrix.advanceCycleForValidation();
        }
        TCInfusionCycleResult secondConsumed = matrix.advanceCycleForValidation();
        checks.add(new Check(
                "runtime_legacy_cycle_consumes_second_component_with_same_timing",
                secondTarget.status() == TCInfusionCycleResult.Status.COMPONENT_TARGETED
                        && secondConsumed.status() == TCInfusionCycleResult.Status.COMPONENT_CONSUMED
                        && initialState.pendingComponentCount() == 0
                        && feather.getStoredStack().isEmpty()
                        && crystal.getStoredStack().isEmpty(),
                "target=" + secondTarget.status() + ", consumed=" + secondConsumed.status()
        ));

        TCInfusionCycleResult completed = matrix.advanceCycleForValidation();
        checks.add(new Check(
                "runtime_legacy_cycle_completes_cloudring_on_following_cycle",
                completed.status() == TCInfusionCycleResult.Status.COMPLETED
                        && !matrix.isCrafting()
                        && center.getStoredStack().is(TCItems.CLOUD_RING.get())
                        && initialState.completedCycles() == 63,
                "status=" + completed.status() + ", cycles=" + initialState.completedCycles()
        ));
        ItemStack damagedCatalyst = new ItemStack(Items.IRON_PICKAXE);
        damagedCatalyst.setDamageValue(50);
        ItemStack damageCarriedResult = TCInfusionLegacyCycleExecutor.resultWithLegacyDamageRatio(
                damagedCatalyst,
                new ItemStack(Items.DIAMOND_PICKAXE)
        );
        int expectedResultDamage = (int) (
                damageCarriedResult.getMaxDamage()
                        * (damagedCatalyst.getDamageValue() / (float) damagedCatalyst.getMaxDamage())
        );
        checks.add(new Check(
                "runtime_legacy_cycle_preserves_damaged_catalyst_ratio",
                damageCarriedResult.getDamageValue() == expectedResultDamage,
                "damage=" + damageCarriedResult.getDamageValue() + ", expected=" + expectedResultDamage
        ));

        addRuntimeLegacyCycleRecoveryChecks(server, cloudRing, checks);
    }

    private static void addRuntimeLegacyCycleRecoveryChecks(
            MinecraftServer server,
            RecipeHolder<TCInfusionRecipe> cloudRing,
            ArrayList<Check> checks
    ) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(144, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);
        BlockPos jarPos = matrixPos.offset(4, 0, 0);
        for (BlockPos pos : List.of(matrixPos, centerPos, featherPos, crystalPos, jarPos)) {
            level.setBlock(pos, Blocks.AIR.defaultBlockState(), 3);
        }
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(jarPos, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        TCWardedJarBlockEntity jar = blockEntity(level, jarPos, TCWardedJarBlockEntity.class);
        if (matrix == null || center == null || feather == null || crystal == null || jar == null) {
            checks.add(new Check("runtime_legacy_cycle_recovery_setup_created", false, "missing block entity"));
            return;
        }
        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        matrix.startCraftingForValidation(cloudRing, new AspectList().add(Aspect.AIR, 50), "AuditPlayer");

        TCInfusionCycleResult waiting = matrix.advanceCycleForValidation();
        TCInfusionCycleState state = matrix.activeCycleState().orElse(null);
        checks.add(new Check(
                "runtime_legacy_cycle_waits_without_mutation_when_source_is_empty",
                waiting.status() == TCInfusionCycleResult.Status.WAITING_FOR_ASPECT
                        && state != null
                        && state.remainingAspectAmount() == 50
                        && matrix.cachedInfusionSourcePositions().isEmpty()
                        && matrix.sourceRefreshCooldownTicks() == TCInfusionMatrixBlockEntity.LEGACY_SOURCE_RESCAN_DELAY_TICKS,
                "status=" + waiting.status() + ", cooldown=" + matrix.sourceRefreshCooldownTicks()
        ));
        jar.setStoredForValidation(Aspect.AIR, 1);
        for (int tick = 0; tick < TCInfusionMatrixBlockEntity.LEGACY_SOURCE_RESCAN_DELAY_TICKS - 1; tick++) {
            TCInfusionMatrixBlockEntity.serverTick(level, matrixPos, matrix.getBlockState(), matrix);
        }
        boolean didNotRescanEarly = jar.storedAmount() == 1 && state != null && state.remainingAspectAmount() == 50;
        TCInfusionMatrixBlockEntity.serverTick(level, matrixPos, matrix.getBlockState(), matrix);
        checks.add(new Check(
                "runtime_legacy_cycle_rescans_after_legacy_ten_second_delay",
                didNotRescanEarly
                        && TCInfusionCycleResult.Status.ASPECT_DRAINED.name().equals(matrix.lastCycleStatus())
                        && state != null
                        && state.remainingAspectAmount() == 49
                        && jar.storedAmount() == 0,
                "status=" + matrix.lastCycleStatus() + ", remaining=" + (state == null ? -1 : state.remainingAspectAmount())
        ));

        center.setStoredForValidation(new ItemStack(Items.IRON_INGOT));
        TCInfusionCycleResult aborted = matrix.advanceCycleForValidation();
        checks.add(new Check(
                "runtime_legacy_cycle_catalyst_change_aborts_without_component_loss",
                aborted.status() == TCInfusionCycleResult.Status.ABORTED
                        && !matrix.isCrafting()
                        && feather.getStoredStack().is(Items.FEATHER)
                        && crystal.getStoredStack().is(TCItems.CRYSTAL_ESSENCE_AER.get()),
                "status=" + aborted.status() + ", reason=" + aborted.reason()
        ));
    }

    private static void addAspectSourceMutationExecutorChecks(MinecraftServer server, RecipeHolder<TCInfusionRecipe> cloudRing, ArrayList<Check> checks) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(36, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);

        clearTestArea(level, matrixPos);
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        if (matrix == null || center == null || feather == null || crystal == null) {
            checks.add(new Check("runtime_aspect_source_executor_setup_created", false, "missing block entity"));
            return;
        }
        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        matrix.startCraftingForValidation(cloudRing, new AspectList().add(Aspect.AIR, 50), "AuditPlayer");
        TCInfusionCompletionPlan completionPlan = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionAspectSource exactSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 50));
        TCInfusionMutationExecutor.Result result = TCInfusionMutationExecutor.executeWithAspectSource(matrix, completionPlan, exactSource);
        checks.add(new Check(
                "runtime_mutation_executor_drains_aspect_source_before_item_completion",
                result.success()
                        && exactSource.availableAspects().visSize() == 0
                        && center.getStoredStack().is(TCItems.CLOUD_RING.get())
                        && feather.getStoredStack().isEmpty()
                        && crystal.getStoredStack().isEmpty()
                        && !matrix.isCrafting(),
                "reason=" + result.reason() + ", sourceRemaining=" + exactSource.availableAspects().visSize()
        ));

        BlockPos failMatrixPos = new BlockPos(48, level.getMinBuildHeight() + 12, 0);
        BlockPos failCenterPos = failMatrixPos.below(2);
        BlockPos failFeatherPos = failMatrixPos.offset(2, -2, 0);
        BlockPos failCrystalPos = failMatrixPos.offset(-2, -2, 0);
        clearTestArea(level, failMatrixPos);
        level.setBlock(failMatrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(failCenterPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failFeatherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failCrystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionMatrixBlockEntity failMatrix = blockEntity(level, failMatrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity failCenter = blockEntity(level, failCenterPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failFeather = blockEntity(level, failFeatherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failCrystal = blockEntity(level, failCrystalPos, TCInfusionPedestalBlockEntity.class);
        if (failMatrix == null || failCenter == null || failFeather == null || failCrystal == null) {
            checks.add(new Check("runtime_aspect_source_executor_missing_source_setup_created", false, "missing block entity"));
            return;
        }
        failCenter.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        failFeather.setStoredForValidation(new ItemStack(Items.FEATHER));
        failCrystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        failMatrix.startCraftingForValidation(cloudRing, new AspectList().add(Aspect.AIR, 50), "AuditPlayer");
        TCInfusionCompletionPlan failCompletionPlan = failMatrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionAspectSource insufficientSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 49));
        TCInfusionMutationExecutor.Result failedResult = TCInfusionMutationExecutor.executeWithAspectSource(failMatrix, failCompletionPlan, insufficientSource);
        checks.add(new Check(
                "runtime_mutation_executor_rejects_insufficient_aspect_source_without_item_mutation",
                !failedResult.success()
                        && "aspect_source_missing_aspects".equals(failedResult.reason())
                        && insufficientSource.availableAspects().getAmount(Aspect.AIR) == 49
                        && failCenter.getStoredStack().is(TCItems.BAUBLE_RING.get())
                        && failFeather.getStoredStack().is(Items.FEATHER)
                        && failCrystal.getStoredStack().is(TCItems.CRYSTAL_ESSENCE_AER.get())
                        && failMatrix.isCrafting(),
                "reason=" + failedResult.reason() + ", sourceAir=" + insufficientSource.availableAspects().getAmount(Aspect.AIR)
        ));
    }
    private static void addAspectSourceBoundaryChecks(ArrayList<Check> checks) {
        TCInfusionCraftingPlan cloudRingPlan = new TCInfusionCraftingPlan(
                CLOUD_RING,
                "CLOUDRING",
                1,
                new ItemStack(TCItems.BAUBLE_RING.get()),
                List.of(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()), new ItemStack(Items.FEATHER)),
                List.of(BlockPos.ZERO, BlockPos.ZERO.offset(1, 0, 0)),
                new AspectList().add(Aspect.AIR, 50),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );

        TCInfusionAspectSource exactSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 50));
        TCInfusionAspectSource.DrainResult exactDrain = exactSource.drain(cloudRingPlan);
        checks.add(new Check(
                "infusion_aspect_source_drains_exact_required_aspects",
                exactDrain.success()
                        && "drained".equals(exactDrain.reason())
                        && exactDrain.drainedAspects().getAmount(Aspect.AIR) == 50
                        && exactDrain.remainingAspects().visSize() == 0
                        && exactSource.availableAspects().visSize() == 0,
                "reason=" + exactDrain.reason() + ", remaining=" + exactDrain.remainingAspects().visSize()
        ));

        TCInfusionAspectSource insufficientSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 49));
        TCInfusionAspectSource.DrainResult missingDrain = insufficientSource.drain(cloudRingPlan);
        checks.add(new Check(
                "infusion_aspect_source_rejects_insufficient_aspects_without_drain",
                !missingDrain.success()
                        && "missing_aspects".equals(missingDrain.reason())
                        && missingDrain.missingAspects().getAmount(Aspect.AIR) == 1
                        && insufficientSource.availableAspects().getAmount(Aspect.AIR) == 49,
                "reason=" + missingDrain.reason() + ", missingAir=" + missingDrain.missingAspects().getAmount(Aspect.AIR)
        ));
    }
    private static void addContainerRemainderPolicyChecks(ArrayList<Check> checks) {
        TCInfusionCraftingPlan safePlan = new TCInfusionCraftingPlan(
                CLOUD_RING,
                "CLOUDRING",
                1,
                new ItemStack(TCItems.BAUBLE_RING.get()),
                List.of(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()), new ItemStack(Items.FEATHER)),
                List.of(BlockPos.ZERO, BlockPos.ZERO.offset(1, 0, 0)),
                new AspectList().add(Aspect.AIR, 50),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );
        TCInfusionCraftingPlan waterComponentPlan = new TCInfusionCraftingPlan(
                ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "audit_component_remainder_policy"),
                "AUDIT",
                0,
                new ItemStack(TCItems.BAUBLE_RING.get()),
                List.of(new ItemStack(Items.WATER_BUCKET)),
                List.of(BlockPos.ZERO),
                new AspectList(),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );
        TCInfusionCraftingPlan waterCatalystPlan = new TCInfusionCraftingPlan(
                ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "audit_catalyst_remainder_policy"),
                "AUDIT",
                0,
                new ItemStack(Items.WATER_BUCKET),
                List.of(),
                List.of(),
                new AspectList(),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );
        checks.add(new Check(
                "infusion_container_policy_allows_current_cloudring_inputs",
                !TCInfusionContainerRemainderPolicy.requiresExplicitPolicy(safePlan),
                "cloudring has no blocked catalyst remainder"
        ));
        checks.add(new Check(
                "infusion_container_policy_preserves_water_bucket_component_remainder",
                !TCInfusionContainerRemainderPolicy.requiresExplicitPolicy(waterComponentPlan)
                        && TCInfusionContainerRemainderPolicy.remainderForComponent(new ItemStack(Items.WATER_BUCKET)).is(Items.BUCKET),
                "water bucket component returns bucket on the same pedestal"
        ));
        checks.add(new Check(
                "infusion_container_policy_replaces_container_catalyst_without_remainder",
                !TCInfusionContainerRemainderPolicy.requiresExplicitPolicy(waterCatalystPlan)
                        && TCInfusionContainerRemainderPolicy.firstBlockingInput(waterCatalystPlan).isEmpty(),
                "legacy completion replaces the center catalyst with the result"
        ));
    }
    private static void addRuntimeMutationExecutorChecks(MinecraftServer server, RecipeHolder<TCInfusionRecipe> cloudRing, ArrayList<Check> checks) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(12, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);

        clearTestArea(level, matrixPos);
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);

        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        checks.add(new Check(
                "runtime_mutation_executor_setup_created",
                matrix != null && center != null && feather != null && crystal != null,
                "matrix=" + (matrix != null) + ", center=" + (center != null)
        ));
        if (matrix == null || center == null || feather == null || crystal == null) {
            return;
        }

        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        TCInfusionStartResult startResult = matrix.startCraftingForValidation(
                cloudRing,
                new AspectList().add(Aspect.AIR, 50),
                "AuditPlayer"
        );
        TCInfusionCompletionPlan completionPlan = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionMutationExecutor.Result result = TCInfusionMutationExecutor.execute(matrix, completionPlan);
        checks.add(new Check(
                "runtime_mutation_executor_executes_valid_plan",
                startResult.started()
                        && result.success()
                        && "executed".equals(result.reason())
                        && result.consumedComponents() == 2
                        && result.result().is(TCItems.CLOUD_RING.get()),
                "started=" + startResult.started() + ", reason=" + result.reason()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_places_result_on_center",
                center.getStoredStack().is(TCItems.CLOUD_RING.get()),
                "center=" + center.getStoredStack().getItem()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_consumes_component_pedestals",
                feather.getStoredStack().isEmpty() && crystal.getStoredStack().isEmpty(),
                "featherEmpty=" + feather.getStoredStack().isEmpty() + ", crystalEmpty=" + crystal.getStoredStack().isEmpty()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_clears_active_plan",
                !matrix.isCrafting() && matrix.activePlan().isEmpty(),
                "active=" + matrix.isCrafting()
        ));

        BlockPos failMatrixPos = new BlockPos(24, level.getMinBuildHeight() + 12, 0);
        BlockPos failCenterPos = failMatrixPos.below(2);
        BlockPos failFeatherPos = failMatrixPos.offset(2, -2, 0);
        BlockPos failCrystalPos = failMatrixPos.offset(-2, -2, 0);
        clearTestArea(level, failMatrixPos);
        level.setBlock(failMatrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(failCenterPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failFeatherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failCrystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionMatrixBlockEntity failMatrix = blockEntity(level, failMatrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity failCenter = blockEntity(level, failCenterPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failFeather = blockEntity(level, failFeatherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failCrystal = blockEntity(level, failCrystalPos, TCInfusionPedestalBlockEntity.class);
        if (failMatrix == null || failCenter == null || failFeather == null || failCrystal == null) {
            checks.add(new Check("runtime_mutation_executor_invalid_plan_setup_created", false, "missing block entity"));
            return;
        }
        failCenter.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        failFeather.setStoredForValidation(new ItemStack(Items.FEATHER));
        failCrystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        failMatrix.startCraftingForValidation(cloudRing, new AspectList().add(Aspect.AIR, 50), "AuditPlayer");
        failFeather.setStoredForValidation(new ItemStack(Items.STICK));
        TCInfusionCompletionPlan invalidCompletion = failMatrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionMutationExecutor.Result failedExecution = TCInfusionMutationExecutor.execute(failMatrix, invalidCompletion);
        checks.add(new Check(
                "runtime_mutation_executor_rejects_invalid_completion_plan",
                !failedExecution.success() && "invalid_completion_plan".equals(failedExecution.reason()),
                "reason=" + failedExecution.reason()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_invalid_plan_noops_world_state",
                failMatrix.isCrafting()
                        && failCenter.getStoredStack().is(TCItems.BAUBLE_RING.get())
                        && failFeather.getStoredStack().is(Items.STICK)
                        && failCrystal.getStoredStack().is(TCItems.CRYSTAL_ESSENCE_AER.get()),
                "active=" + failMatrix.isCrafting()
        ));
    }
    private static void clearTestArea(ServerLevel level, BlockPos matrixPos) {
        for (int dx = -3; dx <= 3; dx++) {
            for (int dy = -3; dy <= 1; dy++) {
                for (int dz = -3; dz <= 3; dz++) {
                    level.setBlock(matrixPos.offset(dx, dy, dz), Blocks.AIR.defaultBlockState(), 3);
                }
            }
        }
    }

    private static <T> T blockEntity(ServerLevel level, BlockPos pos, Class<T> type) {
        Object blockEntity = level.getBlockEntity(pos);
        return type.isInstance(blockEntity) ? type.cast(blockEntity) : null;
    }

    public record Report(List<Check> checks, int infusionRecipeCount) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}

