package thaumcraft.common.crafting.infusion;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.item.crafting.RecipeManager;
import thaumcraft.Thaumcraft;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.registry.TCRecipes;

public final class TCInfusionBehaviorAudit {
    private static final ResourceLocation CLOUD_RING = ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "cloudring");

    private TCInfusionBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Infusion Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter after server recipe reload.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("| Infusion recipes loaded | " + report.infusionRecipeCount() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This validates the current server-owned infusion input snapshot and recipe matcher boundary.");
        lines.add("- Legacy parity point: component matching uses Forge/NeoForge RecipeMatcher 1:1 semantics, so extra pedestal inputs must fail.");
        lines.add("- This does not implement item consumption, pedestal discovery, instability events, essentia transport, particles, beams or matrix animation.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        RecipeManager recipeManager = server.getRecipeManager();
        List<RecipeHolder<TCInfusionRecipe>> infusionRecipes = recipeManager.getAllRecipesFor(TCRecipes.INFUSION_TYPE.get());
        checks.add(new Check(
                "infusion_recipes_loaded",
                infusionRecipes.size() >= 30,
                "loaded=" + infusionRecipes.size()
        ));

        Optional<TCInfusionRecipe> cloudRing = recipeManager.byKey(CLOUD_RING)
                .map(RecipeHolder::value)
                .filter(TCInfusionRecipe.class::isInstance)
                .map(TCInfusionRecipe.class::cast);
        checks.add(new Check(
                "cloudring_recipe_loaded",
                cloudRing.isPresent(),
                "recipe=" + CLOUD_RING
        ));

        if (cloudRing.isPresent()) {
            TCInfusionRecipe recipe = cloudRing.get();
            checks.add(new Check(
                    "cloudring_legacy_recipe_shape",
                    "CLOUDRING".equals(recipe.getResearch())
                            && recipe.instability() == 1
                            && recipe.components().size() == 2
                            && recipe.aspectCosts().size() == 1
                            && recipe.aspectCosts().getFirst().resolvedAspect() == Aspect.AIR
                            && recipe.aspectCosts().getFirst().amount() == 50
                            && recipe.result().is(TCItems.CLOUD_RING.get()),
                    "research=" + recipe.getResearch()
                            + ", instability=" + recipe.instability()
                            + ", components=" + recipe.components().size()
                            + ", aspects=" + recipe.aspectCosts().size()
            ));

            TCInfusionAssembly exactAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult exactResult = exactAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_happy_path_direct_validation",
                    exactResult.valid()
                            && exactResult.remainingAspects().visSize() == 0
                            && exactResult.requiredComponentCount() == 2
                            && exactResult.suppliedComponentCount() == 2,
                    "reason=" + exactResult.reason() + ", remaining=" + exactResult.remainingAspects().visSize()
            ));

            TCInfusionAssembly reversedAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(Items.FEATHER),
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get())
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            checks.add(new Check(
                    "cloudring_unordered_components_match",
                    reversedAssembly.validateAgainst(recipe).valid(),
                    "legacy RecipeMatcher accepts component order changes"
            ));

            TCInfusionAssembly extraComponentAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(Items.FEATHER),
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.STICK)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult extraResult = extraComponentAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_extra_component_fails_legacy_one_to_one_match",
                    !extraResult.valid() && "component_mismatch".equals(extraResult.reason()),
                    "reason=" + extraResult.reason()
            ));

            TCInfusionAssembly missingAspectAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 49)
            );
            TCInfusionValidationResult missingAspectResult = missingAspectAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_missing_aspect_fails_before_components",
                    !missingAspectResult.valid() && "missing_aspects".equals(missingAspectResult.reason()),
                    "reason=" + missingAspectResult.reason()
            ));

            TCInfusionAssembly wrongCatalystAssembly = TCInfusionAssembly.of(
                    new ItemStack(Items.IRON_INGOT),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult wrongCatalystResult = wrongCatalystAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_wrong_catalyst_fails",
                    !wrongCatalystResult.valid() && "catalyst_mismatch".equals(wrongCatalystResult.reason()),
                    "reason=" + wrongCatalystResult.reason()
            ));

            TCInfusionAssembly noPlayerAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            checks.add(new Check(
                    "researched_recipe_lookup_requires_player_context",
                    noPlayerAssembly.findMatchingRecipe(recipeManager, null).isEmpty(),
                    "legacy InfusionRecipe.matches checks player knowledge before recipe match"
            ));
        }

        return new Report(List.copyOf(checks), infusionRecipes.size());
    }

    public record Report(List<Check> checks, int infusionRecipeCount) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
