package thaumcraft.common.crafting.infusion;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.item.crafting.RecipeManager;
import net.minecraft.world.level.block.Blocks;
import thaumcraft.Thaumcraft;
import thaumcraft.common.blocks.crafting.TCInfusionMatrixBlock;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.registry.TCRecipes;
import thaumcraft.common.tiles.crafting.TCInfusionMatrixBlockEntity;
import thaumcraft.common.tiles.crafting.TCInfusionPedestalBlockEntity;

public final class TCInfusionBehaviorAudit {
    private static final ResourceLocation CLOUD_RING = ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "cloudring");

    private TCInfusionBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Infusion Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter after server recipe reload.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("| Infusion recipes loaded | " + report.infusionRecipeCount() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This validates the current server-owned infusion input snapshot, recipe matcher and active-plan readiness boundary.");
        lines.add("- The audit also places a matrix and pedestals in a runtime server world to validate legacy-aligned pedestal discovery.");
        lines.add("- Legacy parity point: component matching uses Forge/NeoForge RecipeMatcher 1:1 semantics, so extra pedestal inputs must fail.");
        lines.add("- The active completion plan is still read-only: it checks current catalyst, planned component pedestals and aspect availability before any future mutation.");
        lines.add("- This does not implement item consumption, instability events, essentia transport, particles, beams or matrix animation.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        RecipeManager recipeManager = server.getRecipeManager();
        List<RecipeHolder<TCInfusionRecipe>> infusionRecipes = recipeManager.getAllRecipesFor(TCRecipes.INFUSION_TYPE.get());
        checks.add(new Check(
                "infusion_recipes_loaded",
                infusionRecipes.size() >= 30,
                "loaded=" + infusionRecipes.size()
        ));

        Optional<RecipeHolder<TCInfusionRecipe>> cloudRingHolder = infusionRecipes.stream()
                .filter(holder -> holder.id().equals(CLOUD_RING))
                .findFirst();
        Optional<TCInfusionRecipe> cloudRing = cloudRingHolder.map(RecipeHolder::value);
        checks.add(new Check(
                "cloudring_recipe_loaded",
                cloudRing.isPresent(),
                "recipe=" + CLOUD_RING
        ));

        if (cloudRing.isPresent()) {
            TCInfusionRecipe recipe = cloudRing.get();
            checks.add(new Check(
                    "cloudring_legacy_recipe_shape",
                    "CLOUDRING".equals(recipe.getResearch())
                            && recipe.instability() == 1
                            && recipe.components().size() == 2
                            && recipe.aspectCosts().size() == 1
                            && recipe.aspectCosts().getFirst().resolvedAspect() == Aspect.AIR
                            && recipe.aspectCosts().getFirst().amount() == 50
                            && recipe.result().is(TCItems.CLOUD_RING.get()),
                    "research=" + recipe.getResearch()
                            + ", instability=" + recipe.instability()
                            + ", components=" + recipe.components().size()
                            + ", aspects=" + recipe.aspectCosts().size()
            ));

            TCInfusionAssembly exactAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult exactResult = exactAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_happy_path_direct_validation",
                    exactResult.valid()
                            && exactResult.remainingAspects().visSize() == 0
                            && exactResult.requiredComponentCount() == 2
                            && exactResult.suppliedComponentCount() == 2,
                    "reason=" + exactResult.reason() + ", remaining=" + exactResult.remainingAspects().visSize()
            ));

            TCInfusionAssembly reversedAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(Items.FEATHER),
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get())
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            checks.add(new Check(
                    "cloudring_unordered_components_match",
                    reversedAssembly.validateAgainst(recipe).valid(),
                    "legacy RecipeMatcher accepts component order changes"
            ));

            TCInfusionAssembly extraComponentAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(Items.FEATHER),
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.STICK)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult extraResult = extraComponentAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_extra_component_fails_legacy_one_to_one_match",
                    !extraResult.valid() && "component_mismatch".equals(extraResult.reason()),
                    "reason=" + extraResult.reason()
            ));

            TCInfusionAssembly missingAspectAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 49)
            );
            TCInfusionValidationResult missingAspectResult = missingAspectAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_missing_aspect_fails_before_components",
                    !missingAspectResult.valid() && "missing_aspects".equals(missingAspectResult.reason()),
                    "reason=" + missingAspectResult.reason()
            ));

            TCInfusionAssembly wrongCatalystAssembly = TCInfusionAssembly.of(
                    new ItemStack(Items.IRON_INGOT),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            TCInfusionValidationResult wrongCatalystResult = wrongCatalystAssembly.validateAgainst(recipe);
            checks.add(new Check(
                    "cloudring_wrong_catalyst_fails",
                    !wrongCatalystResult.valid() && "catalyst_mismatch".equals(wrongCatalystResult.reason()),
                    "reason=" + wrongCatalystResult.reason()
            ));

            TCInfusionAssembly noPlayerAssembly = TCInfusionAssembly.of(
                    new ItemStack(TCItems.BAUBLE_RING.get()),
                    List.of(
                            new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()),
                            new ItemStack(Items.FEATHER)
                    ),
                    new AspectList().add(Aspect.AIR, 50)
            );
            checks.add(new Check(
                    "researched_recipe_lookup_requires_player_context",
                    noPlayerAssembly.findMatchingRecipe(recipeManager, null).isEmpty(),
                    "legacy InfusionRecipe.matches checks player knowledge before recipe match"
            ));

            checks.add(new Check(
                    "player_facing_infusion_completion_disabled",
                    !TCInfusionMatrixBlock.isPlayerFacingCompletionEnabled(),
                    "matrix click remains validation/status only"
            ));
            cloudRingHolder.ifPresent(holder -> {
                addRuntimeMatrixChecks(server, holder, checks);
                addRuntimeMutationExecutorChecks(server, holder, checks);
                addContainerRemainderPolicyChecks(checks);
                addAspectSourceBoundaryChecks(checks);
                addAspectSourceMutationExecutorChecks(server, holder, checks);
            });
        }

        return new Report(List.copyOf(checks), infusionRecipes.size());
    }

    private static void addRuntimeMatrixChecks(MinecraftServer server, RecipeHolder<TCInfusionRecipe> cloudRing, ArrayList<Check> checks) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(0, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);
        BlockPos extraPos = matrixPos.offset(0, -2, 2);
        BlockPos outOfColumnPos = matrixPos.offset(0, -2, 3);

        clearTestArea(level, matrixPos);
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(outOfColumnPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);

        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity emptySameColumn = blockEntity(level, outOfColumnPos, TCInfusionPedestalBlockEntity.class);

        checks.add(new Check(
                "runtime_matrix_and_pedestal_block_entities_created",
                matrix != null && center != null && feather != null && crystal != null && emptySameColumn != null,
                "matrix=" + (matrix != null)
                        + ", center=" + (center != null)
                        + ", feather=" + (feather != null)
                        + ", crystal=" + (crystal != null)
        ));
        if (matrix == null || center == null || feather == null || crystal == null) {
            return;
        }

        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));

        TCInfusionMatrixBlockEntity.Snapshot snapshot = matrix.createSnapshot(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_detects_legacy_center_and_surrounding_pedestals",
                snapshot.hasCentralPedestal()
                        && snapshot.surroundingPedestalCount() == 3
                        && snapshot.componentCount() == 2,
                "surrounding=" + snapshot.surroundingPedestalCount() + ", components=" + snapshot.componentCount()
        ));

        TCInfusionValidationResult runtimeResult = matrix.validateAgainst(cloudRing, new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_snapshot_matches_cloudring_recipe",
                runtimeResult.valid()
                        && runtimeResult.requiredComponentCount() == 2
                        && runtimeResult.suppliedComponentCount() == 2,
                "reason=" + runtimeResult.reason() + ", recipe=" + runtimeResult.recipeId()
        ));

        TCInfusionStartResult startResult = matrix.startCraftingForValidation(
                cloudRing,
                new AspectList().add(Aspect.AIR, 50),
                "AuditPlayer"
        );
        Optional<TCInfusionCraftingPlan> activePlan = matrix.activePlan();
        checks.add(new Check(
                "runtime_matrix_start_plan_cloudring",
                startResult.started()
                        && matrix.isCrafting()
                        && activePlan.isPresent()
                        && CLOUD_RING.equals(activePlan.get().recipeId()),
                "started=" + startResult.started() + ", reason=" + startResult.reason()
        ));
        checks.add(new Check(
                "runtime_matrix_start_plan_records_legacy_fields",
                activePlan.isPresent()
                        && "CLOUDRING".equals(activePlan.get().research())
                        && activePlan.get().instability() == 1
                        && activePlan.get().catalyst().is(TCItems.BAUBLE_RING.get())
                        && activePlan.get().components().size() == 2
                        && activePlan.get().requiredAspects().getAmount(Aspect.AIR) == 50
                        && activePlan.get().result().is(TCItems.CLOUD_RING.get())
                        && "AuditPlayer".equals(activePlan.get().playerName()),
                activePlan.map(plan -> "research=" + plan.research()
                                + ", instability=" + plan.instability()
                                + ", components=" + plan.components().size()
                                + ", aspects=" + plan.requiredAspectAmount())
                        .orElse("no active plan")
        ));
        checks.add(new Check(
                "runtime_matrix_start_plan_records_component_pedestal_positions",
                activePlan.isPresent()
                        && activePlan.get().componentPedestalPositions().size() == 2
                        && activePlan.get().componentPedestalPositions().contains(featherPos)
                        && activePlan.get().componentPedestalPositions().contains(crystalPos),
                activePlan.map(plan -> "positions=" + plan.componentPedestalPositions()).orElse("no active plan")
        ));
        checks.add(new Check(
                "runtime_matrix_active_plan_persists_through_nbt",
                activePlan.map(plan -> TCInfusionCraftingPlan.load(plan.save(server.registryAccess()), server.registryAccess()))
                        .map(loaded -> CLOUD_RING.equals(loaded.recipeId())
                                && loaded.components().size() == 2
                                && loaded.requiredAspects().getAmount(Aspect.AIR) == 50
                                && loaded.result().is(TCItems.CLOUD_RING.get()))
                        .orElse(false),
                activePlan.map(plan -> "recipe=" + plan.recipeId()).orElse("no active plan")
        ));
        TCInfusionCompletionPlan completionPlan = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_cloudring",
                completionPlan.valid()
                        && "valid".equals(completionPlan.reason())
                        && completionPlan.componentCount() == 2
                        && completionPlan.requiredAspectAmount() == 50
                        && completionPlan.remainingAspects().visSize() == 0,
                "reason=" + completionPlan.reason()
                        + ", components=" + completionPlan.componentCount()
                        + ", missing=" + completionPlan.missingAspectAmount()
        ));
        TCInfusionCompletionPlan missingAspectCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 49));
        checks.add(new Check(
                "runtime_matrix_completion_plan_requires_all_aspects",
                !missingAspectCompletion.valid()
                        && "missing_aspects".equals(missingAspectCompletion.reason())
                        && missingAspectCompletion.missingAspects().getAmount(Aspect.AIR) == 1,
                "reason=" + missingAspectCompletion.reason()
                        + ", missingAer=" + missingAspectCompletion.missingAspects().getAmount(Aspect.AIR)
        ));

        center.setStoredForValidation(new ItemStack(Items.IRON_INGOT));
        TCInfusionCompletionPlan changedCatalystCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_rechecks_catalyst",
                !changedCatalystCompletion.valid() && "catalyst_changed".equals(changedCatalystCompletion.reason()),
                "reason=" + changedCatalystCompletion.reason()
        ));
        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));

        feather.setStoredForValidation(new ItemStack(Items.STICK));
        TCInfusionCompletionPlan changedComponentCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_rechecks_component_stack",
                !changedComponentCompletion.valid() && "component_changed".equals(changedComponentCompletion.reason()),
                "reason=" + changedComponentCompletion.reason()
        ));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));

        level.setBlock(featherPos, Blocks.AIR.defaultBlockState(), 3);
        TCInfusionCompletionPlan missingComponentPedestalCompletion = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_completion_plan_rechecks_component_pedestal",
                !missingComponentPedestalCompletion.valid()
                        && "missing_component_pedestal".equals(missingComponentPedestalCompletion.reason()),
                "reason=" + missingComponentPedestalCompletion.reason()
        ));
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        if (feather != null) {
            feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        }

        TCInfusionStartResult secondStart = matrix.startCraftingForValidation(
                cloudRing,
                new AspectList().add(Aspect.AIR, 50),
                "AuditPlayer"
        );
        checks.add(new Check(
                "runtime_matrix_rejects_second_start_while_active",
                !secondStart.started() && "already_crafting".equals(secondStart.reason()),
                "reason=" + secondStart.reason()
        ));
        matrix.abortCrafting();
        checks.add(new Check(
                "runtime_matrix_abort_clears_start_plan",
                !matrix.isCrafting() && matrix.activePlan().isEmpty(),
                "active=" + matrix.isCrafting()
        ));

        level.setBlock(extraPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionPedestalBlockEntity extra = blockEntity(level, extraPos, TCInfusionPedestalBlockEntity.class);
        if (extra != null) {
            extra.setStoredForValidation(new ItemStack(Items.STICK));
        }
        TCInfusionValidationResult extraResult = matrix.validateAgainst(cloudRing, new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_extra_filled_pedestal_fails_one_to_one_match",
                !extraResult.valid() && "component_mismatch".equals(extraResult.reason()),
                "reason=" + extraResult.reason() + ", components=" + matrix.createSnapshot(new AspectList()).componentCount()
        ));

        level.setBlock(centerPos, Blocks.AIR.defaultBlockState(), 3);
        TCInfusionValidationResult missingCenterResult = matrix.validateAgainst(cloudRing, new AspectList().add(Aspect.AIR, 50));
        checks.add(new Check(
                "runtime_matrix_requires_central_pedestal_two_blocks_below",
                !missingCenterResult.valid() && "missing_central_pedestal".equals(missingCenterResult.reason()),
                "reason=" + missingCenterResult.reason()
        ));
    }

    private static void addAspectSourceMutationExecutorChecks(MinecraftServer server, RecipeHolder<TCInfusionRecipe> cloudRing, ArrayList<Check> checks) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(36, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);

        clearTestArea(level, matrixPos);
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        if (matrix == null || center == null || feather == null || crystal == null) {
            checks.add(new Check("runtime_aspect_source_executor_setup_created", false, "missing block entity"));
            return;
        }
        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        matrix.startCraftingForValidation(cloudRing, new AspectList().add(Aspect.AIR, 50), "AuditPlayer");
        TCInfusionCompletionPlan completionPlan = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionAspectSource exactSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 50));
        TCInfusionMutationExecutor.Result result = TCInfusionMutationExecutor.executeWithAspectSource(matrix, completionPlan, exactSource);
        checks.add(new Check(
                "runtime_mutation_executor_drains_aspect_source_before_item_completion",
                result.success()
                        && exactSource.availableAspects().visSize() == 0
                        && center.getStoredStack().is(TCItems.CLOUD_RING.get())
                        && feather.getStoredStack().isEmpty()
                        && crystal.getStoredStack().isEmpty()
                        && !matrix.isCrafting(),
                "reason=" + result.reason() + ", sourceRemaining=" + exactSource.availableAspects().visSize()
        ));

        BlockPos failMatrixPos = new BlockPos(48, level.getMinBuildHeight() + 12, 0);
        BlockPos failCenterPos = failMatrixPos.below(2);
        BlockPos failFeatherPos = failMatrixPos.offset(2, -2, 0);
        BlockPos failCrystalPos = failMatrixPos.offset(-2, -2, 0);
        clearTestArea(level, failMatrixPos);
        level.setBlock(failMatrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(failCenterPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failFeatherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failCrystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionMatrixBlockEntity failMatrix = blockEntity(level, failMatrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity failCenter = blockEntity(level, failCenterPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failFeather = blockEntity(level, failFeatherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failCrystal = blockEntity(level, failCrystalPos, TCInfusionPedestalBlockEntity.class);
        if (failMatrix == null || failCenter == null || failFeather == null || failCrystal == null) {
            checks.add(new Check("runtime_aspect_source_executor_missing_source_setup_created", false, "missing block entity"));
            return;
        }
        failCenter.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        failFeather.setStoredForValidation(new ItemStack(Items.FEATHER));
        failCrystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        failMatrix.startCraftingForValidation(cloudRing, new AspectList().add(Aspect.AIR, 50), "AuditPlayer");
        TCInfusionCompletionPlan failCompletionPlan = failMatrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionAspectSource insufficientSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 49));
        TCInfusionMutationExecutor.Result failedResult = TCInfusionMutationExecutor.executeWithAspectSource(failMatrix, failCompletionPlan, insufficientSource);
        checks.add(new Check(
                "runtime_mutation_executor_rejects_insufficient_aspect_source_without_item_mutation",
                !failedResult.success()
                        && "aspect_source_missing_aspects".equals(failedResult.reason())
                        && insufficientSource.availableAspects().getAmount(Aspect.AIR) == 49
                        && failCenter.getStoredStack().is(TCItems.BAUBLE_RING.get())
                        && failFeather.getStoredStack().is(Items.FEATHER)
                        && failCrystal.getStoredStack().is(TCItems.CRYSTAL_ESSENCE_AER.get())
                        && failMatrix.isCrafting(),
                "reason=" + failedResult.reason() + ", sourceAir=" + insufficientSource.availableAspects().getAmount(Aspect.AIR)
        ));
    }
    private static void addAspectSourceBoundaryChecks(ArrayList<Check> checks) {
        TCInfusionCraftingPlan cloudRingPlan = new TCInfusionCraftingPlan(
                CLOUD_RING,
                "CLOUDRING",
                1,
                new ItemStack(TCItems.BAUBLE_RING.get()),
                List.of(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()), new ItemStack(Items.FEATHER)),
                List.of(BlockPos.ZERO, BlockPos.ZERO.offset(1, 0, 0)),
                new AspectList().add(Aspect.AIR, 50),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );

        TCInfusionAspectSource exactSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 50));
        TCInfusionAspectSource.DrainResult exactDrain = exactSource.drain(cloudRingPlan);
        checks.add(new Check(
                "infusion_aspect_source_drains_exact_required_aspects",
                exactDrain.success()
                        && "drained".equals(exactDrain.reason())
                        && exactDrain.drainedAspects().getAmount(Aspect.AIR) == 50
                        && exactDrain.remainingAspects().visSize() == 0
                        && exactSource.availableAspects().visSize() == 0,
                "reason=" + exactDrain.reason() + ", remaining=" + exactDrain.remainingAspects().visSize()
        ));

        TCInfusionAspectSource insufficientSource = TCInfusionAspectSource.memory(new AspectList().add(Aspect.AIR, 49));
        TCInfusionAspectSource.DrainResult missingDrain = insufficientSource.drain(cloudRingPlan);
        checks.add(new Check(
                "infusion_aspect_source_rejects_insufficient_aspects_without_drain",
                !missingDrain.success()
                        && "missing_aspects".equals(missingDrain.reason())
                        && missingDrain.missingAspects().getAmount(Aspect.AIR) == 1
                        && insufficientSource.availableAspects().getAmount(Aspect.AIR) == 49,
                "reason=" + missingDrain.reason() + ", missingAir=" + missingDrain.missingAspects().getAmount(Aspect.AIR)
        ));
    }
    private static void addContainerRemainderPolicyChecks(ArrayList<Check> checks) {
        TCInfusionCraftingPlan safePlan = new TCInfusionCraftingPlan(
                CLOUD_RING,
                "CLOUDRING",
                1,
                new ItemStack(TCItems.BAUBLE_RING.get()),
                List.of(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()), new ItemStack(Items.FEATHER)),
                List.of(BlockPos.ZERO, BlockPos.ZERO.offset(1, 0, 0)),
                new AspectList().add(Aspect.AIR, 50),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );
        TCInfusionCraftingPlan blockedPlan = new TCInfusionCraftingPlan(
                ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "audit_container_remainder_guard"),
                "AUDIT",
                0,
                new ItemStack(TCItems.BAUBLE_RING.get()),
                List.of(new ItemStack(Items.WATER_BUCKET)),
                List.of(BlockPos.ZERO),
                new AspectList(),
                new ItemStack(TCItems.CLOUD_RING.get()),
                "AuditPlayer"
        );
        checks.add(new Check(
                "infusion_container_policy_allows_current_cloudring_inputs",
                !TCInfusionContainerRemainderPolicy.requiresExplicitPolicy(safePlan),
                "cloudring has no bucket/bottle/bowl input"
        ));
        checks.add(new Check(
                "infusion_container_policy_blocks_water_bucket_plan",
                TCInfusionContainerRemainderPolicy.requiresExplicitPolicy(blockedPlan)
                        && TCInfusionContainerRemainderPolicy.firstBlockingInput(blockedPlan).orElse("").equals("component[0]"),
                "blocker=" + TCInfusionContainerRemainderPolicy.firstBlockingInput(blockedPlan).orElse("none")
        ));
    }
    private static void addRuntimeMutationExecutorChecks(MinecraftServer server, RecipeHolder<TCInfusionRecipe> cloudRing, ArrayList<Check> checks) {
        ServerLevel level = server.overworld();
        BlockPos matrixPos = new BlockPos(12, level.getMinBuildHeight() + 12, 0);
        BlockPos centerPos = matrixPos.below(2);
        BlockPos featherPos = matrixPos.offset(2, -2, 0);
        BlockPos crystalPos = matrixPos.offset(-2, -2, 0);

        clearTestArea(level, matrixPos);
        level.setBlock(matrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(centerPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(featherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(crystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);

        TCInfusionMatrixBlockEntity matrix = blockEntity(level, matrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity center = blockEntity(level, centerPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity feather = blockEntity(level, featherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity crystal = blockEntity(level, crystalPos, TCInfusionPedestalBlockEntity.class);
        checks.add(new Check(
                "runtime_mutation_executor_setup_created",
                matrix != null && center != null && feather != null && crystal != null,
                "matrix=" + (matrix != null) + ", center=" + (center != null)
        ));
        if (matrix == null || center == null || feather == null || crystal == null) {
            return;
        }

        center.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        feather.setStoredForValidation(new ItemStack(Items.FEATHER));
        crystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        TCInfusionStartResult startResult = matrix.startCraftingForValidation(
                cloudRing,
                new AspectList().add(Aspect.AIR, 50),
                "AuditPlayer"
        );
        TCInfusionCompletionPlan completionPlan = matrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionMutationExecutor.Result result = TCInfusionMutationExecutor.execute(matrix, completionPlan);
        checks.add(new Check(
                "runtime_mutation_executor_executes_valid_plan",
                startResult.started()
                        && result.success()
                        && "executed".equals(result.reason())
                        && result.consumedComponents() == 2
                        && result.result().is(TCItems.CLOUD_RING.get()),
                "started=" + startResult.started() + ", reason=" + result.reason()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_places_result_on_center",
                center.getStoredStack().is(TCItems.CLOUD_RING.get()),
                "center=" + center.getStoredStack().getItem()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_consumes_component_pedestals",
                feather.getStoredStack().isEmpty() && crystal.getStoredStack().isEmpty(),
                "featherEmpty=" + feather.getStoredStack().isEmpty() + ", crystalEmpty=" + crystal.getStoredStack().isEmpty()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_clears_active_plan",
                !matrix.isCrafting() && matrix.activePlan().isEmpty(),
                "active=" + matrix.isCrafting()
        ));

        BlockPos failMatrixPos = new BlockPos(24, level.getMinBuildHeight() + 12, 0);
        BlockPos failCenterPos = failMatrixPos.below(2);
        BlockPos failFeatherPos = failMatrixPos.offset(2, -2, 0);
        BlockPos failCrystalPos = failMatrixPos.offset(-2, -2, 0);
        clearTestArea(level, failMatrixPos);
        level.setBlock(failMatrixPos, TCBlocks.INFUSION_MATRIX.get().defaultBlockState(), 3);
        level.setBlock(failCenterPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failFeatherPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        level.setBlock(failCrystalPos, TCBlocks.ARCANE_PEDESTAL.get().defaultBlockState(), 3);
        TCInfusionMatrixBlockEntity failMatrix = blockEntity(level, failMatrixPos, TCInfusionMatrixBlockEntity.class);
        TCInfusionPedestalBlockEntity failCenter = blockEntity(level, failCenterPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failFeather = blockEntity(level, failFeatherPos, TCInfusionPedestalBlockEntity.class);
        TCInfusionPedestalBlockEntity failCrystal = blockEntity(level, failCrystalPos, TCInfusionPedestalBlockEntity.class);
        if (failMatrix == null || failCenter == null || failFeather == null || failCrystal == null) {
            checks.add(new Check("runtime_mutation_executor_invalid_plan_setup_created", false, "missing block entity"));
            return;
        }
        failCenter.setStoredForValidation(new ItemStack(TCItems.BAUBLE_RING.get()));
        failFeather.setStoredForValidation(new ItemStack(Items.FEATHER));
        failCrystal.setStoredForValidation(new ItemStack(TCItems.CRYSTAL_ESSENCE_AER.get()));
        failMatrix.startCraftingForValidation(cloudRing, new AspectList().add(Aspect.AIR, 50), "AuditPlayer");
        failFeather.setStoredForValidation(new ItemStack(Items.STICK));
        TCInfusionCompletionPlan invalidCompletion = failMatrix.createCompletionPlan(new AspectList().add(Aspect.AIR, 50));
        TCInfusionMutationExecutor.Result failedExecution = TCInfusionMutationExecutor.execute(failMatrix, invalidCompletion);
        checks.add(new Check(
                "runtime_mutation_executor_rejects_invalid_completion_plan",
                !failedExecution.success() && "invalid_completion_plan".equals(failedExecution.reason()),
                "reason=" + failedExecution.reason()
        ));
        checks.add(new Check(
                "runtime_mutation_executor_invalid_plan_noops_world_state",
                failMatrix.isCrafting()
                        && failCenter.getStoredStack().is(TCItems.BAUBLE_RING.get())
                        && failFeather.getStoredStack().is(Items.STICK)
                        && failCrystal.getStoredStack().is(TCItems.CRYSTAL_ESSENCE_AER.get()),
                "active=" + failMatrix.isCrafting()
        ));
    }
    private static void clearTestArea(ServerLevel level, BlockPos matrixPos) {
        for (int dx = -3; dx <= 3; dx++) {
            for (int dy = -3; dy <= 1; dy++) {
                for (int dz = -3; dz <= 3; dz++) {
                    level.setBlock(matrixPos.offset(dx, dy, dz), Blocks.AIR.defaultBlockState(), 3);
                }
            }
        }
    }

    private static <T> T blockEntity(ServerLevel level, BlockPos pos, Class<T> type) {
        Object blockEntity = level.getBlockEntity(pos);
        return type.isInstance(blockEntity) ? type.cast(blockEntity) : null;
    }

    public record Report(List<Check> checks, int infusionRecipeCount) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
