package thaumcraft.common.items.casters;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.util.FakePlayerFactory;
import thaumcraft.Thaumcraft;
import thaumcraft.common.items.components.TCFocusPackageComponent;
import thaumcraft.common.registry.TCBlockEntities;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.registry.TCDataComponents;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.registry.TCMenus;
import thaumcraft.common.research.TCPlayerKnowledge;
import thaumcraft.common.research.TCPlayerKnowledgeStore;
import thaumcraft.common.tiles.crafting.TCFocalManipulatorBlockEntity;
import thaumcraft.common.world.aura.AuraHandler;

public final class TCFocusCasterCoreAudit {
    private static final BlockPos AUDIT_POS = new BlockPos(48, 80, 48);

    private TCFocusCasterCoreAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Focus / Caster / Focal Manipulator Core Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter after registry and data reload.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This closes the first core data/behavior boundary for caster stacks, focus package data, aura cost consumption and the Focal Manipulator craft cycle.");
        lines.add("- It intentionally does not claim full focus effect execution, projectiles/clouds/mines, Focus Pouch GUI or final Focal Manipulator editor visual parity.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        ServerLevel level = server.overworld();
        ServerPlayer player = FakePlayerFactory.getMinecraft(level);
        player.getInventory().clearContent();
        grantFocusResearch(player);

        TCFocusPackageComponent samplePackage = samplePackage();
        checks.add(checkFocusElementRegistry());
        checks.add(checkItemIdentity());
        checks.add(checkPackageMath(samplePackage));
        checks.add(checkDefaultSettingRoundTrip());
        checks.add(checkCasterFocusComponent(player, level, samplePackage));
        checks.addAll(checkFocalManipulatorCycle(player, level, samplePackage));
        checks.add(checkRegistries());

        level.setBlock(AUDIT_POS, Blocks.AIR.defaultBlockState(), 3);
        player.getInventory().clearContent();
        return new Report(List.copyOf(checks));
    }

    private static Check checkFocusElementRegistry() {
        boolean passed = TCFocusElements.definitions().size() == 21
                && TCFocusElements.get("ROOT").isPresent()
                && TCFocusElements.get("thaumcraft.FIRE").map(definition -> definition.complexity(Map.of()) == 2).orElse(false)
                && TCFocusElements.get("thaumcraft.CLOUD").map(definition -> definition.complexity(Map.of()) == 7).orElse(false)
                && TCFocusElements.get("thaumcraft.RIFT").map(definition -> definition.complexity(Map.of()) == 6).orElse(false)
                && TCFocusElements.get("thaumcraft.SCATTER").map(definition -> definition.complexity(Map.of()) == 3).orElse(false);
        return new Check(
                "legacy_focus_element_registry",
                passed,
                "definitions=" + TCFocusElements.definitions().size() + ", expected root + 20 registered elements"
        );
    }

    private static Check checkItemIdentity() {
        boolean passed = TCItems.CASTER_BASIC.get() instanceof ItemCaster caster
                && caster.area() == 0
                && TCItems.FOCUS_1.get() instanceof ItemFocus focus1
                && focus1.maxComplexity() == 15
                && TCItems.FOCUS_2.get() instanceof ItemFocus focus2
                && focus2.maxComplexity() == 25
                && TCItems.FOCUS_3.get() instanceof ItemFocus focus3
                && focus3.maxComplexity() == 50
                && TCItems.FOCUS_POUCH.get() instanceof ItemFocusPouch
                && new ItemStack(TCItems.CASTER_BASIC.get()).getRarity() == Rarity.UNCOMMON
                && new ItemStack(TCItems.FOCUS_1.get()).getRarity() == Rarity.RARE;
        return new Check(
                "caster_focus_item_identity",
                passed,
                "caster area=0, focus maxComplexity=15/25/50, focus_pouch real id"
        );
    }

    private static Check checkPackageMath(TCFocusPackageComponent samplePackage) {
        Map<String, Integer> crystals = TCFocusPackageHelper.crystalCosts(samplePackage);
        boolean passed = samplePackage.complexity() == 4
                && Math.abs(TCFocusPackageHelper.getVisCost(samplePackage) - 0.8F) < 0.001F
                && TCFocusPackageHelper.getActivationTime(samplePackage) == 5
                && samplePackage.color() == 0xFF5A01
                && crystals.getOrDefault("aversio", 0) == 1
                && crystals.getOrDefault("ignis", 0) == 1;
        return new Check(
                "focus_package_legacy_math",
                passed,
                "sample ROOT->TOUCH->FIRE complexity=" + samplePackage.complexity()
                        + ", vis=" + TCFocusPackageHelper.getVisCost(samplePackage)
                        + ", activation=" + TCFocusPackageHelper.getActivationTime(samplePackage)
                        + ", crystals=" + crystals
        );
    }

    private static Check checkDefaultSettingRoundTrip() {
        TCFocusPackageComponent cursePackage = TCFocusPackageHelper.buildPackage(List.of(
                new TCFocusPackageHelper.NodeInstance(0, "ROOT", -1, List.of(1), Map.of()),
                new TCFocusPackageHelper.NodeInstance(1, "thaumcraft.TOUCH", 0, List.of(2), Map.of()),
                new TCFocusPackageHelper.NodeInstance(2, "thaumcraft.CURSE", 1, List.of(), Map.of())
        ));
        TCFocusPackageComponent decoded = TCFocusPackageHelper.buildPackage(TCFocusPackageHelper.decode(cursePackage.nodes()));
        boolean passed = cursePackage.complexity() == 6
                && decoded.complexity() == 6
                && TCFocusPackageHelper.getActivationTime(decoded) == 5;
        return new Check(
                "focus_package_default_setting_roundtrip",
                passed,
                "CURSE default package complexity=" + cursePackage.complexity()
                        + ", decodedComplexity=" + decoded.complexity()
                        + ", nodes=" + decoded.nodes()
        );
    }

    private static Check checkCasterFocusComponent(ServerPlayer player, ServerLevel level, TCFocusPackageComponent samplePackage) {
        ItemCaster casterItem = (ItemCaster) TCItems.CASTER_BASIC.get();
        ItemStack caster = new ItemStack(casterItem);
        ItemStack focus = new ItemStack(TCItems.FOCUS_1.get());
        ((ItemFocus) focus.getItem()).setPackage(focus, samplePackage);
        casterItem.setFocus(caster, focus);
        AuraHandler.seedAuraChunk(level, player.blockPosition(), 100);
        boolean simulated = casterItem.consumeVis(caster, player, 10.0F, false, true);
        float before = AuraHandler.getVis(level, player.blockPosition());
        boolean consumed = casterItem.consumeVis(caster, player, 10.0F, false, false);
        float after = AuraHandler.getVis(level, player.blockPosition());
        boolean passed = caster.has(TCDataComponents.CASTER_FOCUS.get())
                && casterItem.hasFocus(caster)
                && !casterItem.getFocusStack(caster).isEmpty()
                && simulated
                && consumed
                && Math.abs((before - after) - 10.0F) < 0.001F;
        return new Check(
                "caster_component_and_area0_vis_drain",
                passed,
                "simulated=" + simulated + ", consumed=" + consumed + ", before=" + before + ", after=" + after
        );
    }

    private static List<Check> checkFocalManipulatorCycle(ServerPlayer player, ServerLevel level, TCFocusPackageComponent expectedPackage) {
        ArrayList<Check> checks = new ArrayList<>();
        level.setBlock(AUDIT_POS, TCBlocks.WAND_WORKBENCH.get().defaultBlockState(), 3);
        TCFocalManipulatorBlockEntity manipulator = level.getBlockEntity(AUDIT_POS) instanceof TCFocalManipulatorBlockEntity focal ? focal : null;
        checks.add(new Check(
                "focal_manipulator_block_entity_created",
                manipulator != null,
                "block=" + BuiltInRegistries.BLOCK.getKey(TCBlocks.WAND_WORKBENCH.get())
        ));
        if (manipulator == null) {
            return checks;
        }

        player.getInventory().clearContent();
        player.giveExperienceLevels(30);
        addCrystal(player, "aversio", 1);
        addCrystal(player, "ignis", 1);
        manipulator.setItem(TCFocalManipulatorBlockEntity.SLOT_FOCUS, new ItemStack(TCItems.FOCUS_1.get()));
        boolean badRejected = !manipulator.applyDesignRequest(player, "0|thaumcraft.NOPE|-1||", "Bad");
        boolean overcomplexAccepted = manipulator.applyDesignRequest(player, overcomplexPackage().nodes(), "Too Strong");
        boolean overcomplexRejectedAtStart = !manipulator.startCraft(player) && manipulator.remainingVis() <= 0.0F;
        boolean validAccepted = manipulator.applyDesignRequest(player, expectedPackage.nodes(), "Audit Focus");
        checks.add(new Check(
                "focal_manipulator_design_request_validation",
                badRejected && overcomplexAccepted && overcomplexRejectedAtStart && validAccepted,
                "badRejected=" + badRejected
                        + ", overcomplexAccepted=" + overcomplexAccepted
                        + ", overcomplexRejectedAtStart=" + overcomplexRejectedAtStart
                        + ", validAccepted=" + validAccepted
        ));
        AuraHandler.seedAuraChunk(level, AUDIT_POS, 200);
        boolean started = manipulator.startCraft(player);
        checks.add(new Check(
                "focal_manipulator_start_contract",
                started
                        && manipulator.remainingVis() == 43.0F
                        && manipulator.xpCost() == 2
                        && countCrystals(player, "aversio") == 0
                        && countCrystals(player, "ignis") == 0,
                "started=" + started + ", remainingVis=" + manipulator.remainingVis() + ", xp=" + manipulator.xpCost()
        ));

        for (int i = 0; i < 4; i++) {
            TCFocalManipulatorBlockEntity.serverTick(level, AUDIT_POS, TCBlocks.WAND_WORKBENCH.get().defaultBlockState(), manipulator);
            for (int skip = 0; skip < 19; skip++) {
                TCFocalManipulatorBlockEntity.serverTick(level, AUDIT_POS, TCBlocks.WAND_WORKBENCH.get().defaultBlockState(), manipulator);
            }
        }
        ItemStack craftedFocus = manipulator.getItem(TCFocalManipulatorBlockEntity.SLOT_FOCUS);
        TCFocusPackageComponent actualPackage = TCFocusPackageHelper.getPackage(craftedFocus);
        checks.add(new Check(
                "focal_manipulator_completion_writes_focus_package",
                manipulator.remainingVis() <= 0.0F
                        && !actualPackage.isEmpty()
                        && actualPackage.complexity() == expectedPackage.complexity()
                        && craftedFocus.getHoverName().getString().equals("Audit Focus"),
                "remainingVis=" + manipulator.remainingVis() + ", packageComplexity=" + actualPackage.complexity()
        ));
        return checks;
    }

    private static Check checkRegistries() {
        boolean passed = TCBlockEntities.FOCAL_MANIPULATOR.get().isValid(TCBlocks.WAND_WORKBENCH.get().defaultBlockState())
                && TCMenus.FOCAL_MANIPULATOR.get() != null
                && BuiltInRegistries.ITEM.getKey(TCItems.FOCUS_POUCH.get()).equals(ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "focus_pouch"));
        return new Check(
                "focal_manipulator_registries",
                passed,
                "blockEntity=wand_workbench, menu=focal_manipulator, item=focus_pouch"
        );
    }

    private static TCFocusPackageComponent samplePackage() {
        return TCFocusPackageHelper.buildPackage(List.of(
                new TCFocusPackageHelper.NodeInstance(0, "ROOT", -1, List.of(1), Map.of()),
                new TCFocusPackageHelper.NodeInstance(1, "thaumcraft.TOUCH", 0, List.of(2), Map.of()),
                new TCFocusPackageHelper.NodeInstance(2, "thaumcraft.FIRE", 1, List.of(), Map.of())
        ));
    }

    private static TCFocusPackageComponent overcomplexPackage() {
        return TCFocusPackageHelper.buildPackage(List.of(
                new TCFocusPackageHelper.NodeInstance(0, "ROOT", -1, List.of(1), Map.of()),
                new TCFocusPackageHelper.NodeInstance(1, "thaumcraft.TOUCH", 0, List.of(2), Map.of()),
                new TCFocusPackageHelper.NodeInstance(2, "thaumcraft.FIRE", 1, List.of(), Map.of("power", 5, "duration", 5))
        ));
    }

    private static void grantFocusResearch(ServerPlayer player) {
        TCPlayerKnowledge knowledge = TCPlayerKnowledgeStore.get(player);
        for (TCFocusElementDefinition definition : TCFocusElements.definitions().values()) {
            if (definition.research().isBlank()) {
                continue;
            }
            String key = TCPlayerKnowledge.baseResearchKey(definition.research());
            knowledge.addResearch(key);
            knowledge.setResearchStage(key, 10);
        }
        TCPlayerKnowledgeStore.set(player, knowledge, false);
    }

    private static void addCrystal(ServerPlayer player, String aspect, int count) {
        BuiltInRegistries.ITEM.getOptional(ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "crystal_essence_" + aspect))
                .map(item -> new ItemStack(item, count))
                .ifPresent(player.getInventory()::add);
    }

    private static int countCrystals(ServerPlayer player, String aspect) {
        int count = 0;
        for (ItemStack stack : player.getInventory().items) {
            if (thaumcraft.common.crafting.arcane.TCArcaneWorkbenchCrafting.isCrystal(stack, aspect)) {
                count += stack.getCount();
            }
        }
        return count;
    }

    public record Report(List<Check> checks) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
