package thaumcraft.common.items.casters;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.animal.Cow;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.util.FakePlayerFactory;
import thaumcraft.common.items.components.TCFocusPackageComponent;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.world.aura.AuraHandler;

public final class TCFocusCastExecutionAudit {
    private static final BlockPos AUDIT_POS = new BlockPos(80, 90, 80);

    private TCFocusCastExecutionAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Focus Cast Execution Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter after registry and data reload.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This audit validates the first server-owned focus execution slice only: legacy ROOT -> TOUCH -> FIRE.");
        lines.add("- Unsupported focus packages fail before vis/aura drain; projectile, cloud, mine, split and other effects remain separate audited slices.");
        lines.add("- Fire follows the audited legacy formulas for default power/duration: damage=(3+power)*finalPower and fireSeconds=(1+duration^2)*finalPower.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        ServerLevel level = server.overworld();
        ServerPlayer player = FakePlayerFactory.getMinecraft(level);
        player.getInventory().clearContent();
        clearArea(level);
        moveAuditPlayer(player);

        checks.add(checkPlanValidation());
        checks.add(checkUnsupportedDoesNotDrain(player, level));
        checks.add(checkSupportedFocusUseDrainsAndCooldowns(player, level));
        checks.add(checkTouchFireDamagesAndIgnitesEntity(player, level));
        checks.add(checkTouchFirePlacesFireOnBlock(player, level));

        player.getInventory().clearContent();
        clearArea(level);
        return new Report(List.copyOf(checks));
    }

    private static Check checkPlanValidation() {
        TCFocusCastExecutor.CastPlan valid = TCFocusCastExecutor.plan(focus(touchFirePackage(0)));
        TCFocusCastExecutor.CastPlan unsupported = TCFocusCastExecutor.plan(focus(unsupportedFrostPackage()));
        boolean passed = valid.supported()
                && "ROOT->TOUCH->FIRE".equals(valid.reason())
                && !unsupported.supported();
        return new Check(
                "touch_fire_plan_validation",
                passed,
                "valid=" + valid.supported() + ", unsupportedReason=" + unsupported.reason()
        );
    }

    private static Check checkUnsupportedDoesNotDrain(ServerPlayer player, ServerLevel level) {
        moveAuditPlayer(player);
        ItemCaster casterItem = (ItemCaster) TCItems.CASTER_BASIC.get();
        ItemStack caster = casterWithFocus(unsupportedFrostPackage());
        player.setItemInHand(InteractionHand.MAIN_HAND, caster);
        AuraHandler.seedAuraChunk(level, player.blockPosition(), 100);
        float before = AuraHandler.getVis(level, player.blockPosition());
        InteractionResultHolder<ItemStack> result = casterItem.use(level, player, InteractionHand.MAIN_HAND);
        float after = AuraHandler.getVis(level, player.blockPosition());
        boolean passed = result.getResult() == InteractionResult.FAIL
                && Math.abs(before - after) < 0.001F
                && !CasterManager.isOnCooldown(player);
        CasterManager.clearCooldown(player, caster);
        return new Check(
                "unsupported_focus_fails_before_vis_drain",
                passed,
                "before=" + before + ", after=" + after + ", result=" + result.getResult()
        );
    }

    private static Check checkSupportedFocusUseDrainsAndCooldowns(ServerPlayer player, ServerLevel level) {
        clearArea(level);
        moveAuditPlayer(player);
        ItemCaster casterItem = (ItemCaster) TCItems.CASTER_BASIC.get();
        ItemStack caster = casterWithFocus(touchFirePackage(0));
        player.setItemInHand(InteractionHand.MAIN_HAND, caster);
        CasterManager.clearCooldown(player, caster);
        AuraHandler.seedAuraChunk(level, player.blockPosition(), 100);
        float before = AuraHandler.getVis(level, player.blockPosition());
        InteractionResultHolder<ItemStack> result = casterItem.use(level, player, InteractionHand.MAIN_HAND);
        float after = AuraHandler.getVis(level, player.blockPosition());
        boolean passed = result.getResult().consumesAction()
                && before > after
                && CasterManager.isOnCooldown(player);
        CasterManager.clearCooldown(player, caster);
        return new Check(
                "supported_focus_use_drains_vis_and_sets_cooldown",
                passed,
                "before=" + before + ", after=" + after + ", result=" + result.getResult()
        );
    }

    private static Check checkTouchFireDamagesAndIgnitesEntity(ServerPlayer player, ServerLevel level) {
        clearArea(level);
        moveAuditPlayer(player);
        ItemStack focus = focus(touchFirePackage(0));
        Cow cow = EntityType.COW.create(level);
        if (cow == null) {
            return new Check("touch_fire_entity_damage_and_burn", false, "cow factory returned null");
        }
        cow.moveTo(AUDIT_POS.getX() + 0.5D, AUDIT_POS.getY(), AUDIT_POS.getZ() + 3.5D, 180.0F, 0.0F);
        cow.setNoAi(true);
        cow.setHealth(10.0F);
        float beforeHealth = cow.getHealth();
        TCFocusCastExecutor.CastResult result = TCFocusCastExecutor.executeTouchFireAtEntity(player, focus, cow);
        float afterHealth = cow.getHealth();
        boolean passed = result.supported()
                && result.applied()
                && beforeHealth - afterHealth >= 3.9F
                && cow.getRemainingFireTicks() > 0;
        String notes = "health=" + beforeHealth + "->" + afterHealth
                + ", fireTicks=" + cow.getRemainingFireTicks()
                + ", result=" + result.notes();
        cow.discard();
        return new Check("touch_fire_entity_damage_and_burn", passed, notes);
    }

    private static Check checkTouchFirePlacesFireOnBlock(ServerPlayer player, ServerLevel level) {
        clearArea(level);
        moveAuditPlayer(player);
        ItemStack focus = focus(touchFirePackage(1));
        BlockPos target = AUDIT_POS.offset(0, 0, 3);
        level.setBlock(target, Blocks.STONE.defaultBlockState(), 3);
        BlockPos firePos = target.relative(Direction.UP);
        TCFocusCastExecutor.CastResult result = TCFocusCastExecutor.executeTouchFireAtBlock(player, focus, target, Direction.UP);
        boolean firePlaced = level.getBlockState(firePos).is(Blocks.FIRE);
        boolean passed = result.supported() && result.applied() && firePlaced;
        return new Check(
                "touch_fire_block_duration_places_fire",
                passed,
                "target=" + target
                        + ", firePos=" + firePos
                        + ", adjacentFire=" + firePlaced
                        + ", result=" + result.notes()
        );
    }

    private static ItemStack casterWithFocus(TCFocusPackageComponent packageData) {
        ItemCaster casterItem = (ItemCaster) TCItems.CASTER_BASIC.get();
        ItemStack caster = new ItemStack(casterItem);
        casterItem.setFocus(caster, focus(packageData));
        return caster;
    }

    private static ItemStack focus(TCFocusPackageComponent packageData) {
        ItemStack focus = new ItemStack(TCItems.FOCUS_1.get());
        ((ItemFocus) focus.getItem()).setPackage(focus, packageData);
        return focus;
    }

    private static TCFocusPackageComponent touchFirePackage(int duration) {
        return TCFocusPackageHelper.buildPackage(List.of(
                new TCFocusPackageHelper.NodeInstance(0, "ROOT", -1, List.of(1), Map.of()),
                new TCFocusPackageHelper.NodeInstance(1, "thaumcraft.TOUCH", 0, List.of(2), Map.of()),
                new TCFocusPackageHelper.NodeInstance(2, "thaumcraft.FIRE", 1, List.of(), Map.of("power", 1, "duration", duration))
        ));
    }

    private static TCFocusPackageComponent unsupportedFrostPackage() {
        return TCFocusPackageHelper.buildPackage(List.of(
                new TCFocusPackageHelper.NodeInstance(0, "ROOT", -1, List.of(1), Map.of()),
                new TCFocusPackageHelper.NodeInstance(1, "thaumcraft.TOUCH", 0, List.of(2), Map.of()),
                new TCFocusPackageHelper.NodeInstance(2, "thaumcraft.FROST", 1, List.of(), Map.of())
        ));
    }

    private static void moveAuditPlayer(ServerPlayer player) {
        player.moveTo(AUDIT_POS.getX() + 0.5D, AUDIT_POS.getY(), AUDIT_POS.getZ() + 0.5D, 0.0F, 0.0F);
        player.setYHeadRot(0.0F);
        player.setYBodyRot(0.0F);
    }

    private static void clearArea(ServerLevel level) {
        for (BlockPos pos : BlockPos.betweenClosed(AUDIT_POS.offset(-6, -2, -6), AUDIT_POS.offset(6, 4, 8))) {
            level.setBlock(pos, Blocks.AIR.defaultBlockState(), 3);
        }
    }

    public record Report(List<Check> checks) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
