package thaumcraft.common.lib;

import net.minecraft.block.SoundType;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent.Register;

public class SoundsTC {
   public static SoundEvent zap;
   public static SoundEvent heartbeat;
   public static SoundEvent spill;
   public static SoundEvent bubble;
   public static SoundEvent creak;
   public static SoundEvent squeek;
   public static SoundEvent jar;
   public static SoundEvent swarm;
   public static SoundEvent swarmattack;
   public static SoundEvent fly;
   public static SoundEvent key;
   public static SoundEvent ticks;
   public static SoundEvent clack;
   public static SoundEvent pump;
   public static SoundEvent poof;
   public static SoundEvent page;
   public static SoundEvent learn;
   public static SoundEvent write;
   public static SoundEvent erase;
   public static SoundEvent brain;
   public static SoundEvent crystal;
   public static SoundEvent wispdead;
   public static SoundEvent wisplive;
   public static SoundEvent wand;
   public static SoundEvent wandfail;
   public static SoundEvent rumble;
   public static SoundEvent ice;
   public static SoundEvent jacobs;
   public static SoundEvent hhoff;
   public static SoundEvent hhon;
   public static SoundEvent pech_idle;
   public static SoundEvent pech_trade;
   public static SoundEvent pech_dice;
   public static SoundEvent pech_hit;
   public static SoundEvent pech_death;
   public static SoundEvent pech_charge;
   public static SoundEvent shock;
   public static SoundEvent craftfail;
   public static SoundEvent scan;
   public static SoundEvent craftstart;
   public static SoundEvent runicShieldEffect;
   public static SoundEvent runicShieldCharge;
   public static SoundEvent wind;
   public static SoundEvent tool;
   public static SoundEvent gore;
   public static SoundEvent tentacle;
   public static SoundEvent upgrade;
   public static SoundEvent whispers;
   public static SoundEvent monolith;
   public static SoundEvent infuser;
   public static SoundEvent infuserstart;
   public static SoundEvent egidle;
   public static SoundEvent egattack;
   public static SoundEvent egdeath;
   public static SoundEvent egscreech;
   public static SoundEvent crabclaw;
   public static SoundEvent crabdeath;
   public static SoundEvent crabtalk;
   public static SoundEvent chant;
   public static SoundEvent coins;
   public static SoundEvent urnbreak;
   public static SoundEvent evilportal;
   public static SoundEvent grind;
   public static SoundEvent dust;
   public static SoundEvent pageturn;
   public static SoundType GORE;
   public static SoundType CRYSTAL;
   public static SoundType JAR;
   public static SoundType URN;

   public static void registerSoundTypes() {
      GORE = new SoundType(0.5F, 1.0F, gore, gore, gore, gore, gore);
      CRYSTAL = new SoundType(0.5F, 1.0F, crystal, crystal, crystal, crystal, crystal);
      JAR = new SoundType(0.5F, 1.0F, jar, jar, jar, jar, jar);
      URN = new SoundType(0.5F, 1.5F, urnbreak, urnbreak, urnbreak, urnbreak, urnbreak);
   }

   public static void registerSounds(Register<SoundEvent> event) {
      zap = getRegisteredSoundEvent(event, "thaumcraft:zap");
      heartbeat = getRegisteredSoundEvent(event, "thaumcraft:heartbeat");
      spill = getRegisteredSoundEvent(event, "thaumcraft:spill");
      bubble = getRegisteredSoundEvent(event, "thaumcraft:bubble");
      creak = getRegisteredSoundEvent(event, "thaumcraft:creak");
      squeek = getRegisteredSoundEvent(event, "thaumcraft:squeek");
      jar = getRegisteredSoundEvent(event, "thaumcraft:jar");
      swarm = getRegisteredSoundEvent(event, "thaumcraft:swarm");
      swarmattack = getRegisteredSoundEvent(event, "thaumcraft:swarmattack");
      fly = getRegisteredSoundEvent(event, "thaumcraft:fly");
      key = getRegisteredSoundEvent(event, "thaumcraft:key");
      ticks = getRegisteredSoundEvent(event, "thaumcraft:ticks");
      clack = getRegisteredSoundEvent(event, "thaumcraft:clack");
      pump = getRegisteredSoundEvent(event, "thaumcraft:pump");
      poof = getRegisteredSoundEvent(event, "thaumcraft:poof");
      page = getRegisteredSoundEvent(event, "thaumcraft:page");
      pageturn = getRegisteredSoundEvent(event, "thaumcraft:pageturn");
      learn = getRegisteredSoundEvent(event, "thaumcraft:learn");
      write = getRegisteredSoundEvent(event, "thaumcraft:write");
      erase = getRegisteredSoundEvent(event, "thaumcraft:erase");
      brain = getRegisteredSoundEvent(event, "thaumcraft:brain");
      crystal = getRegisteredSoundEvent(event, "thaumcraft:crystal");
      wispdead = getRegisteredSoundEvent(event, "thaumcraft:wispdead");
      wisplive = getRegisteredSoundEvent(event, "thaumcraft:wisplive");
      wand = getRegisteredSoundEvent(event, "thaumcraft:wand");
      wandfail = getRegisteredSoundEvent(event, "thaumcraft:wandfail");
      rumble = getRegisteredSoundEvent(event, "thaumcraft:rumble");
      ice = getRegisteredSoundEvent(event, "thaumcraft:ice");
      jacobs = getRegisteredSoundEvent(event, "thaumcraft:jacobs");
      hhoff = getRegisteredSoundEvent(event, "thaumcraft:hhoff");
      hhon = getRegisteredSoundEvent(event, "thaumcraft:hhon");
      pech_idle = getRegisteredSoundEvent(event, "thaumcraft:pech_idle");
      pech_trade = getRegisteredSoundEvent(event, "thaumcraft:pech_trade");
      pech_dice = getRegisteredSoundEvent(event, "thaumcraft:pech_dice");
      pech_hit = getRegisteredSoundEvent(event, "thaumcraft:pech_hit");
      pech_death = getRegisteredSoundEvent(event, "thaumcraft:pech_death");
      pech_charge = getRegisteredSoundEvent(event, "thaumcraft:pech_charge");
      shock = getRegisteredSoundEvent(event, "thaumcraft:shock");
      craftfail = getRegisteredSoundEvent(event, "thaumcraft:craftfail");
      scan = getRegisteredSoundEvent(event, "thaumcraft:scan");
      craftstart = getRegisteredSoundEvent(event, "thaumcraft:craftstart");
      runicShieldEffect = getRegisteredSoundEvent(event, "thaumcraft:runicshieldeffect");
      runicShieldCharge = getRegisteredSoundEvent(event, "thaumcraft:runicshieldcharge");
      wind = getRegisteredSoundEvent(event, "thaumcraft:wind");
      tool = getRegisteredSoundEvent(event, "thaumcraft:tool");
      gore = getRegisteredSoundEvent(event, "thaumcraft:gore");
      tentacle = getRegisteredSoundEvent(event, "thaumcraft:tentacle");
      upgrade = getRegisteredSoundEvent(event, "thaumcraft:upgrade");
      whispers = getRegisteredSoundEvent(event, "thaumcraft:whispers");
      monolith = getRegisteredSoundEvent(event, "thaumcraft:monolith");
      infuser = getRegisteredSoundEvent(event, "thaumcraft:infuser");
      infuserstart = getRegisteredSoundEvent(event, "thaumcraft:infuserstart");
      egidle = getRegisteredSoundEvent(event, "thaumcraft:egidle");
      egattack = getRegisteredSoundEvent(event, "thaumcraft:egattack");
      egdeath = getRegisteredSoundEvent(event, "thaumcraft:egdeath");
      egscreech = getRegisteredSoundEvent(event, "thaumcraft:egscreech");
      crabclaw = getRegisteredSoundEvent(event, "thaumcraft:crabclaw");
      crabdeath = getRegisteredSoundEvent(event, "thaumcraft:crabdeath");
      crabtalk = getRegisteredSoundEvent(event, "thaumcraft:crabtalk");
      chant = getRegisteredSoundEvent(event, "thaumcraft:chant");
      coins = getRegisteredSoundEvent(event, "thaumcraft:coins");
      urnbreak = getRegisteredSoundEvent(event, "thaumcraft:urnbreak");
      evilportal = getRegisteredSoundEvent(event, "thaumcraft:evilportal");
      grind = getRegisteredSoundEvent(event, "thaumcraft:grind");
      dust = getRegisteredSoundEvent(event, "thaumcraft:dust");
   }

   private static SoundEvent getRegisteredSoundEvent(Register<SoundEvent> event, String id) {
      SoundEvent soundevent = new SoundEvent(new ResourceLocation(id));
      soundevent.setRegistryName(new ResourceLocation(id));
      event.getRegistry().register(soundevent);
      return soundevent;
   }
}
