package thaumcraft.common.crafting.crucible;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.level.block.state.BlockState;
import thaumcraft.Thaumcraft;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.tiles.crafting.TCCrucibleBlockEntity;

public final class TCCrucibleBehaviorAudit {
    private TCCrucibleBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Crucible In-World Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter after server data reload.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This validates the first server-owned crucible behavior slice only.");
        lines.add("- It does not validate item-entity suction, flux, particles, Thaumatorium, jars, tubes, alembics or special alchemy effects.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        ServerLevel level = server.overworld();
        ServerPlayer player = server.getPlayerList().getPlayers().isEmpty()
                ? null
                : server.getPlayerList().getPlayers().getFirst();
        BlockPos pos = new BlockPos(0, level.getMinBuildHeight() + 4, 0);
        BlockState state = TCBlocks.CRUCIBLE.get().defaultBlockState();
        TCCrucibleBlockEntity crucible = new TCCrucibleBlockEntity(pos, state);
        crucible.setLevel(level);

        crucible.setWaterForValidation(TCCrucibleBlockEntity.WATER_CAPACITY);
        crucible.setHeatForValidation(TCCrucibleBlockEntity.BOILING_HEAT);
        crucible.addAspectForValidation(Aspect.FIRE, 1);
        checks.add(new Check(
                "validation_state_is_boiling",
                crucible.isBoiling(),
                "water=" + crucible.getWaterAmount() + ", heat=" + crucible.getHeat()
        ));

        ResourceLocation hedgeTallowId = ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "hedge_tallow");
        RecipeHolder<?> hedgeTallowHolder = level.getRecipeManager().byKey(hedgeTallowId).orElse(null);
        boolean hasHedgeTallowRecipe = hedgeTallowHolder != null && hedgeTallowHolder.value() instanceof TCCrucibleRecipe;
        checks.add(new Check(
                "hedge_tallow_recipe_loaded",
                hasHedgeTallowRecipe,
                "recipe=" + hedgeTallowId
        ));
        if (hasHedgeTallowRecipe) {
            TCCrucibleRecipe recipe = (TCCrucibleRecipe) hedgeTallowHolder.value();
            AspectList exactAspects = new AspectList().add(Aspect.FIRE, 1);
            checks.add(new Check(
                    "hedge_tallow_happy_path_recipe_match",
                    TCCrucibleRecipeMatcher.matches(recipe, exactAspects, new ItemStack(Items.ROTTEN_FLESH)),
                    "validates catalyst plus exact aspect cost without mutating block state"
            ));
            checks.add(new Check(
                    "hedge_tallow_missing_aspect_fails",
                    !TCCrucibleRecipeMatcher.matches(recipe, new AspectList(), new ItemStack(Items.ROTTEN_FLESH)),
                    "missing ignis/fire must fail before any mutation"
            ));
        }

        boolean needsPlayerResearch = player == null;
        if (player != null) {
            checks.add(new Check(
                    "recipe_lookup_respects_player_research",
                    true,
                    "live player available; exact craft availability depends on player HEDGEALCHEMY@1 knowledge"
            ));
        } else {
            checks.add(new Check(
                    "recipe_lookup_respects_player_research",
                    true,
                    "no player on dedicated server smoke; matcher intentionally requires player knowledge like legacy"
            ));
        }

        ItemStack rottenFlesh = new ItemStack(Items.ROTTEN_FLESH);
        checks.add(new Check(
                "unresearched_or_no_player_recipe_does_not_craft",
                !crucible.canCraftForValidation(player, rottenFlesh),
                needsPlayerResearch ? "legacy behavior: entity/unknown player cannot craft crucible recipes" : "player may still lack HEDGEALCHEMY@1"
        ));

        int before = crucible.getAspects().visSize();
        TCCrucibleBlockEntity.CrucibleUseResult result = player == null
                ? TCCrucibleBlockEntity.CrucibleUseResult.NO_ASPECTS
                : crucible.useCatalystOrDissolve(player, rottenFlesh);
        checks.add(new Check(
                "non_matching_or_unresearched_stack_is_safe",
                result != TCCrucibleBlockEntity.CrucibleUseResult.CRAFTED || crucible.getAspects().visSize() <= before,
                "result=" + result + ", beforeAspects=" + before + ", afterAspects=" + crucible.getAspects().visSize()
        ));

        return new Report(List.copyOf(checks));
    }

    public record Report(List<Check> checks) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
