package thaumcraft.common.items.equipment;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.UseAnim;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.neoforged.neoforge.common.util.FakePlayerFactory;
import thaumcraft.Thaumcraft;
import thaumcraft.api.items.IGoggles;
import thaumcraft.api.items.IRevealer;
import thaumcraft.api.items.IVisDiscountGear;
import thaumcraft.api.items.IWarpingGear;
import thaumcraft.common.crafting.arcane.TCArcaneRecipe;
import thaumcraft.common.items.armor.ItemRobeArmor;
import thaumcraft.common.items.armor.ItemVoidRobeArmor;
import thaumcraft.common.items.casters.CasterManager;
import thaumcraft.common.items.consumables.ItemSanitySoap;
import thaumcraft.common.items.curios.ItemCurioRites;
import thaumcraft.common.registry.TCDataComponents;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.warp.TCPlayerWarp;
import thaumcraft.common.warp.TCPlayerWarpStore;
import thaumcraft.common.warp.TCWarpType;

public final class TCItemEquipmentBehaviorAudit {
    private TCItemEquipmentBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Item / Equipment Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter after registry and data reload.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This validates server-side behavior contracts for already registered item/equipment ids.");
        lines.add("- It closes the legacy-safe bridge for goggles, cloth robes, void robes, sanity checker, sanity soap and Crimson Rites.");
        lines.add("- It intentionally does not validate final armor model geometry, Curios slot integration, caster focus behavior, recharge logic or bauble-specific movement/status effects.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        ServerPlayer player = FakePlayerFactory.getMinecraft(server.overworld());
        player.getInventory().clearContent();
        TCPlayerWarpStore.clear(player);

        checks.add(checkGoggles(player));
        checks.addAll(checkClothRobes(player));
        checks.addAll(checkVoidRobes(player));
        checks.add(checkSanityChecker());
        checks.add(checkSanitySoap(player));
        checks.addAll(checkCrimsonRites(player));
        checks.add(checkSanityCheckerRecipe(server));
        checks.add(checkEquipmentHelperBridge(player));

        return new Report(List.copyOf(checks));
    }

    private static Check checkGoggles(ServerPlayer player) {
        Item item = TCItems.GOGGLES.get();
        ItemStack stack = new ItemStack(item);
        boolean passed = item instanceof ArmorItem armor
                && armor.getType() == ArmorItem.Type.HELMET
                && item instanceof IVisDiscountGear discount
                && discount.getVisDiscount(stack, player) == 5
                && item instanceof IGoggles goggles
                && goggles.showIngamePopups(stack, player)
                && item instanceof IRevealer revealer
                && revealer.showNodes(stack, player)
                && stack.getMaxDamage() == 350
                && stack.getRarity() == Rarity.RARE
                && item.isValidRepairItem(stack, new ItemStack(TCItems.THAUMIUM_INGOT.get()));
        return new Check(
                "goggles_legacy_equipment_contract",
                passed,
                "helmet, 350 durability, rare, thaumium repair, 5% discount, goggles+revealer"
        );
    }

    private static List<Check> checkClothRobes(ServerPlayer player) {
        ArrayList<Check> checks = new ArrayList<>();
        checks.add(checkRobePiece("cloth_boots", TCItems.CLOTH_BOOTS.get(), ArmorItem.Type.BOOTS, 2, Rarity.UNCOMMON, TCItems.FABRIC.get(), player));
        checks.add(checkRobePiece("cloth_legs", TCItems.CLOTH_LEGS.get(), ArmorItem.Type.LEGGINGS, 3, Rarity.UNCOMMON, TCItems.FABRIC.get(), player));
        checks.add(checkRobePiece("cloth_chest", TCItems.CLOTH_CHEST.get(), ArmorItem.Type.CHESTPLATE, 3, Rarity.UNCOMMON, TCItems.FABRIC.get(), player));
        player.getInventory().armor.set(0, new ItemStack(TCItems.CLOTH_BOOTS.get()));
        player.getInventory().armor.set(1, new ItemStack(TCItems.CLOTH_LEGS.get()));
        player.getInventory().armor.set(2, new ItemStack(TCItems.CLOTH_CHEST.get()));
        checks.add(new Check(
                "cloth_robe_set_vis_discount_legacy_total",
                CasterManager.getTotalVisDiscountPercent(player) == 8,
                "legacy cloth set discount is boots 2 + legs 3 + chest 3"
        ));
        player.getInventory().clearContent();
        return checks;
    }

    private static List<Check> checkVoidRobes(ServerPlayer player) {
        ArrayList<Check> checks = new ArrayList<>();
        checks.add(checkVoidRobePiece("void_robe_helm", TCItems.VOID_ROBE_HELM.get(), ArmorItem.Type.HELMET, true, player));
        checks.add(checkVoidRobePiece("void_robe_chest", TCItems.VOID_ROBE_CHEST.get(), ArmorItem.Type.CHESTPLATE, false, player));
        checks.add(checkVoidRobePiece("void_robe_legs", TCItems.VOID_ROBE_LEGS.get(), ArmorItem.Type.LEGGINGS, false, player));
        player.getInventory().armor.set(1, new ItemStack(TCItems.VOID_ROBE_LEGS.get()));
        player.getInventory().armor.set(2, new ItemStack(TCItems.VOID_ROBE_CHEST.get()));
        player.getInventory().armor.set(3, new ItemStack(TCItems.VOID_ROBE_HELM.get()));
        checks.add(new Check(
                "void_robe_set_vis_discount_legacy_total",
                CasterManager.getTotalVisDiscountPercent(player) == 15,
                "legacy void robe set discount is 5 per registered piece"
        ));
        checks.add(new Check(
                "void_robe_set_warp_total",
                TCEquipmentHelper.getWarp(player) == 9,
                "legacy void robe pieces report 3 warp each"
        ));
        player.getInventory().clearContent();
        return checks;
    }

    private static Check checkRobePiece(String name, Item item, ArmorItem.Type type, int discount, Rarity rarity, Item repairItem, ServerPlayer player) {
        ItemStack stack = new ItemStack(item);
        boolean passed = item instanceof ItemRobeArmor armor
                && armor.getType() == type
                && armor.getVisDiscount(stack, player) == discount
                && stack.getRarity() == rarity
                && item.isValidRepairItem(stack, new ItemStack(repairItem));
        return new Check(name + "_legacy_contract", passed, "slot=" + type.getName() + ", discount=" + discount + ", repair=" + BuiltInRegistries.ITEM.getKey(repairItem));
    }

    private static Check checkVoidRobePiece(String name, Item item, ArmorItem.Type type, boolean reveals, ServerPlayer player) {
        ItemStack stack = new ItemStack(item);
        stack.setDamageValue(4);
        item.inventoryTick(stack, player.level(), player, 0, false);
        boolean passed = item instanceof ItemVoidRobeArmor armor
                && armor.getType() == type
                && armor.getVisDiscount(stack, player) == 5
                && armor.getWarp(stack, player) == 3
                && armor.showNodes(stack, player) == reveals
                && armor.showIngamePopups(stack, player) == reveals
                && stack.getRarity() == Rarity.EPIC
                && item.isValidRepairItem(stack, new ItemStack(TCItems.VOID_INGOT.get()))
                && stack.getDamageValue() == 3;
        return new Check(name + "_legacy_contract", passed, "slot=" + type.getName() + ", discount=5, warp=3, reveals=" + reveals + ", self_repair=1");
    }

    private static Check checkSanityChecker() {
        Item item = TCItems.SANITY_CHECKER.get();
        ItemStack stack = new ItemStack(item);
        boolean oldPlaceholderMissing = BuiltInRegistries.ITEM.getOptional(ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "sanitychecker")).isEmpty();
        boolean passed = item.getDefaultMaxStackSize() == 1
                && stack.getRarity() == Rarity.UNCOMMON
                && oldPlaceholderMissing;
        return new Check(
                "sanity_checker_identity_contract",
                passed,
                "modern item id is thaumcraft:sanity_checker; legacy page id sanitychecker stays recipe/page-only"
        );
    }

    private static Check checkSanitySoap(ServerPlayer player) {
        TCPlayerWarpStore.clear(player);
        TCPlayerWarpStore.add(player, TCWarpType.NORMAL, 3);
        TCPlayerWarpStore.add(player, TCWarpType.TEMPORARY, 4);
        Item item = TCItems.SANE_SOAP.get();
        ItemStack stack = new ItemStack(item, 2);
        boolean behavior = item instanceof ItemSanitySoap soap
                && soap.getUseDuration(stack, player) == ItemSanitySoap.USE_DURATION
                && soap.getUseAnimation(stack) == UseAnim.BLOCK
                && ItemSanitySoap.applyWarpCleansing(player);
        TCPlayerWarp after = TCPlayerWarpStore.get(player);
        boolean passed = behavior
                && after.get(TCWarpType.NORMAL) == 2
                && after.get(TCWarpType.TEMPORARY) == 0;
        TCPlayerWarpStore.clear(player);
        return new Check(
                "sane_soap_legacy_warp_cleansing_contract",
                passed,
                "after normal=" + after.get(TCWarpType.NORMAL) + ", temp=" + after.get(TCWarpType.TEMPORARY)
        );
    }

    private static List<Check> checkCrimsonRites(ServerPlayer player) {
        ArrayList<Check> checks = new ArrayList<>();
        TCPlayerWarpStore.clear(player);
        checks.add(new Check(
                "curio_rites_requires_actual_warp_over_20",
                !ItemCurioRites.canReadCrimsonRites(player),
                "actual warp 0 must fail like legacy"
        ));
        TCPlayerWarpStore.add(player, TCWarpType.NORMAL, 21);
        checks.add(new Check(
                "curio_rites_accepts_actual_warp_21",
                ItemCurioRites.canReadCrimsonRites(player),
                "legacy unlock gate is actual warp > 20"
        ));
        Item item = TCItems.CURIO_RITES.get();
        ItemStack stack = new ItemStack(item);
        checks.add(new Check(
                "curio_rites_item_identity_contract",
                item.getDefaultMaxStackSize() == 1
                        && stack.getRarity() == Rarity.UNCOMMON
                        && stack.has(TCDataComponents.LEGACY_ITEM.get()),
                "registered as thaumcraft:curio_rites with legacy curio/rites metadata component"
        ));
        TCPlayerWarpStore.clear(player);
        return checks;
    }

    private static Check checkSanityCheckerRecipe(MinecraftServer server) {
        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(Thaumcraft.MODID, "sanitychecker");
        RecipeHolder<?> holder = server.getRecipeManager().byKey(id).orElse(null);
        Item result = null;
        if (holder != null && holder.value() instanceof TCArcaneRecipe recipe) {
            result = recipe.getResultItem(server.registryAccess()).getItem();
        }
        return new Check(
                "sanitychecker_recipe_outputs_sanity_checker_item",
                result == TCItems.SANITY_CHECKER.get(),
                "recipe id remains thaumcraft:sanitychecker; output=" + (result == null ? "missing" : BuiltInRegistries.ITEM.getKey(result))
        );
    }

    private static Check checkEquipmentHelperBridge(ServerPlayer player) {
        player.getInventory().clearContent();
        player.getInventory().armor.set(3, new ItemStack(TCItems.GOGGLES.get()));
        boolean armorPath = TCEquipmentHelper.hasGoggles(player) && TCEquipmentHelper.hasRevealer(player);
        player.getInventory().clearContent();
        try (AutoCloseable ignored = TCEquipmentHelper.registerExtraEquipmentStackProvider(
                target -> target == player ? List.of(new ItemStack(TCItems.VOID_ROBE_HELM.get())) : List.of()
        )) {
            return new Check(
                    "equipment_helper_armor_and_extra_provider_paths",
                    armorPath && TCEquipmentHelper.hasGoggles(player) && TCEquipmentHelper.hasRevealer(player) && TCEquipmentHelper.getWarp(player) == 3,
                    "supports armor plus future accessory-provider bridge without hard dependency"
            );
        } catch (Exception exception) {
            return new Check("equipment_helper_armor_and_extra_provider_paths", false, exception.getMessage());
        }
    }

    public record Report(List<Check> checks) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
