package thaumcraft.common.runtime;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import thaumcraft.Thaumcraft;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.registry.TCItems;

public final class TCMinimalGameTestFixture {
    public static final String ENABLE_PROPERTY = "tc.minimalGameTestFixture";
    public static final String OUTPUT_PROPERTY = "tc.minimalGameTestFixturePath";

    private TCMinimalGameTestFixture() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);

        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Thaumcraft Minimal GameTest Fixture");
        lines.add("");
        lines.add("Generated by the opt-in scripted GameTest/runtime fixture after server startup.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL") + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- This is a minimal load/registry/runtime fixture, not a gameplay parity claim.");
        lines.add("- It proves that a dedicated server can reach ServerStartedEvent and resolve representative Thaumcraft registry entries.");
        lines.add("- It is intentionally opt-in through `" + ENABLE_PROPERTY + "` and halts the server after writing the report.");

        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        checks.add(new Check("server_started_event_received", server != null, "server=" + (server != null)));

        ServerLevel overworld = server == null ? null : server.overworld();
        checks.add(new Check(
                "overworld_available",
                overworld != null,
                overworld == null ? "overworld=null" : "dimension=" + overworld.dimension().location()
        ));

        checks.add(blockCheck("arcane_workbench_block_registered", TCBlocks.ARCANE_WORKBENCH.get(), "arcane_workbench"));
        checks.add(blockCheck("research_table_block_registered", TCBlocks.RESEARCH_TABLE.get(), "research_table"));
        checks.add(blockCheck("crucible_block_registered", TCBlocks.CRUCIBLE.get(), "crucible"));
        checks.add(itemCheck("thaumonomicon_item_registered", TCItems.THAUMONOMICON.get(), "thaumonomicon"));
        checks.add(itemCheck("thaumometer_item_registered", TCItems.THAUMOMETER.get(), "thaumometer"));

        return new Report(List.copyOf(checks));
    }

    private static Check blockCheck(String name, Block block, String expectedPath) {
        ResourceLocation id = BuiltInRegistries.BLOCK.getKey(block);
        boolean passed = id != null && Thaumcraft.MODID.equals(id.getNamespace()) && expectedPath.equals(id.getPath());
        return new Check(name, passed, "id=" + id + ", expected=" + Thaumcraft.MODID + ":" + expectedPath);
    }

    private static Check itemCheck(String name, Item item, String expectedPath) {
        ResourceLocation id = BuiltInRegistries.ITEM.getKey(item);
        boolean passed = id != null && Thaumcraft.MODID.equals(id.getNamespace()) && expectedPath.equals(id.getPath());
        return new Check(name, passed, "id=" + id + ", expected=" + Thaumcraft.MODID + ":" + expectedPath);
    }

    public record Report(List<Check> checks) {
        public int passed() {
            int passed = 0;
            for (Check check : checks) {
                if (check.passed()) {
                    passed++;
                }
            }
            return passed;
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
