package thaumcraft.common.essentia.transport;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.phys.AABB;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.neoforge.items.IItemHandler;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.common.blocks.essentia.TCEssentiaTransportBlock;
import thaumcraft.common.blocks.essentia.TCSmelterAuxBlock;
import thaumcraft.common.blocks.essentia.TCSmelterBlock;
import thaumcraft.common.blocks.essentia.TCSmelterVentBlock;
import thaumcraft.common.blocks.devices.TCMirrorBlock;
import thaumcraft.common.essentia.transport.block.TCLegacyTubeVariant;
import thaumcraft.common.essentia.transport.blockentity.TCLegacySmelterEndpointBlockEntity;
import thaumcraft.common.essentia.transport.blockentity.TCLegacyTubeBlockEntity;
import thaumcraft.common.items.TCMirrorBlockItem;
import thaumcraft.common.items.TCEssentiaItemHelper;
import thaumcraft.common.items.TCPhialItem;
import thaumcraft.common.items.TCWardedJarBlockItem;
import thaumcraft.common.registry.TCDataComponents;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.registry.TCBlockEntities;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.tiles.devices.TCMirrorEssentiaBlockEntity;
import thaumcraft.common.tiles.essentia.TCWardedJarBlockEntity;
import thaumcraft.common.tiles.essentia.TCAlembicBlockEntity;
import thaumcraft.common.tiles.essentia.TCSmelterBlockEntity;
import thaumcraft.common.tiles.essentia.TCEssentiaTransfuserBlockEntity;

/** Runtime checks for the legacy TileTube/TileJar transport contract. */
public final class TCEssentiaTransportBehaviorAudit {
    private TCEssentiaTransportBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);
        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Essentia Transport Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter against the ported TC6 transport contract.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL")
                    + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- Covers TC6 normal, buffer, filter, one-way, restrict and redstone-valve transport semantics.");
        lines.add("- Covers Warded Jar top-face suction and five-tick one-point transfer.");
        lines.add("- Covers smelter tier formulas, sided inventory, fuel data, Alembic-column routing, auxiliaries and vent attachment selection.");
        lines.add("- Covers Alembic/Jar label filters, phial/jar item transfer quanta and tube caster sub-part controls.");
        lines.add("- Covers Void Jar overflow/continuing suction and Essentia Mirror linked remote source semantics.");
        lines.add("- Covers Essentia Input/Output transfuser identity, sided capability, shapes and five-tick remote source transfer.");
        lines.add("- Bellows device behavior/rendering is covered by the dedicated Bellows audit; final pixel-level valve/vent visual parity still needs screenshot review.");
        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        checks.add(check("normal_tube_capacity_is_one", TCLegacyTubeVariant.TUBE.storageCapacity() == 1,
                "capacity=" + TCLegacyTubeVariant.TUBE.storageCapacity()));
        checks.add(check("buffer_capacity_is_ten", TCLegacyTubeVariant.BUFFER.storageCapacity() == 10,
                "capacity=" + TCLegacyTubeVariant.BUFFER.storageCapacity()));
        checks.add(check("restrict_minimum_suction_is_zero", TCEssentiaTubeMode.RESTRICT.minimumSuction() == 0,
                "minimum=" + TCEssentiaTubeMode.RESTRICT.minimumSuction()));
        checks.add(check("filter_minimum_suction_is_zero", TCEssentiaTubeMode.FILTER.minimumSuction() == 0,
                "minimum=" + TCEssentiaTubeMode.FILTER.minimumSuction()));

        ServerLevel level = server.overworld();
        BlockPos origin = new BlockPos(256, level.getMinBuildHeight() + 16, 256);
        clearArea(level, origin, 24);

        TCLegacyTubeBlockEntity normal = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        if (normal == null) {
            checks.add(check("runtime_tube_block_entities_created", false, "normal tube missing"));
            return new Report(List.copyOf(checks));
        }
        int normalFirst = normal.addEssentia(Aspect.AIR.getTag(), 64, Direction.UP, false);
        int normalSecond = normal.addEssentia(Aspect.FIRE.getTag(), 1, Direction.UP, false);
        checks.add(check("normal_tube_accepts_exactly_one_point", normalFirst == 1 && normalSecond == 0
                        && normal.transportNode().storage().totalAmount() == 1,
                "first=" + normalFirst + ", second=" + normalSecond
                        + ", stored=" + normal.transportNode().storage().totalAmount()));
        int normalTaken = normal.takeEssentia(Aspect.AIR.getTag(), 64, Direction.DOWN, false);
        checks.add(check("normal_tube_outputs_exactly_one_point", normalTaken == 1
                        && normal.transportNode().storage().totalAmount() == 0,
                "taken=" + normalTaken));
        normal.setSuctionForValidation(Aspect.AIR.getTag(), 23);
        normal.setVentingForValidation(3);
        TCLegacyTubeBlockEntity.serverTick(level, origin, normal.getBlockState(), normal);
        checks.add(check("venting_pauses_normal_suction_cycle",
                normal.ventingTicks() == 2 && normal.getSuction(Direction.NORTH).amount() == 23,
                "venting=" + normal.ventingTicks() + ", suction="
                        + normal.getSuction(Direction.NORTH).amount()));

        TCLegacyTubeBlockEntity buffer = placeTube(level, origin.offset(3, 0, 0), TCLegacyTubeVariant.BUFFER);
        if (buffer != null) {
            int bulk = buffer.addEssentia(Aspect.AIR.getTag(), 2, Direction.UP, false);
            int accepted = 0;
            for (int index = 0; index < 10; index++) {
                accepted += buffer.addEssentia(
                        index % 2 == 0 ? Aspect.AIR.getTag() : Aspect.FIRE.getTag(),
                        1,
                        Direction.UP,
                        false
                );
            }
            int overflow = buffer.addEssentia(Aspect.WATER.getTag(), 1, Direction.UP, false);
            checks.add(check("buffer_accepts_only_single_point_calls_up_to_ten", bulk == 0 && accepted == 10
                            && overflow == 0 && buffer.transportNode().storage().totalAmount() == 10,
                    "bulk=" + bulk + ", accepted=" + accepted + ", overflow=" + overflow));
            buffer.setBellowsForValidation(2);
            int openSuction = buffer.getSuction(Direction.NORTH).amount();
            buffer.setChokedSide(Direction.NORTH, 1);
            int reducedSuction = buffer.getSuction(Direction.NORTH).amount();
            buffer.setChokedSide(Direction.NORTH, 2);
            int closedSuction = buffer.getSuction(Direction.NORTH).amount();
            checks.add(check("buffer_choke_levels_match_legacy", openSuction == 64
                            && reducedSuction == 1 && closedSuction == 0,
                    "open=" + openSuction + ", reduced=" + reducedSuction + ", closed=" + closedSuction));
        } else {
            checks.add(check("runtime_buffer_block_entity_created", false, "buffer missing"));
        }

        addSuctionPropagationChecks(level, origin.offset(0, 0, 6), checks);
        addTransferChecks(level, origin.offset(0, 0, 12), checks);
        addSideAndValveChecks(level, origin.offset(8, 0, 0), checks);
        addJarChecks(level, origin.offset(8, 0, 10), checks);
        addVoidJarAndMirrorChecks(level, origin.offset(18, 0, -10), checks);
        addEssentiaTransfuserChecks(level, origin.offset(18, 0, 10), checks);
        addAlembicChecks(level, origin.offset(12, 0, 18), checks);
        addSmelterChecks(level, origin.offset(-12, 0, 18), checks);
        clearArea(level, origin, 24);
        return new Report(List.copyOf(checks));
    }

    private static void addSuctionPropagationChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        TCLegacyTubeBlockEntity demand = placeTube(level, origin.east(), TCLegacyTubeVariant.TUBE);
        TCLegacyTubeBlockEntity normal = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        if (demand == null || normal == null) {
            checks.add(check("runtime_suction_fixture_created", false, "missing normal tube"));
            return;
        }
        demand.setSuctionForValidation(Aspect.AIR.getTag(), 32);
        normal.recalculateSuctionForValidation();
        checks.add(check("normal_tube_attenuates_suction_by_one",
                normal.getSuction(Direction.EAST).amount() == 31
                        && Aspect.AIR.getTag().equals(normal.getSuction(Direction.EAST).aspect()),
                "suction=" + normal.getSuction(Direction.EAST).amount()));

        level.removeBlock(origin, false);
        TCLegacyTubeBlockEntity restrict = placeTube(level, origin, TCLegacyTubeVariant.RESTRICT);
        if (restrict != null) {
            restrict.recalculateSuctionForValidation();
            checks.add(check("restrict_tube_halves_upstream_suction",
                    restrict.getSuction(Direction.EAST).amount() == 16,
                    "suction=" + restrict.getSuction(Direction.EAST).amount()));
        }

        level.removeBlock(origin, false);
        TCLegacyTubeBlockEntity filter = placeTube(level, origin, TCLegacyTubeVariant.FILTER);
        if (filter != null) {
            filter.setFilterAspect(Aspect.FIRE.getTag());
            filter.recalculateSuctionForValidation();
            int mismatch = filter.getSuction(Direction.EAST).amount();
            filter.setFilterAspect(Aspect.AIR.getTag());
            filter.recalculateSuctionForValidation();
            checks.add(check("filter_tube_propagates_only_matching_suction",
                    mismatch == 0 && filter.getSuction(Direction.EAST).amount() == 31,
                    "mismatch=" + mismatch + ", match=" + filter.getSuction(Direction.EAST).amount()));
        }

        level.removeBlock(origin, false);
        level.removeBlock(origin.east(), false);
        TCLegacyTubeBlockEntity oneWay = placeTube(level, origin, TCLegacyTubeVariant.ONEWAY);
        TCLegacyTubeBlockEntity southDemand = placeTube(level, origin.south(), TCLegacyTubeVariant.TUBE);
        if (oneWay != null && southDemand != null) {
            oneWay.setFacing(Direction.NORTH);
            southDemand.setSuctionForValidation(Aspect.AIR.getTag(), 32);
            oneWay.recalculateSuctionForValidation();
            int allowed = oneWay.getSuction(Direction.SOUTH).amount();
            level.removeBlock(origin.south(), false);
            TCLegacyTubeBlockEntity northDemand = placeTube(level, origin.north(), TCLegacyTubeVariant.TUBE);
            if (northDemand != null) {
                northDemand.setSuctionForValidation(Aspect.AIR.getTag(), 32);
                oneWay.recalculateSuctionForValidation();
            }
            checks.add(check("oneway_suction_uses_legacy_facing_side", allowed == 31
                            && oneWay.getSuction(Direction.NORTH).amount() == 0,
                    "allowed=" + allowed + ", blocked=" + oneWay.getSuction(Direction.NORTH).amount()));
        }
    }

    private static void addTransferChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        TCLegacyTubeBlockEntity source = placeTube(level, origin.west(), TCLegacyTubeVariant.TUBE);
        TCLegacyTubeBlockEntity target = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        if (source == null || target == null) {
            checks.add(check("runtime_transfer_fixture_created", false, "missing tube"));
            return;
        }
        source.addEssentia(Aspect.AIR.getTag(), 1, Direction.WEST, false);
        target.setSuctionForValidation(Aspect.AIR.getTag(), 32);
        target.equalizeForValidation();
        checks.add(check("normal_tube_moves_one_point_toward_stronger_suction",
                source.transportNode().storage().totalAmount() == 0
                        && target.transportNode().storage().amount(Aspect.AIR.getTag()) == 1,
                "source=" + source.transportNode().storage().totalAmount()
                        + ", target=" + target.transportNode().storage().totalAmount()));
    }

    private static void addSideAndValveChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        TCLegacyTubeBlockEntity left = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        TCLegacyTubeBlockEntity right = placeTube(level, origin.east(), TCLegacyTubeVariant.TUBE);
        if (left != null && right != null) {
            left.refreshConnectionState();
            right.refreshConnectionState();
            checks.add(check("tube_blockstate_tracks_capability_connections",
                    left.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                            && right.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST),
                    "leftEast=" + left.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                            + ", rightWest=" + right.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST)));
            left.setSideOpen(Direction.EAST, false);
            left.refreshConnectionState();
            right.refreshConnectionState();
            checks.add(check("tube_side_closure_is_reciprocal", !left.isSideOpen(Direction.EAST)
                            && !right.isSideOpen(Direction.WEST)
                            && !left.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                            && !right.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST),
                    "left=" + left.isSideOpen(Direction.EAST) + ", right=" + right.isSideOpen(Direction.WEST)));
            TCEssentiaTransport closedCapability = level.getCapability(
                    TCEssentiaCapabilities.BLOCK,
                    origin,
                    Direction.EAST
            );
            TCEssentiaTransport openCapability = level.getCapability(
                    TCEssentiaCapabilities.BLOCK,
                    origin,
                    Direction.NORTH
            );
            checks.add(check("sided_neoforge_capability_respects_open_sides",
                    closedCapability == null && openCapability == left,
                    "closed=" + (closedCapability != null) + ", open=" + (openCapability != null)));
            CompoundTag update = left.getUpdateTag(level.registryAccess());
            checks.add(check("tube_sync_tag_contains_directional_state",
                    update.contains("OpenSides") && update.contains("Facing")
                            && update.contains("SuctionAmount") && update.contains("FilterAspect"),
                    "keys=" + update.getAllKeys()));

            TCLegacyTubeBlockEntity persisted = TCBlockEntities.createTubeBlockEntity(
                    TCLegacyTubeVariant.FILTER,
                    origin.offset(0, 1, 0),
                    TCBlocks.TUBE_FILTER.get().defaultBlockState()
            );
            persisted.setFacing(Direction.UP);
            persisted.setSideOpen(Direction.SOUTH, false);
            persisted.setFilterAspect(Aspect.FIRE.getTag());
            persisted.setSuctionForValidation(Aspect.FIRE.getTag(), 23);
            persisted.addEssentia(Aspect.FIRE.getTag(), 1, Direction.NORTH, false);
            CompoundTag persistedTag = persisted.getUpdateTag(level.registryAccess());
            TCLegacyTubeBlockEntity restored = TCBlockEntities.createTubeBlockEntity(
                    TCLegacyTubeVariant.FILTER,
                    origin.offset(0, 2, 0),
                    TCBlocks.TUBE_FILTER.get().defaultBlockState()
            );
            restored.handleUpdateTag(persistedTag, level.registryAccess());
            checks.add(check("tube_nbt_round_trip_preserves_transport_state",
                    restored.facing() == Direction.UP
                            && !restored.isSideOpen(Direction.SOUTH)
                            && Aspect.FIRE.getTag().equals(restored.filterAspect())
                            && restored.getSuction(Direction.NORTH).amount() == 23
                            && restored.transportNode().storage().amount(Aspect.FIRE.getTag()) == 1,
                    "facing=" + restored.facing() + ", filter=" + restored.filterAspect()
                            + ", suction=" + restored.getSuction(Direction.NORTH).amount()
                            + ", stored=" + restored.transportNode().storage().totalAmount()));
        }

        BlockPos casterPairPos = origin.offset(3, 0, 0);
        TCLegacyTubeBlockEntity casterLeft = placeTube(level, casterPairPos, TCLegacyTubeVariant.TUBE);
        TCLegacyTubeBlockEntity casterRight = placeTube(level, casterPairPos.east(), TCLegacyTubeVariant.TUBE);
        if (casterLeft != null && casterRight != null) {
            casterLeft.refreshConnectionState();
            casterRight.refreshConnectionState();
            boolean initiallyConnected = casterLeft.isSideOpen(Direction.EAST)
                    && casterRight.isSideOpen(Direction.WEST)
                    && casterLeft.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                    && casterRight.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST);
            casterLeft.casterToggleSide(Direction.EAST, false);
            boolean closedByCaster = !casterLeft.isSideOpen(Direction.EAST)
                    && !casterRight.isSideOpen(Direction.WEST)
                    && !casterLeft.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                    && !casterRight.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST);
            casterLeft.casterToggleSide(Direction.EAST, false);
            boolean reopenedByCaster = casterLeft.isSideOpen(Direction.EAST)
                    && casterRight.isSideOpen(Direction.WEST)
                    && casterLeft.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                    && casterRight.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST);
            checks.add(check("caster_side_subhit_toggles_tube_connection_pair",
                    initiallyConnected && closedByCaster && reopenedByCaster,
                    "initial=" + initiallyConnected + ", closed=" + closedByCaster
                            + ", reopened=" + reopenedByCaster));
        }

        TCLegacyTubeBlockEntity casterBuffer = placeTube(level, origin.offset(6, 0, 0), TCLegacyTubeVariant.BUFFER);
        if (casterBuffer != null) {
            casterBuffer.casterToggleSide(Direction.NORTH, true);
            int chokeOne = casterBuffer.chokedSide(Direction.NORTH);
            casterBuffer.casterToggleSide(Direction.NORTH, true);
            int chokeTwo = casterBuffer.chokedSide(Direction.NORTH);
            casterBuffer.casterToggleSide(Direction.NORTH, true);
            int chokeReset = casterBuffer.chokedSide(Direction.NORTH);
            checks.add(check("caster_sneak_side_subhit_cycles_buffer_choke",
                    chokeOne == 1 && chokeTwo == 2 && chokeReset == 0,
                    "cycle=" + chokeOne + ">" + chokeTwo + ">" + chokeReset));
        }

        BlockPos casterRotatePos = origin.offset(9, 0, 0);
        TCLegacyTubeBlockEntity casterOneWay = placeTube(level, casterRotatePos, TCLegacyTubeVariant.ONEWAY);
        placeTube(level, casterRotatePos.north(), TCLegacyTubeVariant.TUBE);
        if (casterOneWay != null) {
            casterOneWay.setFacing(Direction.NORTH);
            boolean rotated = casterOneWay.casterRotateCenter();
            checks.add(check("caster_center_subhit_rotates_directional_tube_to_connectable_side",
                    rotated && casterOneWay.facing() == Direction.SOUTH,
                    "rotated=" + rotated + ", facing=" + casterOneWay.facing()));
        }

        BlockPos valvePos = origin.offset(0, 0, 3);
        TCLegacyTubeBlockEntity valve = placeTube(level, valvePos, TCLegacyTubeVariant.VALVE);
        if (valve != null) {
            valve.setFacing(Direction.NORTH);
            boolean faceRule = !valve.isConnectable(Direction.NORTH) && valve.isConnectable(Direction.SOUTH);
            level.setBlock(valvePos.east(), Blocks.REDSTONE_BLOCK.defaultBlockState(), 3);
            TCLegacyTubeBlockEntity.serverTick(level, valvePos, valve.getBlockState(), valve);
            checks.add(check("valve_excludes_handle_face_and_closes_when_powered",
                    faceRule && !valve.allowsFlow() && valve.getSuction(Direction.SOUTH).amount() == 0,
                    "faceRule=" + faceRule + ", flow=" + valve.allowsFlow()));
        }

        TCLegacyTubeBlockEntity manualValve = placeTube(level, origin.offset(3, 0, 3), TCLegacyTubeVariant.VALVE);
        if (manualValve != null) {
            manualValve.setFacing(Direction.NORTH);
            manualValve.setSuctionForValidation(Aspect.AIR.getTag(), 32);
            manualValve.setAllowFlow(false);
            CompoundTag closedTag = manualValve.getUpdateTag(level.registryAccess());
            boolean closed = !manualValve.allowsFlow()
                    && manualValve.getSuction(Direction.SOUTH).amount() == 0
                    && closedTag.contains("AllowFlow")
                    && !closedTag.getBoolean("AllowFlow");
            manualValve.setAllowFlow(true);
            manualValve.setVentingForValidation(7);
            CompoundTag openedTag = manualValve.getUpdateTag(level.registryAccess());
            TCLegacyTubeBlockEntity restoredValve = TCBlockEntities.createTubeBlockEntity(
                    TCLegacyTubeVariant.VALVE,
                    origin.offset(3, 1, 3),
                    TCBlocks.TUBE_VALVE.get().defaultBlockState()
            );
            restoredValve.handleUpdateTag(openedTag, level.registryAccess());
            checks.add(check("manual_valve_toggle_and_vent_state_sync",
                    closed
                            && manualValve.allowsFlow()
                            && openedTag.getBoolean("AllowFlow")
                            && openedTag.getInt("Venting") == 7
                            && restoredValve.allowsFlow()
                            && restoredValve.ventingTicks() == 7,
                    "closed=" + closed + ", reopened=" + manualValve.allowsFlow()
                            + ", venting=" + restoredValve.ventingTicks()));
        }
    }


    private static void addAlembicChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        level.setBlock(origin, TCBlocks.ALEMBIC.get().defaultBlockState(), 3);
        TCAlembicBlockEntity alembic = blockEntity(level, origin, TCAlembicBlockEntity.class);
        checks.add(check("runtime_alembic_block_entity_created", alembic != null, "alembic=" + (alembic != null)));
        if (alembic == null) {
            return;
        }

        int overflow = alembic.addToContainer(Aspect.AIR, 200);
        int mixedRemainder = alembic.addToContainer(Aspect.FIRE, 1);
        checks.add(check("alembic_stores_single_aspect_up_to_128", overflow == 72
                        && mixedRemainder == 1
                        && alembic.storedAmount() == 128
                        && alembic.storedAspect() == Aspect.AIR,
                "overflow=" + overflow + ", mixed=" + mixedRemainder + ", amount=" + alembic.storedAmount()));

        checks.add(check("unlabelled_alembic_outputs_on_all_horizontal_faces", !alembic.canInputFrom(Direction.UP)
                        && !alembic.canOutputTo(Direction.DOWN)
                        && alembic.canOutputTo(Direction.NORTH)
                        && alembic.canOutputTo(Direction.EAST),
                "upInput=" + alembic.canInputFrom(Direction.UP)
                        + ", downOutput=" + alembic.canOutputTo(Direction.DOWN)
                        + ", northOutput=" + alembic.canOutputTo(Direction.NORTH)
                        + ", eastOutput=" + alembic.canOutputTo(Direction.EAST)));

        int simulated = alembic.takeEssentia(Aspect.AIR.getTag(), 64, Direction.EAST, true);
        int taken = alembic.takeEssentia(Aspect.AIR.getTag(), 64, Direction.EAST, false);
        int blocked = alembic.takeEssentia(Aspect.AIR.getTag(), 1, Direction.DOWN, false);
        checks.add(check("alembic_outputs_requested_aspect_from_valid_side", simulated == 64
                        && taken == 64
                        && blocked == 0
                        && alembic.storedAmount() == 64,
                "simulated=" + simulated + ", taken=" + taken + ", blocked=" + blocked
                        + ", remaining=" + alembic.storedAmount()));

        alembic.setStoredForValidation(null, 0);
        alembic.setFilterForValidation(Aspect.FIRE, Direction.NORTH);
        int rejected = alembic.addToContainer(Aspect.AIR, 1);
        int accepted = alembic.addToContainer(Aspect.FIRE, 1);
        checks.add(check("alembic_filter_accepts_only_matching_aspect", rejected == 1
                        && accepted == 0
                        && alembic.storedAspect() == Aspect.FIRE
                        && alembic.storedAmount() == 1
                        && !alembic.canOutputTo(Direction.NORTH)
                        && alembic.canOutputTo(Direction.EAST),
                "rejected=" + rejected + ", accepted=" + accepted + ", amount=" + alembic.storedAmount()));

        CompoundTag labelTag = alembic.getUpdateTag(level.registryAccess());
        TCAlembicBlockEntity restoredAlembic = new TCAlembicBlockEntity(
                origin.offset(0, 1, 0),
                TCBlocks.ALEMBIC.get().defaultBlockState()
        );
        restoredAlembic.handleUpdateTag(labelTag, level.registryAccess());
        checks.add(check("alembic_label_filter_sync_preserves_filter_and_blocked_face",
                restoredAlembic.aspectFilter() == Aspect.FIRE
                        && restoredAlembic.labelFacing() == Direction.NORTH
                        && !restoredAlembic.canOutputTo(Direction.NORTH)
                        && restoredAlembic.canOutputTo(Direction.EAST),
                "filter=" + restoredAlembic.aspectFilter() + ", facing=" + restoredAlembic.labelFacing()));

        alembic.setStoredForValidation(Aspect.AIR, TCPhialItem.BASE_AMOUNT);
        boolean phialQuantum = alembic.takeFromContainer(Aspect.AIR, TCPhialItem.BASE_AMOUNT);
        checks.add(check("empty_phial_extracts_exactly_ten_from_alembic",
                phialQuantum && alembic.storedAmount() == 0 && alembic.storedAspect() == null,
                "drained=" + phialQuantum + ", remaining=" + alembic.storedAmount()));
    }

    private static void addSmelterChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        BlockState basicState = TCBlocks.SMELTER_BASIC.get().defaultBlockState()
                .setValue(TCSmelterBlock.FACING, Direction.NORTH);
        level.setBlock(origin, basicState, 3);
        TCSmelterBlockEntity smelter = blockEntity(level, origin, TCSmelterBlockEntity.class);
        checks.add(check("runtime_basic_smelter_created", smelter != null,
                "smelter=" + (smelter != null)));
        if (smelter == null) {
            return;
        }

        checks.add(check("smelter_tier_formulas_match_legacy",
                TCSmelterBlockEntity.efficiencyForType(TCSmelterBlockEntity.SmelterType.BASIC) == 0.8F
                        && TCSmelterBlockEntity.efficiencyForType(TCSmelterBlockEntity.SmelterType.THAUMIUM) == 0.9F
                        && TCSmelterBlockEntity.efficiencyForType(TCSmelterBlockEntity.SmelterType.VOID) == 0.95F
                        && TCSmelterBlockEntity.speedForType(TCSmelterBlockEntity.SmelterType.BASIC) == 15
                        && TCSmelterBlockEntity.speedForType(TCSmelterBlockEntity.SmelterType.THAUMIUM) == 10
                        && TCSmelterBlockEntity.speedForType(TCSmelterBlockEntity.SmelterType.VOID) == 15
                        && TCSmelterBlockEntity.outputInterval(TCSmelterBlockEntity.SmelterType.BASIC, true) == 12,
                "basic=80%/15, thaumium=90%/10, void=95%/15, alumentumBasic=12"));

        int alumentumBurn = TCSmelterBlockEntity.getBurnTime(new ItemStack(TCItems.ALUMENTUM.get()));
        int greatwoodBurn = TCSmelterBlockEntity.getBurnTime(new ItemStack(TCBlocks.LOG_GREATWOOD.get()));
        int silverwoodBurn = TCSmelterBlockEntity.getBurnTime(new ItemStack(TCBlocks.LOG_SILVERWOOD.get()));
        checks.add(check("legacy_thaumcraft_fuels_are_data_driven",
                alumentumBurn == 4800 && greatwoodBurn == 500 && silverwoodBurn == 400,
                "alumentum=" + alumentumBurn + ", greatwood=" + greatwoodBurn
                        + ", silverwood=" + silverwoodBurn));

        IItemHandler side = level.getCapability(Capabilities.ItemHandler.BLOCK, origin, Direction.EAST);
        IItemHandler bottom = level.getCapability(Capabilities.ItemHandler.BLOCK, origin, Direction.DOWN);
        IItemHandler top = level.getCapability(Capabilities.ItemHandler.BLOCK, origin, Direction.UP);
        boolean capabilityShape = side != null && side.getSlots() == 1
                && bottom != null && bottom.getSlots() == 1
                && top != null && top.getSlots() == 0;
        if (capabilityShape) {
            side.insertItem(0, new ItemStack(Items.COBBLESTONE), false);
            bottom.insertItem(0, new ItemStack(TCItems.ALUMENTUM.get()), false);
        }
        checks.add(check("smelter_sided_item_capability_matches_legacy_slots",
                capabilityShape
                        && smelter.getStoredItem(TCSmelterBlockEntity.SLOT_INPUT).is(Items.COBBLESTONE)
                        && smelter.getStoredItem(TCSmelterBlockEntity.SLOT_FUEL).is(TCItems.ALUMENTUM.get()),
                "sideSlots=" + (side == null ? -1 : side.getSlots())
                        + ", bottomSlots=" + (bottom == null ? -1 : bottom.getSlots())
                        + ", topSlots=" + (top == null ? -1 : top.getSlots())));
        checks.add(check("smelter_is_not_an_essentia_transport_endpoint",
                level.getCapability(TCEssentiaCapabilities.BLOCK, origin, Direction.UP) == null,
                "transportCapability=false"));

        TCSmelterBlockEntity.serverTick(level, origin, smelter.getBlockState(), smelter);
        checks.add(check("alumentum_starts_legacy_burn_and_speed_boost",
                smelter.furnaceBurnTime() == 4800
                        && smelter.currentItemBurnTime() == 4800
                        && smelter.speedBoost(),
                "burn=" + smelter.furnaceBurnTime() + ", boost=" + smelter.speedBoost()));

        smelter.setStoredItemForValidation(TCSmelterBlockEntity.SLOT_INPUT, ItemStack.EMPTY);
        smelter.setStoredAspectsForValidation(new AspectList().add(Aspect.AIR, 2));

        BlockPos firstAlembicPos = origin.above();
        BlockPos matchingAlembicPos = origin.above(2);
        level.setBlock(firstAlembicPos, TCBlocks.ALEMBIC.get().defaultBlockState(), 3);
        level.setBlock(matchingAlembicPos, TCBlocks.ALEMBIC.get().defaultBlockState(), 3);
        TCAlembicBlockEntity firstAlembic = blockEntity(level, firstAlembicPos, TCAlembicBlockEntity.class);
        TCAlembicBlockEntity matchingAlembic = blockEntity(level, matchingAlembicPos, TCAlembicBlockEntity.class);
        if (matchingAlembic != null) {
            matchingAlembic.setStoredForValidation(Aspect.AIR, 10);
        }

        BlockPos auxPos = origin.east();
        level.setBlock(auxPos, TCBlocks.SMELTER_AUX.get().defaultBlockState()
                .setValue(TCSmelterAuxBlock.FACING, Direction.WEST), 3);
        level.setBlock(auxPos.above(), TCBlocks.ALEMBIC.get().defaultBlockState(), 3);
        TCAlembicBlockEntity auxAlembic = blockEntity(level, auxPos.above(), TCAlembicBlockEntity.class);
        smelter.setTransferTicksForValidation(
                TCSmelterBlockEntity.outputInterval(smelter.smelterType(), smelter.speedBoost())
        );
        boolean output = smelter.outputBufferedEssentiaForValidation();
        checks.add(check("smelter_outputs_direct_and_each_valid_aux_per_cycle",
                output
                        && smelter.storedVis() == 0
                        && firstAlembic != null && firstAlembic.storedAmount() == 0
                        && matchingAlembic != null && matchingAlembic.storedAmount() == 11
                        && auxAlembic != null && auxAlembic.storedAmount() == 1,
                "smelter=" + smelter.storedVis()
                        + ", first=" + (firstAlembic == null ? -1 : firstAlembic.storedAmount())
                        + ", matching=" + (matchingAlembic == null ? -1 : matchingAlembic.storedAmount())
                        + ", aux=" + (auxAlembic == null ? -1 : auxAlembic.storedAmount())));

        level.setBlock(origin.west(), TCBlocks.SMELTER_VENT.get().defaultBlockState()
                .setValue(TCSmelterVentBlock.FACING, Direction.EAST), 3);
        level.setBlock(origin.south(), TCBlocks.SMELTER_VENT.get().defaultBlockState()
                .setValue(TCSmelterVentBlock.FACING, Direction.NORTH), 3);
        level.setBlock(origin.north(), TCBlocks.SMELTER_VENT.get().defaultBlockState()
                .setValue(TCSmelterVentBlock.FACING, Direction.SOUTH), 3);
        checks.add(check("vent_selection_excludes_smelter_front_and_stacks_probability",
                smelter.validVentCountForValidation() == 2
                        && Math.abs(TCSmelterBlockEntity.ventMitigationChance(1) - 0.333D) < 0.0001D
                        && TCSmelterBlockEntity.ventMitigationChance(2)
                        > TCSmelterBlockEntity.ventMitigationChance(1),
                "validVents=" + smelter.validVentCountForValidation()
                        + ", p1=" + TCSmelterBlockEntity.ventMitigationChance(1)
                        + ", p2=" + TCSmelterBlockEntity.ventMitigationChance(2)));

        BlockPos thaumiumPos = origin.offset(5, 0, 0);
        BlockPos voidPos = origin.offset(7, 0, 0);
        level.setBlock(thaumiumPos, TCBlocks.SMELTER_THAUMIUM.get().defaultBlockState(), 3);
        level.setBlock(voidPos, TCBlocks.SMELTER_VOID.get().defaultBlockState(), 3);
        TCLegacySmelterEndpointBlockEntity thaumium =
                blockEntity(level, thaumiumPos, TCLegacySmelterEndpointBlockEntity.class);
        TCLegacySmelterEndpointBlockEntity voidSmelter =
                blockEntity(level, voidPos, TCLegacySmelterEndpointBlockEntity.class);
        checks.add(check("upgraded_smelters_use_shared_machine_model_with_exact_tiers",
                thaumium != null && thaumium.smelterType() == TCSmelterBlockEntity.SmelterType.THAUMIUM
                        && voidSmelter != null && voidSmelter.smelterType() == TCSmelterBlockEntity.SmelterType.VOID,
                "thaumium=" + (thaumium == null ? "missing" : thaumium.smelterType())
                        + ", void=" + (voidSmelter == null ? "missing" : voidSmelter.smelterType())));
    }
    private static void addJarChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        level.setBlock(origin, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        TCLegacyTubeBlockEntity buffer = placeTube(level, origin.above(), TCLegacyTubeVariant.BUFFER);
        TCWardedJarBlockEntity jar = blockEntity(level, origin, TCWardedJarBlockEntity.class);
        if (jar == null || buffer == null) {
            checks.add(check("runtime_jar_fixture_created", false, "missing jar or buffer"));
            return;
        }
        buffer.addEssentia(Aspect.AIR.getTag(), 1, Direction.UP, false);
        buffer.addEssentia(Aspect.AIR.getTag(), 1, Direction.UP, false);
        for (int tick = 0; tick < 4; tick++) {
            TCWardedJarBlockEntity.serverTick(level, origin, jar.getBlockState(), jar);
        }
        boolean unchangedBeforeFifth = jar.storedAmount() == 0;
        TCWardedJarBlockEntity.serverTick(level, origin, jar.getBlockState(), jar);
        checks.add(check("warded_jar_pulls_one_point_every_five_ticks", unchangedBeforeFifth
                        && jar.storedAspect() == Aspect.AIR && jar.storedAmount() == 1
                        && buffer.transportNode().storage().amount(Aspect.AIR.getTag()) == 1,
                "jar=" + jar.storedAmount() + ", buffer="
                        + buffer.transportNode().storage().amount(Aspect.AIR.getTag())));
        int allOrNothing = jar.takeEssentia(Aspect.AIR.getTag(), 2, Direction.UP, false);
        checks.add(check("warded_jar_transport_take_is_all_or_nothing", allOrNothing == 0 && jar.storedAmount() == 1,
                "taken=" + allOrNothing + ", remaining=" + jar.storedAmount()));
        jar.setFilterForValidation(Aspect.FIRE);
        checks.add(check("filtered_warded_jar_has_legacy_suction",
                jar.getMinimumSuction() == 64 && jar.getSuction(Direction.UP).amount() == 64
                        && Aspect.FIRE.getTag().equals(jar.getSuction(Direction.UP).aspect()),
                "minimum=" + jar.getMinimumSuction() + ", suction=" + jar.getSuction(Direction.UP).amount()));

        jar.setFilter(null);
        jar.setStoredForValidation(Aspect.AIR, TCPhialItem.BASE_AMOUNT * 2);
        boolean phialDrain = jar.takeFromContainer(Aspect.AIR, TCPhialItem.BASE_AMOUNT);
        int mixedRemainder = jar.addToContainer(Aspect.FIRE, TCPhialItem.BASE_AMOUNT);
        checks.add(check("warded_jar_phial_quantum_and_single_aspect_rule",
                phialDrain
                        && jar.storedAspect() == Aspect.AIR
                        && jar.storedAmount() == TCPhialItem.BASE_AMOUNT
                        && mixedRemainder == TCPhialItem.BASE_AMOUNT,
                "drained=" + phialDrain + ", aspect=" + jar.storedAspect()
                        + ", amount=" + jar.storedAmount() + ", mixedRemainder=" + mixedRemainder));

        jar.setStoredForValidation(null, 0);
        jar.setFilter(Aspect.FIRE, Direction.WEST);
        int rejected = jar.addToContainer(Aspect.AIR, TCPhialItem.BASE_AMOUNT);
        int accepted = jar.addToContainer(Aspect.FIRE, TCPhialItem.BASE_AMOUNT);
        ItemStack carriedJar = TCWardedJarBlockItem.stackFromJar(jar);
        checks.add(check("warded_jar_label_filter_and_item_stack_components_match_legacy",
                rejected == TCPhialItem.BASE_AMOUNT
                        && accepted == 0
                        && jar.aspectFilter() == Aspect.FIRE
                        && jar.labelFacing() == Direction.WEST
                        && carriedJar.is(TCItems.JAR_NORMAL.get())
                        && TCEssentiaItemHelper.aspectFromStack(carriedJar) == Aspect.FIRE
                        && TCEssentiaItemHelper.aspectAmount(carriedJar) == TCPhialItem.BASE_AMOUNT
                        && TCEssentiaItemHelper.filterAspect(carriedJar) == Aspect.FIRE,
                "rejected=" + rejected + ", accepted=" + accepted + ", facing=" + jar.labelFacing()
                        + ", stackAspect=" + TCEssentiaItemHelper.aspectFromStack(carriedJar)
                        + ", stackAmount=" + TCEssentiaItemHelper.aspectAmount(carriedJar)));

        CompoundTag tag = jar.getUpdateTag(level.registryAccess());
        TCWardedJarBlockEntity restoredJar = new TCWardedJarBlockEntity(
                origin.offset(1, 0, 0),
                TCBlocks.JAR_NORMAL.get().defaultBlockState()
        );
        restoredJar.handleUpdateTag(tag, level.registryAccess());
        checks.add(check("warded_jar_label_filter_sync_preserves_facing_and_payload",
                restoredJar.aspectFilter() == Aspect.FIRE
                        && restoredJar.labelFacing() == Direction.WEST
                        && restoredJar.storedAspect() == Aspect.FIRE
                        && restoredJar.storedAmount() == TCPhialItem.BASE_AMOUNT,
                "filter=" + restoredJar.aspectFilter() + ", facing=" + restoredJar.labelFacing()
                        + ", amount=" + restoredJar.storedAmount()));
    }

    private static void addVoidJarAndMirrorChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        boolean voidJarRegistered = TCBlocks.JAR_VOID.get() instanceof thaumcraft.common.blocks.essentia.TCWardedJarBlock
                && TCItems.JAR_VOID.get() instanceof TCWardedJarBlockItem;
        checks.add(check("void_jar_is_registered_as_real_block_and_block_item",
                voidJarRegistered,
                "block=" + TCBlocks.JAR_VOID.get().getClass().getSimpleName()
                        + ", item=" + TCItems.JAR_VOID.get().getClass().getSimpleName()));

        level.setBlock(origin, TCBlocks.JAR_VOID.get().defaultBlockState(), 3);
        TCWardedJarBlockEntity voidJar = blockEntity(level, origin, TCWardedJarBlockEntity.class);
        if (voidJar == null) {
            checks.add(check("runtime_void_jar_block_entity_created", false, "void jar missing"));
            return;
        }

        voidJar.setStoredForValidation(Aspect.AIR, TCWardedJarBlockEntity.CAPACITY);
        int fullUnfilteredSuction = voidJar.getSuction(Direction.UP).amount();
        voidJar.setFilter(Aspect.AIR, Direction.NORTH);
        int fullFilteredSuction = voidJar.getSuction(Direction.UP).amount();
        int filteredMinimum = voidJar.getMinimumSuction();
        voidJar.setStoredForValidation(Aspect.AIR, TCWardedJarBlockEntity.CAPACITY - 1);
        int partialFilteredSuction = voidJar.getSuction(Direction.UP).amount();
        int overflowRemainder = voidJar.addToContainer(Aspect.AIR, 10);
        ItemStack carriedVoidJar = TCWardedJarBlockItem.stackFromJar(voidJar);
        checks.add(check("void_jar_overflow_and_suction_match_legacy",
                voidJar.kind() == TCWardedJarBlockEntity.Kind.VOID
                        && fullUnfilteredSuction == 32
                        && fullFilteredSuction == 32
                        && filteredMinimum == 48
                        && partialFilteredSuction == 48
                        && overflowRemainder == 0
                        && voidJar.storedAmount() == TCWardedJarBlockEntity.CAPACITY
                        && carriedVoidJar.is(TCItems.JAR_VOID.get())
                        && TCEssentiaItemHelper.aspectAmount(carriedVoidJar) == TCWardedJarBlockEntity.CAPACITY,
                "fullUnfiltered=" + fullUnfilteredSuction + ", fullFiltered=" + fullFilteredSuction
                        + ", partialFiltered=" + partialFilteredSuction + ", minimum=" + filteredMinimum
                        + ", overflowRemainder=" + overflowRemainder + ", stored=" + voidJar.storedAmount()));

        TCEssentiaTransport voidJarCapability = level.getCapability(TCEssentiaCapabilities.BLOCK, origin, Direction.UP);
        checks.add(check("void_jar_exposes_top_transport_capability",
                voidJarCapability == voidJar,
                "capability=" + (voidJarCapability != null)));

        boolean mirrorRegistered = TCBlocks.MIRROR_ESSENTIA.get() instanceof TCMirrorBlock
                && TCItems.MIRROR_ESSENTIA.get() instanceof TCMirrorBlockItem;
        checks.add(check("essentia_mirror_is_registered_as_real_block_and_block_item",
                mirrorRegistered,
                "block=" + TCBlocks.MIRROR_ESSENTIA.get().getClass().getSimpleName()
                        + ", item=" + TCItems.MIRROR_ESSENTIA.get().getClass().getSimpleName()));

        BlockState mirrorUp = TCBlocks.MIRROR_ESSENTIA.get().defaultBlockState().setValue(TCMirrorBlock.FACING, Direction.UP);
        BlockState mirrorDown = TCBlocks.MIRROR_ESSENTIA.get().defaultBlockState().setValue(TCMirrorBlock.FACING, Direction.DOWN);
        BlockState mirrorNorth = TCBlocks.MIRROR_ESSENTIA.get().defaultBlockState().setValue(TCMirrorBlock.FACING, Direction.NORTH);
        BlockState mirrorSouth = TCBlocks.MIRROR_ESSENTIA.get().defaultBlockState().setValue(TCMirrorBlock.FACING, Direction.SOUTH);
        BlockState mirrorWest = TCBlocks.MIRROR_ESSENTIA.get().defaultBlockState().setValue(TCMirrorBlock.FACING, Direction.WEST);
        BlockState mirrorEast = TCBlocks.MIRROR_ESSENTIA.get().defaultBlockState().setValue(TCMirrorBlock.FACING, Direction.EAST);
        checks.add(check("essentia_mirror_shapes_match_legacy_facing_boxes",
                sameBounds(mirrorDown.getShape(level, origin).bounds(), 0, 14, 0, 16, 16, 16)
                        && sameBounds(mirrorUp.getShape(level, origin).bounds(), 0, 0, 0, 16, 2, 16)
                        && sameBounds(mirrorNorth.getShape(level, origin).bounds(), 0, 0, 14, 16, 16, 16)
                        && sameBounds(mirrorSouth.getShape(level, origin).bounds(), 0, 0, 0, 16, 16, 2)
                        && sameBounds(mirrorWest.getShape(level, origin).bounds(), 14, 0, 0, 16, 16, 16)
                        && sameBounds(mirrorEast.getShape(level, origin).bounds(), 0, 0, 0, 2, 16, 16),
                "legacy AABB set verified for UP/DOWN/NORTH/SOUTH/WEST/EAST"));

        BlockPos localSupport = origin.offset(4, 0, 0);
        BlockPos localPos = localSupport.north();
        BlockPos remoteSupport = origin.offset(14, 0, 0);
        BlockPos remotePos = remoteSupport.north();
        BlockPos remoteJarPos = remotePos.north(3);
        level.setBlock(localSupport, Blocks.STONE.defaultBlockState(), 3);
        level.setBlock(remoteSupport, Blocks.STONE.defaultBlockState(), 3);
        level.setBlock(localPos, mirrorNorth, 3);
        level.setBlock(remotePos, mirrorNorth, 3);
        level.setBlock(remoteJarPos, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        TCMirrorEssentiaBlockEntity localMirror = blockEntity(level, localPos, TCMirrorEssentiaBlockEntity.class);
        TCMirrorEssentiaBlockEntity remoteMirror = blockEntity(level, remotePos, TCMirrorEssentiaBlockEntity.class);
        TCWardedJarBlockEntity remoteJar = blockEntity(level, remoteJarPos, TCWardedJarBlockEntity.class);
        if (localMirror == null || remoteMirror == null || remoteJar == null) {
            checks.add(check("runtime_essentia_mirror_fixture_created", false,
                    "local=" + (localMirror != null) + ", remote=" + (remoteMirror != null)
                            + ", jar=" + (remoteJar != null)));
            return;
        }
        localMirror.setLinkedTargetForValidation(level, remotePos);
        remoteJar.setStoredForValidation(Aspect.AIR, 2);
        boolean linkValid = localMirror.isLinkValidSimple()
                && remoteMirror.isLinkValidSimple()
                && localMirror.linkPos().equals(remotePos)
                && remoteMirror.linkPos().equals(localPos)
                && localMirror.linkedFacing() == Direction.NORTH;
        checks.add(check("essentia_mirror_restores_bidirectional_legacy_link",
                linkValid,
                "localLinked=" + localMirror.isLinkValidSimple() + ", remoteLinked=" + remoteMirror.isLinkValidSimple()
                        + ", facing=" + localMirror.linkedFacing()));

        TCEssentiaTransport mirrorCapability = level.getCapability(TCEssentiaCapabilities.BLOCK, localPos, Direction.NORTH);
        checks.add(check("essentia_mirror_is_not_direct_pipe_endpoint",
                mirrorCapability == null,
                "transportCapability=" + (mirrorCapability != null)));

        int availableBefore = localMirror.storedAspects().getAmount(Aspect.AIR);
        int simulated = localMirror.drainAspect(Aspect.AIR, 1, true);
        int drained = localMirror.drainAspect(Aspect.AIR, 1, false);
        int addRemainder = localMirror.addToContainer(Aspect.AIR, 1);
        int multiRemainder = localMirror.addToContainer(Aspect.AIR, 2);
        ItemStack linkedStack = TCMirrorBlockItem.stackFromMirror(localMirror);
        checks.add(check("essentia_mirror_bridges_remote_sources_one_point_at_a_time",
                availableBefore == 2
                        && simulated == 1
                        && drained == 1
                        && addRemainder == 0
                        && multiRemainder == 2
                        && remoteJar.storedAmount() == 2
                        && localMirror.instability() == 2
                        && linkedStack.has(TCDataComponents.MIRROR_LINK.get()),
                "available=" + availableBefore + ", simulated=" + simulated + ", drained=" + drained
                        + ", addRemainder=" + addRemainder + ", multiRemainder=" + multiRemainder
                        + ", remoteJar=" + remoteJar.storedAmount()
                        + ", instability=" + localMirror.instability()));

        localMirror.setInstabilityForValidation(65);
        TCMirrorEssentiaBlockEntity.serverTick(level, localPos, localMirror.getBlockState(), localMirror);
        checks.add(check("essentia_mirror_instability_pollutes_and_decays_like_legacy",
                localMirror.instability() == 0,
                "instabilityAfterTick=" + localMirror.instability()));
    }

    private static void addEssentiaTransfuserChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        boolean registered = TCBlocks.ESSENTIA_TRANSPORT_IN.get() instanceof TCEssentiaTransportBlock
                && TCBlocks.ESSENTIA_TRANSPORT_OUT.get() instanceof TCEssentiaTransportBlock
                && TCItems.ESSENTIA_TRANSPORT_IN.get() instanceof BlockItem
                && TCItems.ESSENTIA_TRANSPORT_OUT.get() instanceof BlockItem;
        checks.add(check("essentia_transfusers_are_registered_as_real_blocks_and_block_items",
                registered,
                "inputBlock=" + TCBlocks.ESSENTIA_TRANSPORT_IN.get().getClass().getSimpleName()
                        + ", outputBlock=" + TCBlocks.ESSENTIA_TRANSPORT_OUT.get().getClass().getSimpleName()));

        BlockState inputUp = TCBlocks.ESSENTIA_TRANSPORT_IN.get().defaultBlockState()
                .setValue(TCEssentiaTransportBlock.FACING, Direction.UP);
        BlockState inputDown = TCBlocks.ESSENTIA_TRANSPORT_IN.get().defaultBlockState()
                .setValue(TCEssentiaTransportBlock.FACING, Direction.DOWN);
        BlockState inputNorth = TCBlocks.ESSENTIA_TRANSPORT_IN.get().defaultBlockState()
                .setValue(TCEssentiaTransportBlock.FACING, Direction.NORTH);
        BlockState inputSouth = TCBlocks.ESSENTIA_TRANSPORT_IN.get().defaultBlockState()
                .setValue(TCEssentiaTransportBlock.FACING, Direction.SOUTH);
        BlockState inputWest = TCBlocks.ESSENTIA_TRANSPORT_IN.get().defaultBlockState()
                .setValue(TCEssentiaTransportBlock.FACING, Direction.WEST);
        BlockState inputEast = TCBlocks.ESSENTIA_TRANSPORT_IN.get().defaultBlockState()
                .setValue(TCEssentiaTransportBlock.FACING, Direction.EAST);
        checks.add(check("essentia_transfuser_shapes_match_legacy_facing_boxes",
                sameBounds(inputUp.getShape(level, origin).bounds(), 4, 0, 4, 12, 8, 12)
                        && sameBounds(inputDown.getShape(level, origin).bounds(), 4, 8, 4, 12, 16, 12)
                        && sameBounds(inputNorth.getShape(level, origin).bounds(), 4, 4, 8, 12, 12, 16)
                        && sameBounds(inputSouth.getShape(level, origin).bounds(), 4, 4, 0, 12, 12, 8)
                        && sameBounds(inputWest.getShape(level, origin).bounds(), 8, 4, 4, 16, 12, 12)
                        && sameBounds(inputEast.getShape(level, origin).bounds(), 0, 4, 4, 8, 12, 12),
                "legacy AABB set verified for UP/DOWN/NORTH/SOUTH/WEST/EAST"));

        BlockPos inputPos = origin;
        TCEssentiaTransfuserBlockEntity input = placeTransfuser(
                level,
                inputPos,
                TCEssentiaTransfuserBlockEntity.Kind.INPUT,
                Direction.NORTH
        );
        TCEssentiaTransfuserBlockEntity output = placeTransfuser(
                level,
                origin.offset(6, 0, 0),
                TCEssentiaTransfuserBlockEntity.Kind.OUTPUT,
                Direction.NORTH
        );
        if (input == null || output == null) {
            checks.add(check("runtime_essentia_transfuser_block_entities_created", false,
                    "input=" + (input != null) + ", output=" + (output != null)));
            return;
        }

        TCEssentiaTransport inputBack = level.getCapability(TCEssentiaCapabilities.BLOCK, inputPos, Direction.SOUTH);
        TCEssentiaTransport inputFront = level.getCapability(TCEssentiaCapabilities.BLOCK, inputPos, Direction.NORTH);
        TCEssentiaTransport outputBack = level.getCapability(TCEssentiaCapabilities.BLOCK, origin.offset(6, 0, 0), Direction.SOUTH);
        TCEssentiaTransport outputFront = level.getCapability(TCEssentiaCapabilities.BLOCK, origin.offset(6, 0, 0), Direction.NORTH);
        checks.add(check("essentia_transfuser_capability_is_back_face_only",
                inputBack == input && inputFront == null && outputBack == output && outputFront == null,
                "inputBack=" + (inputBack != null) + ", inputFront=" + (inputFront != null)
                        + ", outputBack=" + (outputBack != null) + ", outputFront=" + (outputFront != null)));
        checks.add(check("essentia_transfuser_io_contract_matches_legacy",
                input.canInputFrom(Direction.SOUTH)
                        && !input.canOutputTo(Direction.SOUTH)
                        && input.getSuction(Direction.SOUTH).amount() == 128
                        && output.canOutputTo(Direction.SOUTH)
                        && !output.canInputFrom(Direction.SOUTH)
                        && output.getSuction(Direction.SOUTH).amount() == 0,
                "inputSuction=" + input.getSuction(Direction.SOUTH).amount()
                        + ", outputSuction=" + output.getSuction(Direction.SOUTH).amount()));

        TCLegacyTubeBlockEntity source = placeTube(level, inputPos.south(), TCLegacyTubeVariant.BUFFER);
        level.setBlock(inputPos.north(3), TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        TCWardedJarBlockEntity jar = blockEntity(level, inputPos.north(3), TCWardedJarBlockEntity.class);
        if (source != null && jar != null) {
            source.addEssentia(Aspect.AIR.getTag(), 1, Direction.NORTH, false);
            source.addEssentia(Aspect.AIR.getTag(), 1, Direction.NORTH, false);
            for (int tick = 0; tick < 4; tick++) {
                TCEssentiaTransfuserBlockEntity.serverTick(level, inputPos, input.getBlockState(), input);
            }
            boolean unchangedBeforeFifth = jar.storedAmount() == 0;
            TCEssentiaTransfuserBlockEntity.serverTick(level, inputPos, input.getBlockState(), input);
            checks.add(check("essentia_input_moves_one_point_from_adjacent_transport_to_remote_source",
                    unchangedBeforeFifth
                            && jar.storedAspect() == Aspect.AIR
                            && jar.storedAmount() == 1
                            && source.transportNode().storage().amount(Aspect.AIR.getTag()) == 1,
                    "jar=" + jar.storedAmount() + ", source="
                            + source.transportNode().storage().amount(Aspect.AIR.getTag())));
        } else {
            checks.add(check("runtime_essentia_input_fixture_created", false,
                    "source=" + (source != null) + ", jar=" + (jar != null)));
        }

        BlockPos outputPos = origin.offset(6, 0, 0);
        TCLegacyTubeBlockEntity target = placeTube(level, outputPos.south(), TCLegacyTubeVariant.TUBE);
        level.setBlock(outputPos.north(3), TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        TCWardedJarBlockEntity sourceJar = blockEntity(level, outputPos.north(3), TCWardedJarBlockEntity.class);
        if (target != null && sourceJar != null) {
            target.setSuctionForValidation(Aspect.AIR.getTag(), 32);
            sourceJar.setStoredForValidation(Aspect.AIR, 1);
            for (int tick = 0; tick < 5; tick++) {
                TCEssentiaTransfuserBlockEntity.serverTick(level, outputPos, output.getBlockState(), output);
            }
            checks.add(check("essentia_output_drains_remote_source_into_adjacent_transport_demand",
                    sourceJar.storedAmount() == 0
                            && sourceJar.storedAspect() == null
                            && target.transportNode().storage().amount(Aspect.AIR.getTag()) == 1,
                    "jar=" + sourceJar.storedAmount() + ", target="
                            + target.transportNode().storage().amount(Aspect.AIR.getTag())));
        } else {
            checks.add(check("runtime_essentia_output_fixture_created", false,
                    "target=" + (target != null) + ", jar=" + (sourceJar != null)));
        }
    }

    private static TCLegacyTubeBlockEntity placeTube(ServerLevel level, BlockPos pos, TCLegacyTubeVariant variant) {
        level.setBlock(pos, blockFor(variant).defaultBlockState(), 3);
        return blockEntity(level, pos, TCLegacyTubeBlockEntity.class);
    }

    private static TCEssentiaTransfuserBlockEntity placeTransfuser(
            ServerLevel level,
            BlockPos pos,
            TCEssentiaTransfuserBlockEntity.Kind kind,
            Direction facing
    ) {
        net.minecraft.world.level.block.Block block = kind == TCEssentiaTransfuserBlockEntity.Kind.INPUT
                ? TCBlocks.ESSENTIA_TRANSPORT_IN.get()
                : TCBlocks.ESSENTIA_TRANSPORT_OUT.get();
        level.setBlock(
                pos,
                block.defaultBlockState().setValue(TCEssentiaTransportBlock.FACING, facing),
                3
        );
        return blockEntity(level, pos, TCEssentiaTransfuserBlockEntity.class);
    }

    private static boolean sameBounds(AABB bounds, double minX, double minY, double minZ, double maxX, double maxY, double maxZ) {
        double scale = 1.0D / 16.0D;
        return Math.abs(bounds.minX - minX * scale) < 0.0001D
                && Math.abs(bounds.minY - minY * scale) < 0.0001D
                && Math.abs(bounds.minZ - minZ * scale) < 0.0001D
                && Math.abs(bounds.maxX - maxX * scale) < 0.0001D
                && Math.abs(bounds.maxY - maxY * scale) < 0.0001D
                && Math.abs(bounds.maxZ - maxZ * scale) < 0.0001D;
    }

    private static net.minecraft.world.level.block.Block blockFor(TCLegacyTubeVariant variant) {
        return switch (variant) {
            case TUBE -> TCBlocks.TUBE.get();
            case BUFFER -> TCBlocks.TUBE_BUFFER.get();
            case FILTER -> TCBlocks.TUBE_FILTER.get();
            case ONEWAY -> TCBlocks.TUBE_ONEWAY.get();
            case RESTRICT -> TCBlocks.TUBE_RESTRICT.get();
            case VALVE -> TCBlocks.TUBE_VALVE.get();
        };
    }

    private static void clearArea(ServerLevel level, BlockPos origin, int radius) {
        for (int x = -radius; x <= radius; x++) {
            for (int y = -2; y <= 2; y++) {
                for (int z = -radius; z <= radius; z++) {
                    BlockPos pos = origin.offset(x, y, z);
                    level.removeBlockEntity(pos);
                    level.setBlock(pos, Blocks.AIR.defaultBlockState(), 3);
                }
            }
        }
    }

    private static <T> T blockEntity(ServerLevel level, BlockPos pos, Class<T> type) {
        Object value = level.getBlockEntity(pos);
        return type.isInstance(value) ? type.cast(value) : null;
    }

    private static Check check(String name, boolean passed, String notes) {
        return new Check(name, passed, notes);
    }

    public record Report(List<Check> checks) {
        public int passed() {
            return (int) checks.stream().filter(Check::passed).count();
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}

