package thaumcraft.common.essentia.transport;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.common.essentia.transport.block.TCLegacyTubeVariant;
import thaumcraft.common.essentia.transport.blockentity.TCLegacyTubeBlockEntity;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.registry.TCBlockEntities;
import thaumcraft.common.tiles.essentia.TCWardedJarBlockEntity;

/** Runtime checks for the legacy TileTube/TileJar transport contract. */
public final class TCEssentiaTransportBehaviorAudit {
    private TCEssentiaTransportBehaviorAudit() {
    }

    public static Report writeMarkdown(Path output, MinecraftServer server) throws IOException {
        Files.createDirectories(output.toAbsolutePath().normalize().getParent());
        Report report = run(server);
        ArrayList<String> lines = new ArrayList<>();
        lines.add("# Essentia Transport Behavior Audit");
        lines.add("");
        lines.add("Generated by the NeoForge runtime audit exporter against the ported TC6 transport contract.");
        lines.add("");
        lines.add("## Summary");
        lines.add("");
        lines.add("| Check | Result |");
        lines.add("|---|---:|");
        lines.add("| Passed | " + report.passed() + " |");
        lines.add("| Failed | " + report.failed() + " |");
        lines.add("");
        lines.add("## Checks");
        lines.add("");
        lines.add("| Name | Result | Notes |");
        lines.add("|---|---|---|");
        for (Check check : report.checks()) {
            lines.add("| " + check.name() + " | " + (check.passed() ? "PASS" : "FAIL")
                    + " | " + check.notes().replace("|", "\\|") + " |");
        }
        lines.add("");
        lines.add("## Boundary");
        lines.add("");
        lines.add("- Covers TC6 normal, buffer, filter, one-way, restrict and redstone-valve transport semantics.");
        lines.add("- Covers Warded Jar top-face suction and five-tick one-point transfer.");
        lines.add("- Does not claim smelter, alembic, bellows discovery, caster sub-part interaction or tube rendering parity.");
        Files.write(output, lines);
        return report;
    }

    private static Report run(MinecraftServer server) {
        ArrayList<Check> checks = new ArrayList<>();
        checks.add(check("normal_tube_capacity_is_one", TCLegacyTubeVariant.TUBE.storageCapacity() == 1,
                "capacity=" + TCLegacyTubeVariant.TUBE.storageCapacity()));
        checks.add(check("buffer_capacity_is_ten", TCLegacyTubeVariant.BUFFER.storageCapacity() == 10,
                "capacity=" + TCLegacyTubeVariant.BUFFER.storageCapacity()));
        checks.add(check("restrict_minimum_suction_is_zero", TCEssentiaTubeMode.RESTRICT.minimumSuction() == 0,
                "minimum=" + TCEssentiaTubeMode.RESTRICT.minimumSuction()));
        checks.add(check("filter_minimum_suction_is_zero", TCEssentiaTubeMode.FILTER.minimumSuction() == 0,
                "minimum=" + TCEssentiaTubeMode.FILTER.minimumSuction()));

        ServerLevel level = server.overworld();
        BlockPos origin = new BlockPos(256, level.getMinBuildHeight() + 16, 256);
        clearArea(level, origin, 24);

        TCLegacyTubeBlockEntity normal = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        if (normal == null) {
            checks.add(check("runtime_tube_block_entities_created", false, "normal tube missing"));
            return new Report(List.copyOf(checks));
        }
        int normalFirst = normal.addEssentia(Aspect.AIR.getTag(), 64, Direction.UP, false);
        int normalSecond = normal.addEssentia(Aspect.FIRE.getTag(), 1, Direction.UP, false);
        checks.add(check("normal_tube_accepts_exactly_one_point", normalFirst == 1 && normalSecond == 0
                        && normal.transportNode().storage().totalAmount() == 1,
                "first=" + normalFirst + ", second=" + normalSecond
                        + ", stored=" + normal.transportNode().storage().totalAmount()));
        int normalTaken = normal.takeEssentia(Aspect.AIR.getTag(), 64, Direction.DOWN, false);
        checks.add(check("normal_tube_outputs_exactly_one_point", normalTaken == 1
                        && normal.transportNode().storage().totalAmount() == 0,
                "taken=" + normalTaken));
        normal.setSuctionForValidation(Aspect.AIR.getTag(), 23);
        normal.setVentingForValidation(3);
        TCLegacyTubeBlockEntity.serverTick(level, origin, normal.getBlockState(), normal);
        checks.add(check("venting_pauses_normal_suction_cycle",
                normal.ventingTicks() == 2 && normal.getSuction(Direction.NORTH).amount() == 23,
                "venting=" + normal.ventingTicks() + ", suction="
                        + normal.getSuction(Direction.NORTH).amount()));

        TCLegacyTubeBlockEntity buffer = placeTube(level, origin.offset(3, 0, 0), TCLegacyTubeVariant.BUFFER);
        if (buffer != null) {
            int bulk = buffer.addEssentia(Aspect.AIR.getTag(), 2, Direction.UP, false);
            int accepted = 0;
            for (int index = 0; index < 10; index++) {
                accepted += buffer.addEssentia(
                        index % 2 == 0 ? Aspect.AIR.getTag() : Aspect.FIRE.getTag(),
                        1,
                        Direction.UP,
                        false
                );
            }
            int overflow = buffer.addEssentia(Aspect.WATER.getTag(), 1, Direction.UP, false);
            checks.add(check("buffer_accepts_only_single_point_calls_up_to_ten", bulk == 0 && accepted == 10
                            && overflow == 0 && buffer.transportNode().storage().totalAmount() == 10,
                    "bulk=" + bulk + ", accepted=" + accepted + ", overflow=" + overflow));
            buffer.setBellowsForValidation(2);
            int openSuction = buffer.getSuction(Direction.NORTH).amount();
            buffer.setChokedSide(Direction.NORTH, 1);
            int reducedSuction = buffer.getSuction(Direction.NORTH).amount();
            buffer.setChokedSide(Direction.NORTH, 2);
            int closedSuction = buffer.getSuction(Direction.NORTH).amount();
            checks.add(check("buffer_choke_levels_match_legacy", openSuction == 64
                            && reducedSuction == 1 && closedSuction == 0,
                    "open=" + openSuction + ", reduced=" + reducedSuction + ", closed=" + closedSuction));
        } else {
            checks.add(check("runtime_buffer_block_entity_created", false, "buffer missing"));
        }

        addSuctionPropagationChecks(level, origin.offset(0, 0, 6), checks);
        addTransferChecks(level, origin.offset(0, 0, 12), checks);
        addSideAndValveChecks(level, origin.offset(8, 0, 0), checks);
        addJarChecks(level, origin.offset(8, 0, 10), checks);
        clearArea(level, origin, 24);
        return new Report(List.copyOf(checks));
    }

    private static void addSuctionPropagationChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        TCLegacyTubeBlockEntity demand = placeTube(level, origin.east(), TCLegacyTubeVariant.TUBE);
        TCLegacyTubeBlockEntity normal = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        if (demand == null || normal == null) {
            checks.add(check("runtime_suction_fixture_created", false, "missing normal tube"));
            return;
        }
        demand.setSuctionForValidation(Aspect.AIR.getTag(), 32);
        normal.recalculateSuctionForValidation();
        checks.add(check("normal_tube_attenuates_suction_by_one",
                normal.getSuction(Direction.EAST).amount() == 31
                        && Aspect.AIR.getTag().equals(normal.getSuction(Direction.EAST).aspect()),
                "suction=" + normal.getSuction(Direction.EAST).amount()));

        level.removeBlock(origin, false);
        TCLegacyTubeBlockEntity restrict = placeTube(level, origin, TCLegacyTubeVariant.RESTRICT);
        if (restrict != null) {
            restrict.recalculateSuctionForValidation();
            checks.add(check("restrict_tube_halves_upstream_suction",
                    restrict.getSuction(Direction.EAST).amount() == 16,
                    "suction=" + restrict.getSuction(Direction.EAST).amount()));
        }

        level.removeBlock(origin, false);
        TCLegacyTubeBlockEntity filter = placeTube(level, origin, TCLegacyTubeVariant.FILTER);
        if (filter != null) {
            filter.setFilterAspect(Aspect.FIRE.getTag());
            filter.recalculateSuctionForValidation();
            int mismatch = filter.getSuction(Direction.EAST).amount();
            filter.setFilterAspect(Aspect.AIR.getTag());
            filter.recalculateSuctionForValidation();
            checks.add(check("filter_tube_propagates_only_matching_suction",
                    mismatch == 0 && filter.getSuction(Direction.EAST).amount() == 31,
                    "mismatch=" + mismatch + ", match=" + filter.getSuction(Direction.EAST).amount()));
        }

        level.removeBlock(origin, false);
        level.removeBlock(origin.east(), false);
        TCLegacyTubeBlockEntity oneWay = placeTube(level, origin, TCLegacyTubeVariant.ONEWAY);
        TCLegacyTubeBlockEntity southDemand = placeTube(level, origin.south(), TCLegacyTubeVariant.TUBE);
        if (oneWay != null && southDemand != null) {
            oneWay.setFacing(Direction.NORTH);
            southDemand.setSuctionForValidation(Aspect.AIR.getTag(), 32);
            oneWay.recalculateSuctionForValidation();
            int allowed = oneWay.getSuction(Direction.SOUTH).amount();
            level.removeBlock(origin.south(), false);
            TCLegacyTubeBlockEntity northDemand = placeTube(level, origin.north(), TCLegacyTubeVariant.TUBE);
            if (northDemand != null) {
                northDemand.setSuctionForValidation(Aspect.AIR.getTag(), 32);
                oneWay.recalculateSuctionForValidation();
            }
            checks.add(check("oneway_suction_uses_legacy_facing_side", allowed == 31
                            && oneWay.getSuction(Direction.NORTH).amount() == 0,
                    "allowed=" + allowed + ", blocked=" + oneWay.getSuction(Direction.NORTH).amount()));
        }
    }

    private static void addTransferChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        TCLegacyTubeBlockEntity source = placeTube(level, origin.west(), TCLegacyTubeVariant.TUBE);
        TCLegacyTubeBlockEntity target = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        if (source == null || target == null) {
            checks.add(check("runtime_transfer_fixture_created", false, "missing tube"));
            return;
        }
        source.addEssentia(Aspect.AIR.getTag(), 1, Direction.WEST, false);
        target.setSuctionForValidation(Aspect.AIR.getTag(), 32);
        target.equalizeForValidation();
        checks.add(check("normal_tube_moves_one_point_toward_stronger_suction",
                source.transportNode().storage().totalAmount() == 0
                        && target.transportNode().storage().amount(Aspect.AIR.getTag()) == 1,
                "source=" + source.transportNode().storage().totalAmount()
                        + ", target=" + target.transportNode().storage().totalAmount()));
    }

    private static void addSideAndValveChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        TCLegacyTubeBlockEntity left = placeTube(level, origin, TCLegacyTubeVariant.TUBE);
        TCLegacyTubeBlockEntity right = placeTube(level, origin.east(), TCLegacyTubeVariant.TUBE);
        if (left != null && right != null) {
            left.refreshConnectionState();
            right.refreshConnectionState();
            checks.add(check("tube_blockstate_tracks_capability_connections",
                    left.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                            && right.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST),
                    "leftEast=" + left.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                            + ", rightWest=" + right.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST)));
            left.setSideOpen(Direction.EAST, false);
            left.refreshConnectionState();
            right.refreshConnectionState();
            checks.add(check("tube_side_closure_is_reciprocal", !left.isSideOpen(Direction.EAST)
                            && !right.isSideOpen(Direction.WEST)
                            && !left.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.EAST)
                            && !right.getBlockState().getValue(thaumcraft.common.essentia.transport.block.TCLegacyTubeBlock.WEST),
                    "left=" + left.isSideOpen(Direction.EAST) + ", right=" + right.isSideOpen(Direction.WEST)));
            TCEssentiaTransport closedCapability = level.getCapability(
                    TCEssentiaCapabilities.BLOCK,
                    origin,
                    Direction.EAST
            );
            TCEssentiaTransport openCapability = level.getCapability(
                    TCEssentiaCapabilities.BLOCK,
                    origin,
                    Direction.NORTH
            );
            checks.add(check("sided_neoforge_capability_respects_open_sides",
                    closedCapability == null && openCapability == left,
                    "closed=" + (closedCapability != null) + ", open=" + (openCapability != null)));
            CompoundTag update = left.getUpdateTag(level.registryAccess());
            checks.add(check("tube_sync_tag_contains_directional_state",
                    update.contains("OpenSides") && update.contains("Facing")
                            && update.contains("SuctionAmount") && update.contains("FilterAspect"),
                    "keys=" + update.getAllKeys()));

            TCLegacyTubeBlockEntity persisted = TCBlockEntities.createTubeBlockEntity(
                    TCLegacyTubeVariant.FILTER,
                    origin.offset(0, 1, 0),
                    TCBlocks.TUBE_FILTER.get().defaultBlockState()
            );
            persisted.setFacing(Direction.UP);
            persisted.setSideOpen(Direction.SOUTH, false);
            persisted.setFilterAspect(Aspect.FIRE.getTag());
            persisted.setSuctionForValidation(Aspect.FIRE.getTag(), 23);
            persisted.addEssentia(Aspect.FIRE.getTag(), 1, Direction.NORTH, false);
            CompoundTag persistedTag = persisted.getUpdateTag(level.registryAccess());
            TCLegacyTubeBlockEntity restored = TCBlockEntities.createTubeBlockEntity(
                    TCLegacyTubeVariant.FILTER,
                    origin.offset(0, 2, 0),
                    TCBlocks.TUBE_FILTER.get().defaultBlockState()
            );
            restored.handleUpdateTag(persistedTag, level.registryAccess());
            checks.add(check("tube_nbt_round_trip_preserves_transport_state",
                    restored.facing() == Direction.UP
                            && !restored.isSideOpen(Direction.SOUTH)
                            && Aspect.FIRE.getTag().equals(restored.filterAspect())
                            && restored.getSuction(Direction.NORTH).amount() == 23
                            && restored.transportNode().storage().amount(Aspect.FIRE.getTag()) == 1,
                    "facing=" + restored.facing() + ", filter=" + restored.filterAspect()
                            + ", suction=" + restored.getSuction(Direction.NORTH).amount()
                            + ", stored=" + restored.transportNode().storage().totalAmount()));
        }

        BlockPos valvePos = origin.offset(0, 0, 3);
        TCLegacyTubeBlockEntity valve = placeTube(level, valvePos, TCLegacyTubeVariant.VALVE);
        if (valve != null) {
            valve.setFacing(Direction.NORTH);
            boolean faceRule = !valve.isConnectable(Direction.NORTH) && valve.isConnectable(Direction.SOUTH);
            level.setBlock(valvePos.east(), Blocks.REDSTONE_BLOCK.defaultBlockState(), 3);
            TCLegacyTubeBlockEntity.serverTick(level, valvePos, valve.getBlockState(), valve);
            checks.add(check("valve_excludes_handle_face_and_closes_when_powered",
                    faceRule && !valve.allowsFlow() && valve.getSuction(Direction.SOUTH).amount() == 0,
                    "faceRule=" + faceRule + ", flow=" + valve.allowsFlow()));
        }
    }

    private static void addJarChecks(ServerLevel level, BlockPos origin, ArrayList<Check> checks) {
        level.setBlock(origin, TCBlocks.JAR_NORMAL.get().defaultBlockState(), 3);
        TCLegacyTubeBlockEntity buffer = placeTube(level, origin.above(), TCLegacyTubeVariant.BUFFER);
        TCWardedJarBlockEntity jar = blockEntity(level, origin, TCWardedJarBlockEntity.class);
        if (jar == null || buffer == null) {
            checks.add(check("runtime_jar_fixture_created", false, "missing jar or buffer"));
            return;
        }
        buffer.addEssentia(Aspect.AIR.getTag(), 1, Direction.UP, false);
        buffer.addEssentia(Aspect.AIR.getTag(), 1, Direction.UP, false);
        for (int tick = 0; tick < 4; tick++) {
            TCWardedJarBlockEntity.serverTick(level, origin, jar.getBlockState(), jar);
        }
        boolean unchangedBeforeFifth = jar.storedAmount() == 0;
        TCWardedJarBlockEntity.serverTick(level, origin, jar.getBlockState(), jar);
        checks.add(check("warded_jar_pulls_one_point_every_five_ticks", unchangedBeforeFifth
                        && jar.storedAspect() == Aspect.AIR && jar.storedAmount() == 1
                        && buffer.transportNode().storage().amount(Aspect.AIR.getTag()) == 1,
                "jar=" + jar.storedAmount() + ", buffer="
                        + buffer.transportNode().storage().amount(Aspect.AIR.getTag())));
        int allOrNothing = jar.takeEssentia(Aspect.AIR.getTag(), 2, Direction.UP, false);
        checks.add(check("warded_jar_transport_take_is_all_or_nothing", allOrNothing == 0 && jar.storedAmount() == 1,
                "taken=" + allOrNothing + ", remaining=" + jar.storedAmount()));
        jar.setFilterForValidation(Aspect.FIRE);
        checks.add(check("filtered_warded_jar_has_legacy_suction",
                jar.getMinimumSuction() == 64 && jar.getSuction(Direction.UP).amount() == 64
                        && Aspect.FIRE.getTag().equals(jar.getSuction(Direction.UP).aspect()),
                "minimum=" + jar.getMinimumSuction() + ", suction=" + jar.getSuction(Direction.UP).amount()));
    }

    private static TCLegacyTubeBlockEntity placeTube(ServerLevel level, BlockPos pos, TCLegacyTubeVariant variant) {
        level.setBlock(pos, blockFor(variant).defaultBlockState(), 3);
        return blockEntity(level, pos, TCLegacyTubeBlockEntity.class);
    }

    private static net.minecraft.world.level.block.Block blockFor(TCLegacyTubeVariant variant) {
        return switch (variant) {
            case TUBE -> TCBlocks.TUBE.get();
            case BUFFER -> TCBlocks.TUBE_BUFFER.get();
            case FILTER -> TCBlocks.TUBE_FILTER.get();
            case ONEWAY -> TCBlocks.TUBE_ONEWAY.get();
            case RESTRICT -> TCBlocks.TUBE_RESTRICT.get();
            case VALVE -> TCBlocks.TUBE_VALVE.get();
        };
    }

    private static void clearArea(ServerLevel level, BlockPos origin, int radius) {
        for (int x = -radius; x <= radius; x++) {
            for (int y = -2; y <= 2; y++) {
                for (int z = -radius; z <= radius; z++) {
                    BlockPos pos = origin.offset(x, y, z);
                    level.removeBlockEntity(pos);
                    level.setBlock(pos, Blocks.AIR.defaultBlockState(), 3);
                }
            }
        }
    }

    private static <T> T blockEntity(ServerLevel level, BlockPos pos, Class<T> type) {
        Object value = level.getBlockEntity(pos);
        return type.isInstance(value) ? type.cast(value) : null;
    }

    private static Check check(String name, boolean passed, String notes) {
        return new Check(name, passed, notes);
    }

    public record Report(List<Check> checks) {
        public int passed() {
            return (int) checks.stream().filter(Check::passed).count();
        }

        public int failed() {
            return checks.size() - passed();
        }
    }

    public record Check(String name, boolean passed, String notes) {
    }
}
